cabal-version:      3.0
name:               cutesetup
version:            0.1.0.0
synopsis:           Cute TUI for scaffolding nix devshells
description:        A terminal UI to quickly generate flake.nix + .envrc for common languages
license:            Apache-2.0
license-file:       LICENSE
author:             Alice Liddell
maintainer:         Alice Liddell <rosegirl@tuta.io>
category:           Development, Utility, User Interfaces
homepage:           https://github.com/petalmaya/cutesetup
bug-reports:        https://github.com/petalmaya/cutesetup/issues
build-type:         Simple
extra-doc-files:    README.org

source-repository head
    type:     git
    location: https://github.com/petalmaya/cutesetup.git

common common-options
    default-language:   GHC2021
    default-extensions:
        TypeApplications
        OverloadedStrings
    ghc-options:        -Wall

common shared-deps
    build-depends:
        base                >= 4.14 && < 5,
        containers          >= 0.6  && < 1,
        directory           >= 1.3  && < 2,
        filepath            >= 1.4  && < 2,
        process             >= 1.6  && < 2,
        aeson               >= 2.1  && < 3,
        bytestring          >= 0.11 && < 1,
        vector              >= 0.13 && < 1

executable cutesetup
    import:           common-options, shared-deps
    main-is:          Main.hs
    other-modules:
        Languages
        NixGen
        NixSearch
        UI
    hs-source-dirs:   app, src
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N

    build-depends:
        brick               >= 2.1  && < 3,
        vty                 >= 6.0  && < 7,
        vty-unix            >= 0.2  && < 1,
        vty-crossplatform   >= 0.4  && < 0.5,
        text                >= 2.0  && < 3,
        microlens           >= 0.4  && < 1,
        microlens-platform  >= 0.4  && < 1,
        async               >= 2.2  && < 3,
        stm                 >= 2.5  && < 3

test-suite cutesetup-tests
    import:           common-options, shared-deps
    type:             exitcode-stdio-1.0
    main-is:          Spec.hs
    hs-source-dirs:   test, src
    build-depends:
        QuickCheck          >= 2.14 && < 3


