cabal-version:      3.0
name:               IStr
version:            0.1.0.0
x-revision: 3
synopsis:
        String Interpolation of Haskell expressions using #{expr} syntax 
description:
        Easy string interpolation of arbitrary haskell expressions.

        This is done using a custom class similar to Show except that with IStr except that it doesn't escape instances of IsString.
license:            MIT
license-file:       LICENSE
author:             lazyLambda
maintainer:         galen.sprout@gmail.com
-- copyright:
category:           Text
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

source-repository head
  type:                git
  location:            https://github.com/augyg/IStr   
common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  Text.IStr
    -- other-modules:
    -- other-extensions:
    
    build-depends:    base >= 4.19.0 && < 5
                    , template-haskell >= 2.21.0.0 && < 2.23
                    , haskell-src-meta >= 0.8.15 && < 0.9
    hs-source-dirs:   src
    default-language: Haskell2010
