cabal-version: >= 1.10
name:          array-mhs
version:       0.5.8.0
license:       Apache-2.0
license-file:  LICENSE
copyright:     2025 Lennart Augustsson
maintainer:    lennart@augustsson.net
bug-reports:   https://github.com/augustss/array-mhs/issues
synopsis:      Mutable and immutable arrays
category:      Data Structures
build-type:    Simple
description:
    This is a copy of the array package adapted for MicroHs.
    .
    In addition to providing the "Data.Array" module
    <http://www.haskell.org/onlinereport/haskell2010/haskellch14.html as specified in the Haskell 2010 Language Report>,
    this package also defines the classes 'IArray' of
    immutable arrays and 'MArray' of arrays mutable within appropriate
    monads, as well as some instances of these classes.

source-repository head
  type:     git
  location: https://github.com/augustss/array-mhs.git

library
  default-language: Haskell2010
  build-depends:
      base >= 4.5 && < 5
  exposed-modules:
      Data.Array
      Data.Array.Base
      Data.Array.IArray
      Data.Array.IO
      Data.Array.IO.Safe
      Data.Array.IO.Internals
      Data.Array.MArray
      Data.Array.MArray.Safe
      Data.Array.ST
      Data.Array.ST.Safe
      Data.Array.Storable
      Data.Array.Storable.Safe
      Data.Array.Storable.Internals
      Data.Array.Unboxed
      Data.Array.Unsafe
  other-modules:
      Data.Array.IOArray
      Data.Array.STArray
