cabal-version: 3.0
name: cache-effectful
version: 0.0.1.0
synopsis: A Cache effect for the effectful ecosystem.
category: cache
homepage:
  https://github.com/haskell-effectful/cache-effectful/tree/main/cache-effectful#readme

bug-reports: https://github.com/haskell-effectful/cache-effectful/issues
author: Hécate Moonlight
maintainer: Hécate Moonlight
license: MIT
build-type: Simple
tested-with: ghc ==9.10.3 || ==9.12.4 || ==9.14.1
extra-source-files:
  LICENSE.md
  README.md

extra-doc-files:
  CHANGELOG.md

source-repository head
  type: git
  location: https://github.com/haskell-effectful/cache-effectful

common common-extensions
  default-extensions:
    ConstraintKinds
    DataKinds
    FlexibleContexts
    FlexibleInstances
    GADTs
    KindSignatures
    ScopedTypeVariables
    TypeApplications
    TypeOperators

  default-language: Haskell2010

common common-ghc-options
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints
    -fhide-source-paths
    -Wno-unused-do-bind

common common-rts-options
  ghc-options:
    -rtsopts
    -threaded
    -with-rtsopts=-N

library
  import: common-extensions
  import: common-ghc-options
  hs-source-dirs: src
  exposed-modules: Effectful.Cache
  build-depends:
    base <4.23,
    cache >=0.1.3 && <0.2,
    effectful-core >=2.6 && <2.7,
    hashable >=1.5.1 && <1.6,

test-suite cache-effectful-test
  import: common-extensions
  import: common-ghc-options
  import: common-rts-options
  type: exitcode-stdio-1.0
  main-is: Main.hs
  other-modules: Utils
  hs-source-dirs: test
  build-depends:
    base,
    cache,
    cache-effectful,
    effectful-core,
    hashable,
    tasty >=1.5.4 && <1.6,
    tasty-hunit >=0.10.2 && <0.11,
