-- documentation, see http://haskell.org/cabal/users-guide/

name:                   aip-version
version:                0.0.0.3
synopsis:               Version of AIP documents
description:
  <<https://logo.systemf.com.au/systemf-450x450.jpg>>
  .
  A standalone executable to report the version of each AIP document
license:                BSD3
license-file:           LICENCE
author:                 Tony Morris <nɐ˙ɯoɔ˙ɟɯǝʇsʎs@ǝɹɐʍʇɟos>
maintainer:             Tony Morris <nɐ˙ɯoɔ˙ɟɯǝʇsʎs@ǝɹɐʍʇɟos>
copyright:              Copyright (C) 2024 Tony Morris
category:               Data, Aviation
build-type:             Simple
extra-source-files:     changelog.md
cabal-version:          >=1.10
homepage:               https://gitlab.com/aip-version/aip-version
bug-reports:            https://gitlab.com/aip-version/aip-version/issues
tested-with:            GHC == 8.6.5
                        GHC == 9.0.2
                        GHC == 9.4.8
                        GHC == 9.6.6
                        GHC == 9.8.2
source-repository       head
  type:                 git
  location:             git@gitlab.com:aip-version/aip-version.git

executable              aip-version
  build-depends:
                          base                 >= 4.9  && < 6
                        , bytestring           >= 0.10 && < 0.12
                        , http-client          >= 0.7  && < 0.8
                        , lens                 >= 5.3  && < 5.4
                        , optparse-applicative >= 0.18 && < 0.19
                        , parsec               >= 3.1  && < 3.2
                        , time                 >= 1.9  && < 1.12
                        , wreq                 >= 0.5  && < 0.6

  main-is:              Main.hs

  hs-source-dirs:       src

  default-language:     Haskell2010

  ghc-options:          -Wall
