cabal-version:      3.8
build-type:         Simple
name:               ghc-tags
version:            1.12
license:            MPL-2.0
license-file:       LICENSE
category:           Development
maintainer:         andrzej@rybczak.net
author:             Andrzej Rybczak
copyright:          Andrzej Rybczak
synopsis:           Utility for generating ctags and etags with GHC API.

description:
  Utility for generating etags (Emacs) and ctags (Vim and other editors) with
  GHC API for efficient project navigation.

extra-doc-files:
  CHANGELOG.md
  README.md

tested-with: GHC ^>= { 9.10, 9.12, 9.14 }

homepage:    https://github.com/arybczak/ghc-tags
bug-reports: https://github.com/arybczak/ghc-tags/issues
source-repository head
    type:     git
    location: https://github.com/arybczak/ghc-tags.git

common language
    ghc-options:        -Wall
                        -Wunused-packages
                        -Werror=missing-deriving-strategies
                        -Werror=name-shadowing
                        -Werror=prepositive-qualified-module

    default-language:   GHC2021

    default-extensions: DataKinds
                        DerivingStrategies
                        DerivingVia
                        GADTs
                        LambdaCase
                        MultiWayIf
                        OverloadedStrings
                        PatternSynonyms
                        RecordWildCards
                        StrictData
                        ViewPatterns

executable ghc-tags
    import:         language

    ghc-options:    -threaded -rtsopts

    build-depends:    base >= 4.20 && < 4.23
                    , async >= 2.2.5
                    , attoparsec
                    , bytestring
                    , containers
                    , deepseq
                    , directory
                    , filepath
                    , ghc >= 9.10 && < 9.15
                    , ghc-boot >= 9.10 && < 9.15
                    , ghc-paths
                    , optparse-applicative
                    , primitive
                    , process
                    , stm
                    , temporary
                    , text
                    , time
                    , yamlet >= 1.0

    hs-source-dirs:  src

    main-is:         Main.hs

    other-modules:   GhcTags
                     GhcTags.CTag
                     GhcTags.CTag.Formatter
                     GhcTags.CTag.Header
                     GhcTags.CTag.Parser
                     GhcTags.CTag.Utils
                     GhcTags.Config.Args
                     GhcTags.Config.Project
                     GhcTags.ETag
                     GhcTags.ETag.Formatter
                     GhcTags.ETag.Parser
                     GhcTags.Ghc
                     GhcTags.GhcCompat
                     GhcTags.Tag
                     GhcTags.Utils
                     Paths_ghc_tags

    autogen-modules: Paths_ghc_tags
