cabal-version:      3.0
name:               ghci-quickfix
version:            0.1.0.0
synopsis:           GHC plugin that writes errors to a file for use with quickfix
description:        GHC plugin that writes errors to a file for use with vim/nvim's quickfix system
license:            BSD-3-Clause
license-file:       LICENSE
author:             Aaron Allen
maintainer:         aaronallen8455@gmail.com
-- copyright:
category:           Development
build-type:         Simple
extra-doc-files:    CHANGELOG.md
                    README.md
tested-with: GHC == 9.12.1, GHC == 9.10.1, GHC == 9.8.1, GHC == 9.6.1
-- extra-source-files:

source-repository head
  type: git
  location: https://github.com/aaronallen8455/ghci-quickfix

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  GhciQuickfix
    other-modules: GhciQuickfix.GhcFacade
    -- other-extensions:
    build-depends:    base < 4.23,
                      ghc >= 9.6 && < 9.13,
                      text,
                      async >= 2.2 && < 3,
                      stm-containers >= 1.2 && < 1.3,
                      directory,
                      stm,
                      deferred-folds >= 0.9 && < 1,
                      foldl >= 1 && < 2
    hs-source-dirs:   src
    default-language: GHC2021

test-suite ghci-quickfix-test
    import:           warnings
    default-language: GHC2021
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    ghc-options: -threaded -with-rtsopts=-N
    build-depends:
        base,
        ghci-quickfix,
        tasty,
        tasty-hunit,
        process,
        directory,
        async

-- executable play
--     import:           warnings
--     default-language: GHC2021
--     hs-source-dirs:   play
--     main-is:          Main.hs
--     build-depends:
--         base,
--         ghci-quickfix
--     ghc-options: -fplugin GhciQuickfix
