cabal-version:   2.0
name:            debug-print
version:         0.2.0.0
license:         MIT
license-file:    LICENSE
maintainer:      Freckle Education
homepage:        https://github.com/freckle/debug-print#readme
bug-reports:     https://github.com/freckle/debug-print/issues
synopsis:        A structured alternative to Show
category:        Debug
build-type:      Simple
extra-doc-files:
    README.md
    CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/freckle/debug-print

library
    exposed-modules:
        DebugPrint
        DebugPrint.Aeson
        DebugPrint.Class
        DebugPrint.Integer
        DebugPrint.Show
        DebugPrint.Tagged
        DebugPrint.Types

    hs-source-dirs:     library
    other-modules:      Paths_debug_print
    autogen-modules:    Paths_debug_print
    default-language:   GHC2021
    default-extensions:
        DefaultSignatures DeriveAnyClass DerivingVia NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction OverloadedStrings
        StrictData

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missing-import-lists -Wno-missing-kind-signatures
        -Wno-missing-safe-haskell-mode -Wno-safe -Wno-unsafe

    build-depends:
        aeson >=2.2.3.0,
        base >=4.19.2.0 && <5,
        containers >=0.6.8,
        internal,
        text >=2.1.1

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures

library internal
    exposed-modules:    DebugPrint.Core
    hs-source-dirs:     internal
    other-modules:      Paths_debug_print
    autogen-modules:    Paths_debug_print
    default-language:   GHC2021
    default-extensions:
        DefaultSignatures DeriveAnyClass DerivingVia NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction OverloadedStrings
        StrictData

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missing-import-lists -Wno-missing-kind-signatures
        -Wno-missing-safe-haskell-mode -Wno-safe -Wno-unsafe

    build-depends:
        base >=4.19.2.0 && <5,
        containers >=0.6.8,
        text >=2.1.1,
        vector >=0.13.2.0

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures

test-suite readme
    type:               exitcode-stdio-1.0
    main-is:            README.lhs
    other-modules:      Paths_debug_print
    autogen-modules:    Paths_debug_print
    default-language:   GHC2021
    default-extensions:
        DefaultSignatures DeriveAnyClass DerivingVia NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction OverloadedStrings
        StrictData

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missing-import-lists -Wno-missing-kind-signatures
        -Wno-missing-safe-haskell-mode -Wno-safe -Wno-unsafe -pgmL
        markdown-unlit

    build-depends:
        aeson >=2.2.3.0,
        base >=4.19.2.0 && <5,
        debug-print,
        hspec >=2.11.11,
        markdown-unlit >=0.6.0,
        text >=2.1.1

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures

test-suite spec
    type:               exitcode-stdio-1.0
    main-is:            Main.hs
    hs-source-dirs:     tests
    other-modules:      Paths_debug_print
    autogen-modules:    Paths_debug_print
    default-language:   GHC2021
    default-extensions:
        DefaultSignatures DeriveAnyClass DerivingVia NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction OverloadedStrings
        StrictData

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missing-import-lists -Wno-missing-kind-signatures
        -Wno-missing-safe-haskell-mode -Wno-safe -Wno-unsafe

    build-depends:
        aeson-qq >=0.8.4,
        base >=4.19.2.0 && <5,
        debug-print,
        hspec >=2.11.11,
        text >=2.1.1

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures
