cabal-version:   3.0
name:            visualize-cbn
version:         0.2.2
synopsis:        Visualize CBN reduction
description:     CBN interpretation and visualization tool.
                 Exports in text format, coloured text (ANSI) or HTML/JavaScript.
license:         BSD-3-Clause
license-file:    LICENSE
author:          Edsko de Vries
maintainer:      edsko@well-typed.com
copyright:       Well-Typed LLP
category:        Development
build-type:      Simple
extra-doc-files: ChangeLog.md README.md CONTRIBUTORS

tested-with:
  GHC == 9.14.1
  GHC == 9.12.4
  GHC == 9.10.3
  GHC == 9.8.4
  GHC == 9.6.7
  GHC == 9.4.8
  GHC == 9.2.8
  GHC == 8.10.7

source-repository head
  type:     git
  location: https://github.com/well-typed/visualize-cbn

common lang
  build-depends:    base >= 4.14 && < 4.23
  default-language: Haskell2010

  default-extensions:
      DeriveDataTypeable
      ExistentialQuantification
      FlexibleInstances
      LambdaCase
      RecordWildCards
      ScopedTypeVariables
      StandaloneDeriving
      TupleSections

  ghc-options:
      -Wall
      -fno-warn-orphans
      -rtsopts
      "-with-rtsopts=-M128M"

  if impl(ghc >= 9.8)
    ghc-options:
      -Wno-x-partial

executable visualize-cbn
  import:         lang
  main-is:        Main.hs
  hs-source-dirs: src

  other-modules:
      CBN.Closure
      CBN.Eval
      CBN.Free
      CBN.Heap
      CBN.InlineHeap
      CBN.Language
      CBN.Options
      CBN.Parser
      CBN.Pretty
      CBN.Pretty.Precedence
      CBN.SelThunkOpt
      CBN.Subst
      CBN.Trace
      CBN.Trace.Graph
      CBN.Trace.HeapGraph
      CBN.Trace.JavaScript
      CBN.Trace.JSON
      CBN.Trace.Textual
      CBN.Util.Doc
      CBN.Util.Doc.Rendered
      CBN.Util.Doc.Rendered.ANSI
      CBN.Util.Doc.Rendered.HTML
      CBN.Util.Doc.Rendered.String
      CBN.Util.Doc.Style
      CBN.Util.Map
      CBN.Util.Snoc

  build-depends:
    , aeson                >= 2.0  && < 2.4
    , ansi-terminal        >= 1.0  && < 1.2
    , bytestring           >= 0.10 && < 0.13
    , blaze-html           >= 0.9  && < 0.10
    , blaze-markup         >= 0.8  && < 0.9
    , containers           >= 0.6  && < 0.9
    , data-default         >= 0.7  && < 0.9
    , mtl                  >= 2.2  && < 2.4
    , optparse-applicative >= 0.18 && < 0.20
    , parsec               >= 3.1  && < 3.2
    , template-haskell     >= 2.16 && < 2.25
    , text                 >= 1.2  && < 2.2

  other-extensions:
      GeneralizedNewtypeDeriving
      OverloadedStrings
      TemplateHaskell
