cabal-version: 3.0
name: haxl-effectful
version: 1.0.0
category: Concurrency
synopsis: Effectful bindings for Haxl
description:
  Adaptation of the @<https://hackage.haskell.org/package/haxl Haxl>@ library for the @<https://hackage.haskell.org/package/effectful effectful>@ ecosystem.

license: EUPL-1.2
license-file: LICENCE
author: IDA
maintainer: IDA
homepage: https://digital-autonomy.institute
bug-reports: https://issues.digital-autonomy.institute
build-type: Simple
extra-doc-files:
  CHANGELOG.md

extra-source-files:
  test/LoadCache.txt

common common
  default-language: Haskell2010
  ghc-options:
    -Weverything
    -Wno-unsafe
    -Wno-all-missed-specialisations
    -Wno-missing-export-lists
    -Wno-missing-import-lists
    -Wno-missing-kind-signatures
    -Wno-missing-poly-kind-signatures
    -Wno-missing-role-annotations
    -Wno-missing-safe-haskell-mode
    -Wno-name-shadowing

  default-extensions:
    ApplicativeDo
    BlockArguments
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveGeneric
    DerivingStrategies
    DerivingVia
    ExplicitNamespaces
    FlexibleContexts
    FlexibleInstances
    GADTs
    ImportQualifiedPost
    LambdaCase
    MultiParamTypeClasses
    NamedFieldPuns
    NoImplicitPrelude
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    RankNTypes
    RecordWildCards
    RecursiveDo
    ScopedTypeVariables
    TemplateHaskell
    TypeApplications
    TypeFamilies
    TypeOperators
    ViewPatterns

  build-depends:
    base >=4.10 && <5,
    effectful >=2.6 && <2.7,
    hashable >=1.5 && <1.6,

library
  import: common
  hs-source-dirs: src
  build-depends:
    haxl >=2.5 && <2.6

  exposed-modules:
    Effectful.Haxl

test-suite test
  import: common
  type: exitcode-stdio-1.0
  ghc-options: -threaded
  hs-source-dirs: test
  main-is: Main.hs
  other-modules:
    ExampleDataSource
    LoadCache

  build-depends:
    filepath >=1.5 && <1.6,
    haxl-effectful,
    hspec-effectful >=1.0 && <1.1,
    text >=2.1 && <2.2,
