cabal-version:   1.18
name:            wai-middleware-openapi
version:         0.1.0.0
license:         MIT
license-file:    LICENSE
maintainer:      Freckle Education
synopsis:        TODO
description:     TODO
category:        Web
build-type:      Simple
extra-doc-files:
    README.md
    CHANGELOG.md

library
    exposed-modules:
        Network.Wai.Middleware.OpenApi
        Network.Wai.Middleware.OpenApi.PathMap
        Network.Wai.Middleware.OpenApi.Schema
        Network.Wai.Middleware.OpenApi.Validate
        Network.Wai.Middleware.OpenApi.ValidationError

    hs-source-dirs:     src
    other-modules:      Paths_wai_middleware_openapi
    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingStrategies DerivingVia
        DuplicateRecordFields GADTs LambdaCase NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction NoPostfixOperators
        OverloadedRecordDot OverloadedStrings QuasiQuotes TypeFamilies

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-missing-safe-haskell-mode -Wno-monomorphism-restriction
        -Wno-prepositive-qualified-module -Wno-safe -Wno-unsafe

    build-depends:
        aeson >=2.0.3.0,
        base >=4.16.4.0 && <5,
        bytestring >=0.11.4.0,
        filepath >=1.4.2.2,
        http-media >=0.8.0.0,
        http-types >=0.12.3,
        insert-ordered-containers >=0.2.5.2,
        lens >=5.1.1,
        mtl >=2.2.2,
        openapi3 >=3.2.3,
        text >=1.2.5.0,
        wai >=3.2.4

    if impl(ghc >=9.8)
        ghc-options: -Wno-missing-role-annotations

    if impl(ghc >=9.2)
        ghc-options: -Wno-missing-kind-signatures

test-suite spec
    type:               exitcode-stdio-1.0
    main-is:            Spec.hs
    hs-source-dirs:     tests
    other-modules:
        Network.Wai.Middleware.OpenApi.PathMapSpec
        Network.Wai.Middleware.OpenApiSpec
        TestApp
        Paths_wai_middleware_openapi

    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingStrategies DerivingVia
        DuplicateRecordFields GADTs LambdaCase NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction NoPostfixOperators
        OverloadedRecordDot OverloadedStrings QuasiQuotes TypeFamilies

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-missing-safe-haskell-mode -Wno-monomorphism-restriction
        -Wno-prepositive-qualified-module -Wno-safe -Wno-unsafe -threaded
        -rtsopts -with-rtsopts=-N

    build-depends:
        aeson >=2.0.3.0,
        base >=4.16.4.0 && <5,
        hspec >=2.9.7,
        http-types >=0.12.3,
        insert-ordered-containers >=0.2.5.2,
        lens >=5.1.1,
        openapi3 >=3.2.3,
        text >=1.2.5.0,
        wai >=3.2.4,
        wai-extra >=3.1.13.0,
        wai-middleware-openapi

    if impl(ghc >=9.8)
        ghc-options: -Wno-missing-role-annotations

    if impl(ghc >=9.2)
        ghc-options: -Wno-missing-kind-signatures
