cabal-version:      3.0
name:               canvhs
version:            0.2.0.0
synopsis:           Simple HTML5 graphics for MicroHs
description:        Simple HTML5 graphics and sound for MicroHs
license:            Apache-2.0
license-file:       LICENSE
author:             Lennart Augustsson
maintainer:         lennart@augustsson.net
copyright:          2026 Lennart Augustsson
category:           Web
build-type:         Simple
stability:          experimental

extra-source-files:
                      LICENSE
                      README.md

source-repository head
  type:                git
  location:            https://github.com/augustss/canvhs

library
    default-language: Haskell98
    exposed-modules:  Graphics.CanvHs,
                      Graphics.CanvHs.Color,
                      Graphics.CanvHs.Picture,
                      Graphics.CanvHs.Demo,
                      Audio.AudHs.FFI
    -- other-modules:
    -- other-extensions:
    build-depends:    base ^>=4.22.0.0
    hs-source-dirs:   src
