cabal-version:   3.0
name:            dependent-enummap
version:         0.2.0.0
synopsis:        A generalisation of EnumMap to dependent types
description:
  A generalisation of EnumMap to dependent key and value types. The key type
  needs to be an instance of class Enum1, a generalisation of the Enum class.
  Most of the API of EnumMap/IntMap is supported, usually by wrapping IntMap
  operations in coercions accompanied by some runtime type-consistency
  assertions.
license:         BSD-3-Clause
copyright:       (c) 2025-2026 Tom Smeding, Mikolaj Konarski
author:          Tom Smeding, Mikolaj Konarski
maintainer:      Tom Smeding <xhackage@tomsmeding.com>
category:        Data, Dependent Types
build-type:      Simple
extra-doc-files: CHANGELOG.md

library
  exposed-modules:
    Data.Dependent.EnumMap.Strict
    Data.Dependent.EnumMap.Strict.Internal
    -- Data.Dependent.EnumMap.Strict.Unsafe
  build-depends:
    base >= 4.15 && < 4.23,
    containers >= 0.6 && < 0.9,
    dependent-sum >= 0.7 && < 0.8,
    some >= 1 && < 2,
  hs-source-dirs: src
  default-language: Haskell2010
  ghc-options: -Wall -Wcompat -Widentities -Wredundant-constraints -Wunused-packages -Wpartial-fields -Wredundant-bang-patterns -Woperator-whitespace -Wredundant-strictness-flags


test-suite test
  type: exitcode-stdio-1.0
  main-is: Main.hs
  build-depends:
    base,
    dependent-enummap,
    dependent-sum,
    some,
  hs-source-dirs: test
  default-language: Haskell2010
  ghc-options: -Wall

source-repository head
  type: git
  location: https://git.tomsmeding.com/dependent-enummap
