name:           symbol
version:        0.3.0
cabal-version:  >= 1.10
license:        BSD3
license-file:   LICENSE
copyright:      (c) 2006-2011 Harvard University
                (c) 2011-2026 Geoffrey Mainland
author:         Geoffrey Mainland <mainland@drexel.edu>
maintainer:     Geoffrey Mainland <mainland@drexel.edu>
stability:      alpha
homepage:       https://github.com/mainland/symbol
category:       Data
synopsis:       A 'Symbol' type for fast symbol comparison.
description:    Provides a 'Symbol' data type allowing fast symbol comparisons
                and functions for interning symbols and recovering their
                'String' representation.
tested-with:    GHC==8.0.2,
                GHC==8.2.2,
                GHC==8.4.3,
                GHC==8.6.5,
                GHC==8.8.4,
                GHC==8.10.7,
                GHC==9.0.2,
                GHC==9.2.2,
                GHC==9.4.8,
                GHC==9.6.4,
                GHC==9.8.2,
                GHC==9.10.1,
                GHC==9.12.4,
                GHC==9.14.1

build-type:     Simple

extra-source-files:
  README.md
  CHANGELOG.md
  .stylish-haskell.yaml

library
  hs-source-dirs: src

  exposed-modules:
    Data.Symbol
    Data.Symbol.Unsafe

  build-depends:
    base       >= 4.9 && < 5,
    containers >= 0.2 && < 0.9,
    deepseq    >= 1.0 && < 2

  default-language: Haskell2010
  ghc-options: -Wall

test-suite symbol-tests
  type: exitcode-stdio-1.0
  hs-source-dirs: tests
  main-is: Main.hs

  build-depends:
    base             >= 4.9  && < 5,
    symbol,
    tasty            >= 1.4  && < 1.6,
    tasty-hunit      >= 0.10 && < 0.11,
    tasty-quickcheck >= 0.10 && < 0.12

  default-language: Haskell2010
  ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N2

source-repository head
  type:     git
  location: https://github.com/mainland/symbol.git
