Name:                zip2tar
Version:             0.0
Synopsis:            Convert ZIP to TAR archives
Description:
  Convert ZIP to TAR archives with minimal memory footprint.
  .
  Usage:
  .
  > zip2tar input.zip >output.tar
  .
  > zip2tar input.zip | lzip >output.tar.lz
  .
  ZIP archives cannot be read in a purely sequential way,
  because the central file catalogue is stored at the end of the archive file.
  Thus we do not provide reading ZIP archives from Stdin.
  .
  Per default @zip2tar@ stores files in the TAR archive
  in the same order as the ZIP archive in order to minimize seeking.
  However this means unsorted filenames.
  You can order with respect to filenames with the @--sort-by-name@ option.
  .
  Per default @zip2tar@ sets user and group
  ids to zero and names to empty strings,
  because we do not know what is available on the system
  where the TAR archive gets unpacked.
  You may set those values individually like in:
  .
  > zip2tar --user-name janedoe --user-id 42 --group-name users --group-id 23 input.zip
  .
  @zip2tar@ does not try to derive id from name or vice versa.
  If you want certain values you must set them explicitly.
  You may want to set the values to the settings of the current system like so:
  .
  > zip2tar --user-name $USER --user-id $UID --group-name $(id -gn) --group-id $(id -g) input.zip
Homepage:            https://hub.darcs.net/thielema/zip2tar
License:             BSD3
License-File:        LICENSE
Author:              Henning Thielemann
Maintainer:          haskell@henning-thielemann.de
Category:            Archive, Codec
Build-Type:          Simple
Cabal-Version:       >=1.10

Source-Repository this
  Tag:         0.0
  Type:        darcs
  Location:    https://hub.darcs.net/thielema/zip2tar

Source-Repository head
  Type:        darcs
  Location:    https://hub.darcs.net/thielema/zip2tar

-- Alternative: https://github.com/dylex/zip-stream 2017
-- Alternative: https://github.com/timcherganov/zip-conduit 2022, has no way to "conduit" the whole archive

Executable zip2tar
  Build-Depends:
    zip >=2.2 && <2.3,
    tar-conduit >=0.4.1 && <0.5,
    conduit >=1.3 && <1.4,
    optparse-applicative >=0.11 && <0.20,
    time >=1.0 && <1.16,
    bytestring >=0.10 && <0.13,
    containers >=0.6 && <0.9,
    base >=4.5 && <5
  Hs-Source-Dirs:      src
  Main-Is:             Main.hs
  Default-Language:    Haskell2010
  GHC-Options:
    -Wall -fwarn-incomplete-uni-patterns -fwarn-tabs
