cabal-version:   3.0
name:            ghc-build-stats-plugin
version:         0.1.0.0
x-revision: 1
synopsis:        A plugin for collecting GHC build statistics
description:     A plugin for collecting GHC build statistics
license:         BSD-3-Clause
license-file:    LICENSE
author:          Teo Camarasu
maintainer:      teofilcamarasu@gmail.com
copyright:       ghc-build-stats Contributors
category:        Development
build-type:      Simple
extra-doc-files: CHANGELOG.md
bug-reports:     https://codeberg.org/teo/ghc-build-stats/issues
tested-with:     
  GHC ==9.10
  ||  ==9.12
  ||  ==9.14

common warnings
  ghc-options: -Wall

library
  import:           warnings
  exposed-modules:  GHC.BuildStats.Plugin
  build-depends:
    -- Only depend on boot libs
    , base >= 4.20 && < 4.23
    , containers >= 0.7 && < 0.9
    , filepath >= 1.5 && < 1.6
    , ghc >= 9.10 && <9.15

  hs-source-dirs:   src
  default-language: GHC2024


source-repository head
  type:     git
  location: https://codeberg.org/teo/ghc-build-stats.git
  subdir: ghc-build-stats-plugin
