cabal-version:      3.0
name:               gruvbox-colors
version:            0.1.0.0
synopsis:           Gruvbox colors for use in Haskell
description:        See README.md at https://github.com/ccntrq/gruvbox-colors-hs
homepage:           https://github.com/ccntrq/gruvbox-colors-hs
license:            MIT
license-file:       LICENSE
author:             Alexander 'ccntrq' Pankoff
maintainer:         ccntrq@screenri.de
category:           Graphics
build-type:         Simple
extra-doc-files:  
  CHANGELOG.md
  README.md

source-repository head
  type:     git
  location: https://github.com/ccntrq/gruvbox-colors-hs

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  Graphics.Colors.Gruvbox
    -- other-modules:
    -- other-extensions:
    build-depends:    base ^>=4.20.0.0
    hs-source-dirs:   src
    default-language: Haskell2010
