cabal-version: 3.0
name: hunit-effectful
version: 1.0.0
synopsis: Effectful driver for HUnit
description:
  Adaptation of the @<https://hackage.haskell.org/package/HUnit HUnit>@ library for the @<https://hackage.haskell.org/package/effectful effectful>@ ecosystem.

license: EUPL-1.2
license-file: LICENCE
author: IDA
maintainer: IDA
homepage: https://digital-autonomy.institute
bug-reports: https://issues.digital-autonomy.institute
category: Test
build-type: Simple
extra-doc-files:
  CHANGELOG.md

common common
  default-language: Haskell2010
  ghc-options:
    -Weverything
    -Wno-unsafe
    -Wno-missing-safe-haskell-mode
    -Wno-missing-export-lists
    -Wno-missing-import-lists
    -Wno-missing-kind-signatures
    -Wno-all-missed-specialisations
    -Wno-missing-role-annotations

  default-extensions:
    ApplicativeDo
    BlockArguments
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveGeneric
    DerivingStrategies
    DerivingVia
    ExplicitNamespaces
    FlexibleContexts
    FlexibleInstances
    ImportQualifiedPost
    LambdaCase
    MultiParamTypeClasses
    NoImplicitPrelude
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    RankNTypes
    RecordWildCards
    RecursiveDo
    TypeFamilies
    TypeOperators
    ViewPatterns

  build-depends:
    base >=4.16 && <5

library
  import: common
  hs-source-dirs: src
  build-depends:
    HUnit >=1.6 && <1.7,
    effectful-core >=2.6 && <2.7,

  exposed-modules:
    Effectful.HUnit
