name:                 reader
version:              0.0.6
synopsis:             A reader data type with all the bits
description:          A reader data type with all the bits and type constructor rearrangements
license:              BSD3
license-file:         LICENCE
author:               Tony Morris <ʇǝu˙sıɹɹoɯʇ@ןןǝʞsɐɥ>
maintainer:           Tony Morris <ʇǝu˙sıɹɹoɯʇ@ןןǝʞsɐɥ>
copyright:            Copyright (C) 2021-2025 Tony Morris
category:             Test
build-type:           Simple
extra-source-files:   changelog.md
cabal-version:        >=1.10
homepage:             https://gitlab.com/tonymorris/reader
bug-reports:          https://gitlab.com/tonymorris/reader/issues
tested-with:          GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.3, GHC == 8.6.5, GHC == 9.4.8, GHC == 9.10.1, GHC == 9.12.2

source-repository     head
  type:               git
  location:           git@gitlab.com:tonymorris/reader.git

library
  exposed-modules:    Data.Reader
                      Data.Reader.Reader
                      Data.Reader.Reader1
                      Data.Reader.Reader2
                      Data.Reader.Reader3
                      Data.Reader.Readers

  build-depends:        base >= 4.8 && < 6
                      , contravariant >= 1 && < 2
                      , distributive >= 0.5 && < 1
                      , lens >= 4 && < 6
                      , mmorph >= 1.1 && < 2
                      , mtl >= 2.2 && < 3
                      , profunctors >= 5 && < 6
                      , transformers >= 0.5 && < 1
                      , semigroupoids >= 5.3 && < 7

  hs-source-dirs:     src
  default-language:   Haskell2010
  ghc-options:        -Wall
