cabal-version:      3.4
name:               qute-syntax
version:            0.1.0
synopsis:           This package provides a parser for the QBE intermediate language.
description:
  This library provides a parser for the [QBE intermediate language](https://c9x.me/compile/)
  and algebraic data types to represent various QBE constructs. This package is the foundation
  of the [Qute](https://hackage.haskell.org/package/qute) software analysis framework.
license:            GPL-3.0-only AND BSD-2-Clause AND MIT
-- license-file:
author:             Sören Tempel
maintainer:         soeren+hackage@soeren-tempel.net
-- copyright:
category:           Language
build-type:         Simple
homepage:           https://git.8pit.net/qute
bug-reports:        https://github.com/nmeum/qute/issues

source-repository head
    type: git
    location: https://git.8pit.net/qute.git

common warnings
    ghc-options: -Wall

library
    import:           warnings
    -- other-extensions:
    hs-source-dirs:   src
    default-language: GHC2021

    other-modules:
      Language.QBE.Util,
      Language.QBE.Numbers

    exposed-modules:
      Language.QBE,
      Language.QBE.Types,
      Language.QBE.Parser

    build-depends:
      base >= 4.16.4.0 && < 4.23,
      parsec >= 3.1.15 && < 3.19,
      containers >= 0.6.5.1 && < 0.9,
      exceptions >= 0.10.4 && < 0.11

test-suite qute-syntax-test
    import:           warnings
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs

    other-modules:
      Parser,
      Golden,
      Types

    build-depends:
        base,
        qute-syntax,
        parsec,
        process,
        filepath,
        containers,
        tasty        >=1.4.3,
        tasty-hunit  >=0.10,
        tasty-golden >=2.3.5,
