Name:          hsqml-demo-notes
Version:       0.3.4.0
Cabal-version: >= 1.10
Build-type:    Simple
License:       BSD3
License-file:  LICENSE
Copyright:     (c) 2014-2015 Robin KAY, (c) 2025 Sascha-Oliver Prolic
Author:        Robin KAY
Maintainer:    saschaprolic@googlemail.com
Stability:     experimental
Homepage:      http://www.gekkou.co.uk/software/hsqml/
Category:      Graphics
Synopsis:      Sticky notes example program implemented in HsQML
Data-dir:      qml
Data-files:    *.qml *.png
Extra-source-files:
    README CHANGELOG
Description:
    Sticky notes example program implemented in HsQML.

Executable hsqml-notes
    Default-language: Haskell2010
    Hs-source-dirs: src
    Main-is: NotesFast.hs
    Build-depends:
        base          == 4.*,
        containers    >= 0.4 && < 0.7,
        text          >= 2.0 && < 2.1,
        transformers  >= 0.2 && < 0.7,
        sqlite-simple >= 0.4.8 && < 0.5,
        hsqml         >= 0.3.6 && < 0.4
    GHC-options: -threaded

Executable hsqml-notes-slow
    Default-language: Haskell2010
    Hs-source-dirs: src
    Main-is: NotesSlow.hs
    Build-depends:
        base          == 4.*,
        text          >= 2.0 && < 2.1,
        sqlite-simple >= 0.4.8 && < 0.5,
        hsqml         >= 0.3.6 && < 0.4
    GHC-options: -threaded

Source-repository head
    type:     git
    location: https://github.com/prolic/hsqml-demo-notes
