cabal-version:      2.2
name:               fearOfView
version:            0.1.0.1
license:            AGPL-3.0-or-later
license-file:       COPYING
maintainer:         mbays@sdf.org
author:             mbays
homepage:           https://mbays.sdf.org/fov/
synopsis:           A terminal broughlike game about manipulating vision
description:
    A constrained roguelike ("broughlike") game played on a 5x5 grid of cells
    which are regenerated when out of view. Designed for colour terminals,
    using the ncurses library.
category:           Game
extra-doc-files: CHANGELOG.md README.md fov-shot.png

source-repository head
    type: git
    location: https://thegonz.net/~fov/fearOfView.git

flag debug
    description: Enable debug keys
    default:     False
    manual:      True

executable fearOfView
    main-is:           Main.hs
    pkgconfig-depends: ncursesw
    other-modules:
        AStar
        Board
        BoardConf
        Command
        Creature
        CPos
        CStyle
        CursesDraw
        CursesUI
        CursesUIMInstance
        Equipment
        Exit
        Inventory
        Game
        GameName
        Group
        Highscore
        HighscoreFile
        Item
        KeyBindings
        Pos
        Power
        Rand
        RollFrom
        UIMonad
        Serialise
        Tutorial
        Wall

    default-language:  Haskell2010
    ghc-options:       -Wall
    build-depends:
        base >=4.3 && <5,
        mtl >=2.2 && <2.4,
        safe >=0.3.18 && <0.4,
        containers >=0.4 && <0.9,
        directory >=1.2.3.0 && <1.4,
        filepath >=1.0 && <2.1,
        safe-exceptions >=0.1 && <0.2,
        hscurses >=1.4 && <1.6,
        MonadRandom >=0.6 && <0.7,
        splitmix >=0.1 && <0.2,
        random >=1.3 && <1.4,
        serialise >=0.2 && <0.3,
        bytestring >=0.10 && <0.13,
        hashable >=1.4 && <1.6,
        unordered-containers >=0.2 && <0.3,
        astar >=0.3 && <0.4,
        filelock >=0.1 && <0.2

    if flag(debug)
        cpp-options: -DDEBUG
