Cabal-Version:  2.2
Name:           align-audio
Version:        0.0.0.2
License:        BSD-3-Clause
License-File:   LICENSE
Author:         Henning Thielemann <haskell@henning-thielemann.de>
Maintainer:     Henning Thielemann <haskell@henning-thielemann.de>
Category:       Sound
Synopsis:       Find relative time displacement of two recordings of the same music
Description:
  Say, you have a video with some background music
  and a clean recording of the background music.
  You want to know exact displacement of the background music.
  This program should find it.
  .
  > align-audio orig.wav video.wav
  .
  The program actually performs a simple correlation.
  .
  The program can handle sources of different sample rates
  if the sample rates are integers.
  .
  You can specify the precision of the displacement using the @--rate@ option,
  which must be a positive integer:
  .
  > align-audio --rate 1000 orig.wav video.wav
  .
  For reading of audio files, @libsox@ is used
  and thus you can use all audio formats supported by SoX.
  .
  Cabal-Flags:
  .
  * @blas@ for running with 'comfort-blas' (more memory consumption)
  .
  * @lapack@ for running with 'lapack' (heavier dependency)

Tested-With:    GHC==8.6.5
Build-Type:     Simple
Extra-Source-Files:
  Makefile

Flag blas
  Description: Build executable using BLAS support
  Manual: True
  Default: False

Flag lapack
  Description: Build executable using LAPACK support (less memory consumption than BLAS)
  Manual: True
  Default: False

Source-Repository this
  Tag:         0.0.0.2
  Type:        darcs
  Location:    http://hub.darcs.net/thielema/align-audio/

Source-Repository head
  Type:        darcs
  Location:    http://hub.darcs.net/thielema/align-audio/

Common Vector
  Build-Depends:
    comfort-fftw >=0.0 && <0.1,
    comfort-array >=0.5 && <0.6,
    storablevector >=0.2 && <0.3,
    netlib-ffi >=0.1.1 && <0.2,
    Stream >=0.4.7 && <0.5,
    numeric-prelude >=0.4.1 && <0.5,
  If flag(lapack)
    Hs-Source-Dirs: src/lapack
    Build-Depends:
      lapack >=0.4 && <0.6,
  Else
    If flag(blas)
      Hs-Source-Dirs: src/blas
      Build-Depends:
        comfort-blas >=0.0 && <0.1,
    Else
      Hs-Source-Dirs: src/plain
  Other-Modules: Vector

Executable align-audio
  Import: Vector
  Build-Depends:
    containers >=0.2 && <0.9,
    synthesizer-core >=0.7 && <0.10,
    soxlib >=0.0.1 && <0.1,
    shell-utility >=0.0 && <0.2,
    optparse-applicative >=0.11 && <0.20,
    utility-ht >=0.0.12 && <0.1,
    base >=3 && <5

  Default-Language: Haskell98
  GHC-Options:    -Wall
  Hs-Source-Dirs: src
  Main-Is:        Main.hs
  Other-Modules:
    Correlate
    CorrelateResample
    Common
    Option

Test-Suite align-audio-test
  Import:           Vector
  Type:             exitcode-stdio-1.0
  Default-Language: Haskell98
  GHC-Options:      -Wall
  Hs-source-dirs:   src, test
  Main-Is:          Test.hs
  Other-Modules:
    Test.Correlate
    Test.CorrelateResample
    Correlate
    CorrelateResample
    Common
  Build-Depends:
    doctest-exitcode-stdio >=0.0 && <0.1,
    doctest-lib >=0.1 && <0.2,
    QuickCheck >=2 && <3,
    base >=3 && <5
