Cabal-Version:       3.14
name:                Diff
version:             2.0.0
synopsis:            Diff algorithm in pure Haskell
description:         Implementation of the standard diff algorithm in Haskell.
 .
 Time complexity is O(ND) (input length * number of differences).
 Space complexity is O(D^2).  Includes utilities for pretty printing.
category:            Algorithms
homepage:            https://web.archive.org/web/20150326181224/http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.4.6927
license:             BSD-3-Clause
license-file:        LICENSE
author:              Sterling Clover
maintainer:          David Fox <dsf@seereason.com>
build-Type:          Simple
extra-doc-files:     README.md, CHANGELOG.md
extra-files:         ./Diff-liquidhaskell/Diff-liquidhaskell.cabal
bug-reports:         https://github.com/seereason/Diff/issues

tested-with:
  GHC == 9.14.1
  GHC == 9.12.2
  GHC == 9.10.3
  GHC == 9.8.4
  GHC == 9.6.7
  GHC == 9.4.8
  GHC == 9.2.8
  GHC == 9.0.2
  GHC == 8.10.7
  GHC == 8.8.4
  GHC == 8.6.5
  GHC == 8.4.4

library
  default-language: Haskell2010
  build-depends:
      base >= 4.11 && <= 6
    , array
    , pretty >= 1.1
  hs-source-dirs:  src
  exposed-modules:
                   Data.Algorithm.Diff
                   Data.Algorithm.DiffOutput
                   Data.Algorithm.DiffContext
  other-modules:   Data.Algorithm.Diff.Refinement
                   Data.Algorithm.Diff.Type
  ghc-options:     -Wall -funbox-strict-fields

source-repository head
  type:      git
  location:  https://github.com/seereason/Diff

test-suite diff-tests
  default-language: Haskell2010
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Test.hs
  build-depends:
      Diff
    , base >= 3 && <= 6
    , array
    , pretty
    , directory
    , process
    , QuickCheck
    , test-framework
    , test-framework-quickcheck2

benchmark simple
  default-language: Haskell2010
  type: exitcode-stdio-1.0
  main-is: bench/bench.hs
  build-depends:
      Diff
    , base >= 3 && <= 6
    , criterion
    , deepseq
    , random
