cabal-version:      1.18
name:               mdoc
version:            0.1.1.2
license:            AGPL-3
license-file:       COPYING
maintainer:         Pat Brisbin
homepage:           https://codeberg.org/pbrisbin/mdoc#readme
bug-reports:        https://codeberg.org/pbrisbin/mdoc/issues
synopsis:           Parser and pretty-printer for the mdoc(7) language
description:
    This library parses, represents, pretty-prints, or generates man-page content
    using the [mdoc(7)](https://mandoc.bsd.lv/man/mdoc.7.html) language.
    .
    To parse a man-page and work with its data in a structured way,
    .
    * Use @parseMdocBytes@ from the "Mdoc.Input" module
    .
    To pretty-print parsed (or constructed) man-page data,
    .
    * Use @prettyMdoc@ from the @Mdoc@ module and @putDoc@ in "Mdoc.Gen"
    .
    To generate a man-page from a supported parser library, check the appropriate
    integration module,
    .
    * @envparse@ -- "Env.Mdoc"
    * @opt-env-conf@ -- "OptEnvConf.Mdoc"
    * @optparse-applicative@ -- "Options.Applicative.Mdoc"
    .
    An example and screenshots can be seen at the project homepage.

category:           Text
build-type:         Simple
extra-source-files:
    data/man1.template
    data/man5.template

extra-doc-files:
    README.md
    CHANGELOG.md

source-repository head
    type:     git
    location: https://codeberg.org/pbrisbin/mdoc

library
    exposed-modules:
        Autodocodec.Schema.Mdoc
        Env.Mdoc
        Mdoc
        Mdoc.Detect
        Mdoc.Dump.Diff
        Mdoc.Dump.Env
        Mdoc.Dump.Main
        Mdoc.Dump.Options
        Mdoc.Gen
        Mdoc.Gen.Argument
        Mdoc.Gen.Config
        Mdoc.Gen.CrossRef
        Mdoc.Gen.Described
        Mdoc.Gen.Description
        Mdoc.Gen.Environment
        Mdoc.Gen.EnvVar
        Mdoc.Gen.ExitStatus
        Mdoc.Gen.File
        Mdoc.Gen.Flag
        Mdoc.Gen.Man1
        Mdoc.Gen.Man5
        Mdoc.Gen.Name
        Mdoc.Gen.Option
        Mdoc.Gen.Optionality
        Mdoc.Gen.Synopsis
        Mdoc.Gen.Template
        Mdoc.Input
        Mdoc.Interpolated
        Mdoc.Interpolation
        Mdoc.MacroArg
        Mdoc.MacroName
        Mdoc.MdocLine
        Mdoc.Optics
        Mdoc.Parse
        Mdoc.Parse.Interpolation
        Mdoc.Parse.MacroArg
        Mdoc.Parse.MacroName
        Mdoc.Parse.MdocLine
        Mdoc.Parse.TableLine
        Mdoc.Parse.TroffMacro
        Mdoc.Prelude
        Mdoc.Pretty
        Mdoc.Pretty.Interpolation
        Mdoc.Pretty.MacroArg
        Mdoc.Pretty.MacroName
        Mdoc.Pretty.MdocLine
        Mdoc.Pretty.TableLine
        Mdoc.Pretty.TroffMacro
        Mdoc.TableLine
        Mdoc.TroffMacro
        Mdoc.UpdateMdocdate
        OptEnvConf.Mdoc
        Options.Applicative.Mdoc

    hs-source-dirs:     src
    other-modules:      Paths_mdoc
    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingStrategies DerivingVia
        DuplicateRecordFields GADTs LambdaCase NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction OverloadedRecordDot
        OverloadedStrings RecordWildCards TypeFamilies QuasiQuotes

    ghc-options:
        -fignore-optim-changes -fwrite-ide-info -Weverything
        -Wno-all-missed-specialisations -Wno-missed-specialisations
        -Wno-missing-exported-signatures -Wno-missing-import-lists
        -Wno-missing-kind-signatures -Wno-missing-local-signatures
        -Wno-missing-role-annotations -Wno-missing-safe-haskell-mode
        -Wno-monomorphism-restriction -Wno-prepositive-qualified-module
        -Wno-safe -Wno-unsafe -optP-Wno-nonportable-include-path

    build-depends:
        Diff >=0.5,
        aeson >=2.2.3.0,
        autodocodec-schema >=0.2.0.1 && <0.2.0.2,
        base >=4.19.2.0 && <5,
        bytestring >=0.12.1.0,
        containers >=0.6.8,
        envparse >=0.6.0,
        extra >=1.7.16,
        file-embed >=0.0.16.0,
        filepath >=1.4.301.0,
        generic-optics >=2.2.1.0,
        megaparsec >=9.6.1,
        mtl >=2.3.1,
        opt-env-conf >=0.8.0.0,
        optics >=0.4.2.1,
        optparse-applicative >=0.18.1.0,
        prettyprinter >=1.7.1,
        prettyprinter-ansi-terminal >=1.1.3,
        text >=2.1.1,
        time >=1.12.2,
        zlib >=0.7.1.0

executable mdoc-dump
    main-is:            Main.hs
    hs-source-dirs:     dump
    other-modules:      Paths_mdoc
    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingStrategies DerivingVia
        DuplicateRecordFields GADTs LambdaCase NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction OverloadedRecordDot
        OverloadedStrings RecordWildCards TypeFamilies QuasiQuotes

    ghc-options:
        -fignore-optim-changes -fwrite-ide-info -Weverything
        -Wno-all-missed-specialisations -Wno-missed-specialisations
        -Wno-missing-exported-signatures -Wno-missing-import-lists
        -Wno-missing-kind-signatures -Wno-missing-local-signatures
        -Wno-missing-role-annotations -Wno-missing-safe-haskell-mode
        -Wno-monomorphism-restriction -Wno-prepositive-qualified-module
        -Wno-safe -Wno-unsafe -optP-Wno-nonportable-include-path -threaded
        -rtsopts -with-rtsopts=-N

    build-depends:
        base >=4.19.2.0 && <5,
        mdoc

test-suite readme
    type:               exitcode-stdio-1.0
    main-is:            README.lhs
    build-tool-depends: markdown-unlit:markdown-unlit
    other-modules:      Paths_mdoc
    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingStrategies DerivingVia
        DuplicateRecordFields GADTs LambdaCase NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction OverloadedRecordDot
        OverloadedStrings RecordWildCards TypeFamilies QuasiQuotes

    ghc-options:
        -fignore-optim-changes -fwrite-ide-info -Weverything
        -Wno-all-missed-specialisations -Wno-missed-specialisations
        -Wno-missing-exported-signatures -Wno-missing-import-lists
        -Wno-missing-kind-signatures -Wno-missing-local-signatures
        -Wno-missing-role-annotations -Wno-missing-safe-haskell-mode
        -Wno-monomorphism-restriction -Wno-prepositive-qualified-module
        -Wno-safe -Wno-unsafe -optP-Wno-nonportable-include-path -pgmL
        markdown-unlit

    build-depends:
        base >=4.19.2.0 && <5,
        mdoc

test-suite spec
    type:               exitcode-stdio-1.0
    main-is:            Spec.hs
    hs-source-dirs:     test
    other-modules:
        Autodocodec.Schema.MdocSpec
        Mdoc.Gen.DescriptionSpec
        Mdoc.Gen.ExitStatusSpec
        Mdoc.Gen.FlagSpec
        Mdoc.GenSpec
        Mdoc.Parse.MacroArgSpec
        Mdoc.Parse.MdocLineSpec
        Mdoc.Parse.TableLineSpec
        Mdoc.Parse.TroffMacroSpec
        Mdoc.Test.Fixtures
        Mdoc.Test.Parse
        Mdoc.Test.Render
        Mdoc.UpdateMdocdateSpec
        MdocSpec
        Paths_mdoc

    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingStrategies DerivingVia
        DuplicateRecordFields GADTs LambdaCase NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction OverloadedRecordDot
        OverloadedStrings RecordWildCards TypeFamilies QuasiQuotes

    ghc-options:
        -fignore-optim-changes -fwrite-ide-info -Weverything
        -Wno-all-missed-specialisations -Wno-missed-specialisations
        -Wno-missing-exported-signatures -Wno-missing-import-lists
        -Wno-missing-kind-signatures -Wno-missing-local-signatures
        -Wno-missing-role-annotations -Wno-missing-safe-haskell-mode
        -Wno-monomorphism-restriction -Wno-prepositive-qualified-module
        -Wno-safe -Wno-unsafe -optP-Wno-nonportable-include-path -threaded
        -rtsopts -with-rtsopts=-N

    build-depends:
        aeson >=2.2.3.0,
        autodocodec >=0.4.2.2 && <0.6,
        autodocodec-schema >=0.2.0.1,
        base >=4.19.2.0 && <5,
        bytestring >=0.12.1.0,
        envparse >=0.6.0,
        filepath >=1.4.301.0,
        hspec >=2.11.12,
        hspec-golden >=0.2.2.0,
        mdoc,
        opt-env-conf >=0.8.0.0,
        optparse-applicative >=0.18.1.0,
        text >=2.1.1,
        time >=1.12.2
