cabal-version: 3.4
name: comonad-coactions
-- The package version.
-- See the Haskell package versioning policy (PVP) for standards
-- guiding when and how versions should be incremented.
-- https://pvp.haskell.org
-- PVP summary:     +-+------- breaking API changes
--                  | | +----- non-breaking API additions
--                  | | | +--- code changes with no API change
version: 0.1.0.1
synopsis: Coactions of comonads on functors
description:
  This package defines classes for left and right coactions of
  comonads on functors.

license: LGPL-2.0-or-later
license-file: LICENSE
author: noiioiu
maintainer: noiioiu@cocaine.ninja
homepage: https://codeberg.org/noiioiu/comonad-coactions
category:
  Control,
  Comonads

build-type: Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall

source-repository head
  type: git
  location: ssh://git@codeberg.org/noiioiu/comonad-coactions.git

library
  import: warnings
  exposed-modules:
    Control.Comonad.Coaction
    Control.Comonad.Coaction.Left
    Control.Comonad.Coaction.Right
    Control.Comonad.TransformerStack

  other-modules: Control.Comonad.Coaction.TH
  build-depends:
    adjunctions >=4.4.4 && <4.5,
    base >=4.20.2 && <4.23,
    comonad >=5.0.10 && <5.1,
    free >=5.2 && <5.3,
    kan-extensions >=5.2.8 && <5.3,
    template-haskell >=2.23.0 && <2.25,

  hs-source-dirs: src
  default-language: GHC2024

flag examples
  description: Build examples
  default: False
  manual: True

executable elementary
  import: warnings

  if !flag(examples)
    buildable: False
  default-language: GHC2024
  hs-source-dirs: examples
  main-is: ElementaryCA.hs
  build-depends:
    base,
    comonad,
    comonad-coactions,
    finite-typelits >=0.2.1 && <0.3,
    random >=1.3.1 && <1.4,
    terminal-size >=0.3.4 && <0.4,
    vector-sized >=1.6.1 && <1.7,

executable higher-range
  import: warnings

  if !flag(examples)
    buildable: False
  default-language: GHC2024
  hs-source-dirs: examples
  main-is: HigherRange.hs
  build-depends:
    base,
    comonad,
    comonad-coactions,
    finite-typelits >=0.2.1 && <0.3,
    random >=1.3.1 && <1.4,
    terminal-size >=0.3.4 && <0.4,
    vector-sized >=1.6.1 && <1.7,

executable life
  import: warnings

  if !flag(examples)
    buildable: False
  default-language: GHC2024
  hs-source-dirs: examples
  main-is: Life.hs
  ghc-options:
    -threaded
    -rtsopts
    -fplugin
    GHC.TypeLits.KnownNat.Solver

  build-depends:
    adjunctions,
    base,
    clock >=0.8.4 && <0.9,
    comonad,
    comonad-coactions,
    constraints >=0.14.4 && <0.15,
    distributive >=0.6.3 && <0.7,
    finite-typelits >=0.2.1 && <0.3,
    ghc-typelits-knownnat >=0.8.3 && <0.9,
    ki >=1.0.1 && <1.1,
    monad-actions >=2.0.1 && <2.1,
    mtl >=2.3.1 && <2.4,
    optparse-applicative >=0.19.0 && <0.20,
    random >=1.3.1 && <1.4,
    termbox-tea >=1.0.0 && <1.1,
    text >=2.1.2 && <2.2,
    vector-sized >=1.6.1 && <1.7,

test-suite comonad-coactions-test
  import: warnings
  default-language: GHC2024
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  build-depends:
    QuickCheck,
    base,
    checkers,
    comonad,
    comonad-coactions,
    containers,
    tasty,
    tasty-quickcheck,
