cabal-version: 3.0
name: align-equal
version: 1.0.1.0
license: MIT
license-file: LICENSE
author: Joonkyu Park (based on original work by Gabriella Gonzalez)
build-type: Simple
synopsis: Aligns text prefixes before '=' for consistent formatting
description: A utility to adjust text lines by padding spaces before '=' based on the longest prefix.
category: Text
maintainer: vpark45@gmail.com
bug-reports: https://hub.darcs.net/vincent/align-equal/issues
extra-doc-files:
  CHANGELOG.md
  README.md

source-repository head
  type: darcs
  location: https://hub.darcs.net/vincent/align-equal

common warnings
  ghc-options: -Wall

executable align-equal
  import: warnings
  main-is: Main.hs
  build-depends:
    align-equal,
    base >=4.17 && <4.19,
    text >=2.0.2 && <2.1,

  hs-source-dirs: app
  default-language: Haskell2010

library
  import: warnings
  exposed-modules: Data.Text.AlignEqual
  build-depends:
    base >=4.17 && <4.19,
    safe >=0.3.21 && <0.4,
    text >=2.0.2 && <2.1,

  hs-source-dirs: src
  default-language: Haskell2010

test-suite your-project-test
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Spec.hs
  build-depends:
    align-equal,
    base,
    hspec,
    safe,
    text,

  default-language: Haskell2010
