cabal-version: 2.2

name: co-log-simple
version: 1.2.1
synopsis: Simple enhancements for logging with co-log
description: A library built upon co-log that makes constructing and using
  `LogAction`s simpler with some predefined formatters and a slightly enhanced
  Severity type
author: Dino Morelli
maintainer: dino@ui3.info
copyright: 2025 Dino Morelli
category: Logging
license: ISC
license-file: LICENSE
build-type: Simple
extra-source-files:
  .gitignore
  README.md
  stack.yaml
extra-doc-files:
  CHANGELOG.md

source-repository head
  type: git
  location: https://codeberg.org/dinofp/co-log-simple

common lang
  default-language: Haskell2010
  default-extensions:
    BangPatterns
    DeriveFoldable
    DeriveFunctor
    DeriveGeneric
    DeriveLift
    DeriveTraversable
    EmptyCase
    FlexibleContexts
    FlexibleInstances
    GeneralizedNewtypeDeriving
    ImportQualifiedPost
    InstanceSigs
    KindSignatures
    LambdaCase
    MultiParamTypeClasses
    MultiWayIf
    NamedFieldPuns
    NumericUnderscores
    OverloadedStrings
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
  ghc-options:
    -fwarn-tabs
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints
  build-depends:
      base >=3 && <5
    , co-log >=0.7.0.0 && <0.8

library
  import: lang
  exposed-modules:
      Colog.Simple
      Colog.Simple.Message
      Colog.Simple.Severity
  hs-source-dirs:
    src/lib
  build-depends:
      ansi-terminal >=1.0.2 && <2
    , co-log-core >=0.3.2.1 && <0.4
    , mtl >=2.3.1 && <3
    , text >=2.0.2 && <2.2
    , time >=1.4 && <1.16

executable co-log-simple
  import: lang
  main-is: Main.hs
  hs-source-dirs:
    src/examples
  build-depends:
      co-log-simple
