cabal-version: 3.4
name: diagnostician-html
version: 0.2.0.1
license: (Apache-2.0 OR MIT)
maintainer: root@owenlynch.org
author: Coln contributors
description: Lucid HTML rendering backend for Diagnostician
category: Language

source-repository head
  type: git
  location: https://github.com/coln-project/Coln

library
  exposed-modules: Diagnostician.HTML
  hs-source-dirs: src
  default-language: GHC2024
  default-extensions:
    DuplicateRecordFields
    NoFieldSelectors
    OverloadedRecordDot
    OverloadedStrings

  ghc-options:
    -Wall

  build-depends:
    base ^>=4.21.0.0 || ^>=4.22,
    diagnostician,
    lucid,
    prettyprinter,
    prettyprinter-lucid,
    text,
