cabal-version:   1.18
name:            ronn-optparse-applicative
version:         1.0.2.0
license:         AGPL-3
maintainer:      Pat Brisbin
homepage:        https://github.com/pbrisbin/ronn#readme
bug-reports:     https://github.com/pbrisbin/ronn/issues
synopsis:        Produce Ronn from OptEnvConf
description:     Please see README.md
category:        Documentation
build-type:      Simple
extra-doc-files:
    README.md
    CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/pbrisbin/ronn

library
    exposed-modules:    Ronn.Options.Applicative
    hs-source-dirs:     src
    other-modules:      Paths_ronn_optparse_applicative
    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingStrategies DerivingVia
        DuplicateRecordFields GADTs LambdaCase NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction OverloadedRecordDot
        OverloadedStrings RecordWildCards TypeFamilies

    ghc-options:
        -fignore-optim-changes -fwrite-ide-info -Weverything
        -Wno-all-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-kind-signatures
        -Wno-missing-local-signatures -Wno-missing-safe-haskell-mode
        -Wno-monomorphism-restriction -Wno-prepositive-qualified-module
        -Wno-safe -Wno-unsafe

    build-depends:
        base >=4.16.4.0 && <5,
        optparse-applicative >=0.17.1.0,
        ronn >=1.1.2.0,
        text >=1.2.5.0

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures

test-suite spec
    type:               exitcode-stdio-1.0
    main-is:            Main.hs
    hs-source-dirs:     tests
    other-modules:
        Ronn.Options.ApplicativeSpec
        Paths_ronn_optparse_applicative

    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingStrategies DerivingVia
        DuplicateRecordFields GADTs LambdaCase NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction OverloadedRecordDot
        OverloadedStrings RecordWildCards TypeFamilies

    ghc-options:
        -fignore-optim-changes -fwrite-ide-info -Weverything
        -Wno-all-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-kind-signatures
        -Wno-missing-local-signatures -Wno-missing-safe-haskell-mode
        -Wno-monomorphism-restriction -Wno-prepositive-qualified-module
        -Wno-safe -Wno-unsafe -threaded -rtsopts -with-rtsopts=-N

    build-depends:
        base >=4.16.4.0 && <5,
        hspec >=2.9.7,
        optparse-applicative >=0.17.1.0,
        ronn-optparse-applicative,
        ronn-test

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures
