cabal-version: 3.8

name: ersatz-viz
version: 0
synopsis: draw circuit (DAG) for Ersatz.Bit
description:
  draw circuit (DAG) for Ersatz.Bit
  .
  example usage: see test/Works.hs
license: GPL-3.0-only
author: Johannes Waldmann
homepage: https://git.imn.htwk-leipzig.de/waldmann/ersatz-viz
  
library
  hs-source-dirs: src
  exposed-modules: Ersatz.Bit.Display
  other-modules: Ersatz.Internal.StableName
  build-depends: base < 4.24 , text, process-extras, unordered-containers,
    mtl, lens, ersatz
  default-language: GHC2021
  
test-suite works
  hs-source-dirs: test
  main-is: Works.hs
  type: exitcode-stdio-1.0
  build-depends: base, text, ersatz, ersatz-viz
  default-language: GHC2021
