cabal-version: 2.2

name: hslogger-colorfmt
version: 1.0.0
synopsis: Custom hslogger formatters implementing color output
description:
  This library adds some custom log formatters implementing color output. We
  have also added code to pad the Priority strings in log messages if desired.
author: Dino Morelli
maintainer: dino@ui3.info
copyright: 2026 Dino Morelli
category: Interfaces, Logging
license: ISC
license-file: LICENSE
build-type: Simple
extra-source-files:
  .gitignore
  README.md
  stack.yaml
extra-doc-files:
  CHANGELOG.md

source-repository head
  type: git
  location: https://codeberg.org/dinofp/hslogger-colorfmt

common lang
  default-language: Haskell2010
  ghc-options:
    -fwarn-tabs
    -Wall
    -Wcompat
    -Wderiving-typeable
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints
  build-depends:
      base >=3 && <5
    , hslogger >= 1.3.1.2 && < 2

library
  import: lang
  exposed-modules:
    System.Log.Color
    System.Log.Color.Formatter
    System.Log.Util
  hs-source-dirs:
    src/lib
  build-depends:
      ansi-terminal >= 1.1 && < 2
    , time >= 1.12.2 && < 2

executable hslogger-colorfmt-example
  import: lang
  main-is: Main.hs
  hs-source-dirs:
    src/examples
  build-depends:
      hslogger-colorfmt
