cabal-version:       >= 1.10
name:                ini
version:             0.5.1
synopsis:            Configuration files in the INI format.
description:         Quick and easy configuration files in the INI format.
license:             BSD3
license-file:        LICENSE
author:              Chris Done
maintainer:          Jan Hrček
homepage:            https://github.com/jhrcek/ini
bug-reports:         https://github.com/jhrcek/ini/issues
copyright:           2013 Chris Done
category:            Data, Configuration
build-type:          Simple

tested-with:
  GHC == 9.12.2
   || == 9.10.3
   || == 9.8.4
   || == 9.6.7
   || == 9.4.8
   || == 9.2.8
   || == 9.0.2
   || == 8.10.7
   || == 8.8.4
   || == 8.6.5
   || == 8.4.4
   || == 8.2.2
   || == 8.0.2

extra-source-files:
  CHANGELOG.md
  README.md

library
  hs-source-dirs:    src/
  exposed-modules:   Data.Ini
  build-depends:     base >= 4 && <5,
                     attoparsec,
                     text,
                     unordered-containers
  if !impl(ghc >= 8)
    build-depends: semigroups >= 0.10 && < 0.21

  default-language:   Haskell98
  default-extensions: OverloadedStrings
                      TypeOperators

  ghc-options:        -Wall
  if impl(ghc >= 8)
    ghc-options:      -Wcompat

test-suite ini-test
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  ghc-options:     -Wall
  build-depends:     base >= 4 && <5
                   , QuickCheck
                   , ini
                   , hspec
                   , text
                   , unordered-containers

  default-language:  Haskell98

source-repository head
  type:     git
  location: https://github.com/jhrcek/ini.git
