-- documentation, see http://haskell.org/cabal/users-guide/

name:                  casa-abbreviations-and-acronyms
version:               0.0.12
synopsis:              CASA Abbreviations and Acronyms
description:
  CASA Abbreviations and Acronyms
  .
  <<https://logo.systemf.com.au/systemf-450x450.jpg>>
  .
  <<https://i.imgur.com/J5bfm3Z.gif>>
  .
  https://www.casa.gov.au/resources-and-education/glossary
license:               BSD3
license-file:          LICENCE
author:                Queensland Functional Programming Lab <oᴉ˙ldɟb@llǝʞsɐɥ>
maintainer:            Tony Morris <ʇǝu˙sıɹɹoɯʇ@ןןǝʞsɐɥ>
copyright:             Copyright (C) 2018-2019 Commonwealth Scientific and Industrial Research Organisation (CSIRO)
                       Copyright (C) 2020-2025 Tony Morris
category:              Aviation
build-type:            Simple
extra-source-files:    changelog.md
cabal-version:         >=1.10
homepage:              https://gitlab.com/system-f/code/casa-abbreviations-and-acronyms
bug-reports:           https://gitlab.com/system-f/code/casa-abbreviations-and-acronyms/issues
tested-with:           GHC == 7.10.3, GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.1, GHC == 9.4.8, GHC == 9.6.7

source-repository      head
  type:                git
  location:            git@gitlab.com:system-f/code/casa-abbreviations-and-acronyms.git

library
  exposed-modules:       Data.Aviation.Casa.AbbreviationsAndAcronyms.Acronym
                       , Data.Aviation.Casa.AbbreviationsAndAcronyms.Render
                       , Data.Aviation.Casa.AbbreviationsAndAcronyms.Render.Config
                       , Data.Aviation.Casa.AbbreviationsAndAcronyms.Render.Colours
                       , Data.Aviation.Casa.AbbreviationsAndAcronyms.Render.Score
                       , Data.Aviation.Casa.AbbreviationsAndAcronyms.Render.Spacing
                       , Data.Aviation.Casa.AbbreviationsAndAcronyms.Search

  build-depends:         base              >= 4.8     && < 6
                       , lens              >= 4.15    && < 6
                       , containers        >= 0.5     && < 1
                       , fuzzy             >= 0.1.0.0 && < 1
                       , monoid-subclasses >= 1.1     && < 2
                       , bytestring        >= 0.10    && < 1
                       , semialign         >= 1       && < 2
                       , these             >= 1.1     && < 2
                       , profunctors       >= 5.0     && < 6.0

  hs-source-dirs:      src/library

  default-language:    Haskell2010

  ghc-options:         -Wall

executable pre-process-casa-abbreviations-and-acronyms
  if impl(ghcjs)
    buildable: False
  else
    buildable: True

    build-depends:         base              >= 4.8     && < 6
                         , lens              >= 4.15    && < 6
                         , containers        >= 0.5     && < 1
                         , fuzzy             >= 0.1.0.0 && < 1
                         , monoid-subclasses >= 1.1     && < 2
                         , wreq              >= 0.5     && < 0.6
                         , bytestring        >= 0.10    && < 1

  main-is:             Main.hs

  hs-source-dirs:      src/pre-process

  default-language:    Haskell2010

  ghc-options:         -Wall

executable casa-abbreviations-and-acronyms
  if impl(ghcjs)
    buildable: False
  else
    buildable: True

    build-depends:        base                            >= 4.8     && < 6
                        , lens                            >= 4.15    && < 6
                        , fuzzy                           >= 0.1.0.0 && < 1
                        , optparse-applicative            >= 0.13.2  && < 1
                        , casa-abbreviations-and-acronyms

  main-is:             Main.hs

  hs-source-dirs:      src/executable

  default-language:    Haskell2010

  ghc-options:         -Wall
