cabal-version:   2.4
name:            mmark-ext
version:         0.3.0.0
license:         BSD-3-Clause
license-file:    LICENSE.md
maintainer:      Mark Karpov <markkarpov92@gmail.com>
author:          Mark Karpov <markkarpov92@gmail.com>
tested-with:     ghc ==9.10.3 ghc ==9.12.4 ghc ==9.14.1
homepage:        https://github.com/mmark-md/mmark-ext
bug-reports:     https://github.com/mmark-md/mmark-ext/issues
synopsis:        Commonly useful extensions for the MMark markdown processor
description:
    Commonly useful extensions for the MMark markdown processor. Click on
    "Text.MMark.Extension.Common" to get started.

category:        Text
build-type:      Simple
data-files:
    data/*.md
    data/*.html

extra-doc-files:
    CHANGELOG.md
    README.md

source-repository head
    type:     git
    location: https://github.com/mmark-md/mmark-ext.git

flag dev
    description: Turn on development settings.
    default:     False
    manual:      True

library
    exposed-modules:
        Text.MMark.Extension.Common
        Text.MMark.Extension.Emoji
        Text.MMark.Extension.Heading
        Text.MMark.Extension.Icons
        Text.MMark.Extension.Image
        Text.MMark.Extension.LineHighlight
        Text.MMark.Extension.Link
        Text.MMark.Extension.Mermaid
        Text.MMark.Extension.Metadata
        Text.MMark.Extension.Permalinks
        Text.MMark.Extension.Comment
        Text.MMark.Extension.Footnotes
        Text.MMark.Extension.GhcSyntaxHighlighter
        Text.MMark.Extension.Kbd
        Text.MMark.Extension.MathJax
        Text.MMark.Extension.PunctuationPrettifier
        Text.MMark.Extension.Skylighting
        Text.MMark.Extension.TableOfContents

    other-modules:    Text.MMark.Extension.Internal
    default-language: GHC2021
    build-depends:
        base >=4.16 && <5,
        bytestring >=0.10 && <0.13,
        containers >=0.5 && <0.9,
        directory >=1.2 && <1.4,
        filepath >=1.4 && <1.6,
        foldl >=1.2 && <1.5,
        ghc-syntax-highlighter >=0.0.1 && <0.1,
        lucid >=2.9.13 && <3,
        microlens >=0.4 && <0.6,
        mmark >=0.1 && <0.2,
        modern-uri >=0.3.4.4 && <0.4,
        skylighting >=0.7.6 && <0.15,
        text >=0.2 && <2.2

    if flag(dev)
        ghc-options:
            -Wall -Werror -Wredundant-constraints -Wpartial-fields
            -Wunused-packages -haddock -Winvalid-haddock

    else
        ghc-options: -O2 -Wall

test-suite tests
    type:               exitcode-stdio-1.0
    main-is:            Spec.hs
    build-tool-depends: hspec-discover:hspec-discover >=2.0 && <3.0
    hs-source-dirs:     tests
    other-modules:
        Text.MMark.Extension.CommentSpec
        Text.MMark.Extension.EmojiSpec
        Text.MMark.Extension.HeadingSpec
        Text.MMark.Extension.IconsSpec
        Text.MMark.Extension.ImageSpec
        Text.MMark.Extension.LineHighlightSpec
        Text.MMark.Extension.LinkSpec
        Text.MMark.Extension.MermaidSpec
        Text.MMark.Extension.MetadataSpec
        Text.MMark.Extension.PermalinksSpec
        Text.MMark.Extension.FootnotesSpec
        Text.MMark.Extension.GhcSyntaxHighlighterSpec
        Text.MMark.Extension.KbdSpec
        Text.MMark.Extension.MathJaxSpec
        Text.MMark.Extension.PunctuationPrettifierSpec
        Text.MMark.Extension.SkylightingSpec
        Text.MMark.Extension.TableOfContentsSpec
        Text.MMark.Extension.TestUtils

    default-language:   GHC2021
    build-depends:
        base >=4.16 && <5,
        bytestring >=0.10 && <0.13,
        containers >=0.5 && <0.9,
        directory >=1.2 && <1.4,
        filepath >=1.4 && <1.6,
        hspec >=2 && <3,
        lucid >=2.9.13 && <3,
        megaparsec >=8 && <10,
        mmark >=0.1 && <0.2,
        mmark-ext,
        modern-uri >=0.3.4.4 && <0.4,
        text >=0.2 && <2.2

    if flag(dev)
        ghc-options:
            -Wall -Werror -Wredundant-constraints -Wpartial-fields
            -Wunused-packages -haddock -Winvalid-haddock

    else
        ghc-options: -O2 -Wall
