cabal-version: 3.0
name: warp-effectful
version: 1.1.0
synopsis: Effectful bindings for the warp library
description:
  Adaptation of the @<https://hackage.haskell.org/package/warp warp>@ library for the @<https://hackage.haskell.org/package/effectful effectful>@ ecosystem.

homepage: https://digital-autonomy.institute
license: EUPL-1.2
license-file: LICENCE
author: IDA
maintainer: IDA
bug-reports: https://issues.digital-autonomy.institute
category: Network
build-type: Simple
extra-source-files:
  CHANGELOG.md

common common
  default-language: Haskell2010
  ghc-options:
    -Weverything
    -Wno-unsafe
    -Wno-missing-safe-haskell-mode
    -Wno-missing-export-lists
    -Wno-missing-import-lists
    -Wno-missing-kind-signatures
    -Wno-all-missed-specialisations
    -Wno-missing-role-annotations

  default-extensions:
    BlockArguments
    DataKinds
    ExplicitNamespaces
    FlexibleContexts
    ImportQualifiedPost
    ImpredicativeTypes
    LambdaCase
    NoImplicitPrelude
    OverloadedStrings
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators
    ViewPatterns

  build-depends:
    base >=4.10 && <5,
    bytestring >=0.12 && <0.13,
    effectful >=2.6 && <2.7,
    http-types >=0.12 && <0.13,
    wai-effectful >=1.0 && <1.1,

library
  import: common
  hs-source-dirs: src
  build-depends:
    crypton-x509 >=1.7 && <1.10,
    network >=3.2 && <3.3,
    time-manager >=0.2 && <0.4,
    warp >=3.4.13 && <3.5,

  exposed-modules:
    Effectful.Wai.Handler.Warp

test-suite test
  import: common
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  build-depends:
    hspec-effectful >=1.0 && <1.2,
    http-client-effectful >=1.0 && <1.1,
    warp-effectful,
