name:               hsmrc
version:            0.1.3
cabal-version:      >=1.10
build-type:         Simple
stability:          experimental
category:           Data
license:            BSD3
synopsis:           Library for Marc21 bibliographic records
copyright:          2025
homepage:           https://codeberg.org/brunberg/hsmrc/
extra-source-files: Changelog.md

library
  hs-source-dirs:   src
  build-depends:
                    base >= 4.13.0 && < 4.17,
                    text >= 1.2.4 && < 2.2,
                    bytestring >= 0.10.10 && < 0.13
  ghc-options:      -Wall
  other-modules:
                    Data.Marc21.Constants,
                    Data.Marc21.Convenience,
                    Data.Marc21.MnemText21
  exposed-modules:
                    Data.Marc21,
                    Data.Marc21.Mnem
  default-language: Haskell2010
