cabal-version:      2.0
name:               network-run
version:            0.6.0
license:            BSD3
license-file:       LICENSE
maintainer:         kazu@iij.ad.jp
author:             Kazu Yamamoto
synopsis:           Simple network runner library
description:        Simple functions to run network clients and servers.
category:           Network
build-type:         Simple
extra-doc-files:    CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/kazu-yamamoto/network-run

flag examples
    description: Build the example programs
    default:     False
    manual:      True

library
    exposed-modules:
        Network.Run.TCP
        Network.Run.TCP.Timeout
        Network.Run.UDP

    other-modules:    Network.Run.Core
    default-language: Haskell2010
    build-depends:
        base >=4 && <5,
        bytestring >=0.10 && <0.13,
        network >=3.2.4 && <3.3,
        time-manager >=0.2 && <0.4

executable tcp-client
    main-is:          tcpClient.hs
    hs-source-dirs:   examples
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4 && <5,
        bytestring >=0.10 && <0.13,
        network >=3.2.4 && <3.3,
        network-run

    if !flag(examples)
        buildable: False

executable tcp-server
    main-is:          tcpServer.hs
    hs-source-dirs:   examples
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4 && <5,
        bytestring >=0.10 && <0.13,
        network >=3.2.4 && <3.3,
        network-run

    if !flag(examples)
        buildable: False

executable udp-client
    main-is:          udpClient.hs
    hs-source-dirs:   examples
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4 && <5,
        bytestring >=0.10 && <0.13,
        network >=3.2.4 && <3.3,
        network-run

    if !flag(examples)
        buildable: False

executable udp-server
    main-is:          udpServer.hs
    hs-source-dirs:   examples
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4 && <5,
        bytestring >=0.10 && <0.13,
        network >=3.2.4 && <3.3,
        network-run

    if !flag(examples)
        buildable: False

test-suite spec
    type:             exitcode-stdio-1.0
    main-is:          Spec.hs
    build-tool-depends: hspec-discover:hspec-discover
    hs-source-dirs:   test .
    other-modules:
        CoreSpec
        Helper
        TCPSpec
        TimeoutSpec
        UDPSpec
        Network.Run.Core
        Network.Run.TCP
        Network.Run.TCP.Timeout
        Network.Run.UDP

    default-language: Haskell2010
    ghc-options:      -Wall -threaded -rtsopts -with-rtsopts=-N
    build-depends:
        base >=4 && <5,
        bytestring,
        directory,
        hspec,
        network >=3.2.4,
        time-manager >=0.2 && <0.4,
        network-run
