Name:                sum-pyramid
Version:             0.0.1
Synopsis:            Create Sum Pyramid (Additionstreppe) exercises
Description:
  Create Sum Pyramid (Additionstreppe) exercises.
  You specify the size of the pyramid and the number range of the base line
  and the program emits LaTeX code for puzzles.
  .
  > sum-pyramid create --size 5
  .
  > nix-shell --run "make puzzle.pdf"
  .
  You may also use multiplications (@--multiplication@),
  or both addition and multiplication (@--mixed@).
  In case of additions only,
  you may allow puzzles that are uniquely solvable,
  but possibly not step-by-step (@--allow-gaps@).
  You can also control via LaTeX macros
  whether and how unknown cells are displayed.
  .
  Example output: http://code.henning-thielemann.de/sum-pyramid/puzzle.pdf
Homepage:            https://hub.darcs.net/thielema/sum-pyramid
License:             BSD3
License-File:        LICENSE
Author:              Henning Thielemann
Maintainer:          haskell@henning-thielemann.de
Category:            Math
Build-Type:          Simple
Cabal-Version:       >=1.10

Extra-Source-Files:
  Makefile
  puzzle.tex

Source-Repository this
  Tag:         0.0.1
  Type:        darcs
  Location:    https://hub.darcs.net/thielema/sum-pyramid

Source-Repository head
  Type:        darcs
  Location:    https://hub.darcs.net/thielema/sum-pyramid

Executable sum-pyramid
  Build-Depends:
    lapack >=0.5.2 && <0.6,
    unique-logic-tf >=0.5.1 && <0.6,
    combinatorial >=0.1.1 && <0.2,
    random >=1.2.1 && <1.4,
    comfort-array >=0.5.5 && <0.6,
    containers >=0.5.4 && <0.9,
    transformers >=0.3 && <0.7,
    shell-utility >=0.1 && <0.2,
    optparse-applicative >=0.11 && <0.19,
    utility-ht >=0.0.11 && <0.1,
    base >=4.5 && <5
  Default-Language:    Haskell2010
  GHC-Options:         -Wall
  Hs-Source-Dirs:      src
  Main-is:             Main.hs
  Other-Modules:
    UniqueLogic
    LinearAlgebra
    Common

Test-Suite sum-pyramid-test
  Type: exitcode-stdio-1.0
  Build-Depends:
    doctest-exitcode-stdio >=0.0 && <0.1,
    doctest-lib >=0.1 && <0.2,
    lapack,
    unique-logic-tf,
    combinatorial,
    comfort-array,
    containers,
    transformers,
    utility-ht,
    base >=4.5 && <5
  Default-Language:    Haskell2010
  GHC-Options:         -Wall
  Hs-Source-Dirs:      src, test
  Main-is:             TestMain.hs
  Other-Modules:
    Test.UniqueLogic
    Test.LinearAlgebra
    UniqueLogic
    LinearAlgebra
    Common
