cabal-version:       2.4
name:                ghc-debug-brick
version:             0.8.0.0
synopsis:            A simple TUI using ghc-debug
description:         A simple TUI using ghc-debug
bug-reports:         https://gitlab.haskell.org/ghc/ghc-debug/-/issues
license:             BSD-3-Clause
license-file:        LICENSE
author:              David Eichmann, Matthew Pickering, Hannes Siebenhandl
maintainer:          hannes@well-typed.com
build-type:          Simple
extra-doc-files:     CHANGELOG.md

common shared
  ghc-options: -Wall -Wincomplete-record-selectors
  default-language:    Haskell2010

library
  import:            shared
  hs-source-dirs:    src
  exposed-modules:
    Brick.Widgets.IOTree
    Brick.Widgets.ListPicker
    GHC.Debug.Brick.Model
    GHC.Debug.Brick.Namespace
    GHC.Debug.Brick.ClosureDetails
    GHC.Debug.Brick.Common
    GHC.Debug.Brick.IOTree
    GHC.Debug.Brick.Lib
    GHC.Debug.Brick.Render
    GHC.Debug.Brick.Render.Closure
    GHC.Debug.Brick.Render.Command
    GHC.Debug.Brick.Render.Filter
    GHC.Debug.Brick.Render.Footer
    GHC.Debug.Brick.Render.Header
    GHC.Debug.Brick.Render.Histogram
    GHC.Debug.Brick.Render.HistoryPicker
    GHC.Debug.Brick.Render.Key
    GHC.Debug.Brick.Render.Utils
    GHC.Debug.Brick.Update
    GHC.Debug.Brick.UI
    GHC.Debug.Brick.UI.Async
    GHC.Debug.Brick.UI.Filter
    GHC.Debug.Brick.Action.ArrWords
    GHC.Debug.Brick.Action.Async
    GHC.Debug.Brick.Action.Profile
    GHC.Debug.Brick.Action.Retainers
    GHC.Debug.Brick.Action.Strings
    GHC.Debug.Brick.Action.Thunk

  build-depends:
    async,
    base >=4.16 && <5,
    brick >= 1.3,
    bytestring,
    containers,
    directory,
    filepath,
    microlens-platform,
    safe-exceptions,
    text,
    vty-crossplatform,
    vty >= 6,
    time,
    deepseq,
    microlens,
    ghc-debug-client == 0.8.0.0,
    ghc-debug-common == 0.8.0.0,
    ghc-debug-convention == 0.8.0.0,
    unordered-containers,
    exceptions,
    contra-tracer,
    bytestring,
    byteunits,
    dependent-map >= 0.4.0 && < 0.5,
    some >= 1.0.6 && < 1.1,
    dependent-sum-template >= 0.2.0 && < 0.3,

executable ghc-debug-brick
  import:            shared
  hs-source-dirs:    app
  main-is:           Main.hs
  build-depends:
    base,
    ghc-debug-brick,
  ghc-options:       -threaded "-with-rtsopts=-N -qn1" -rtsopts
