cabal-version:      3.16
name:               pandoc-md-slides
version:            1.1.0.0
synopsis:           A pandoc filter to convert markdown notes to markdown slides
description:        A pandoc filter to convert markdown notes to markdown slides. Splits long slides and resolves image target paths
license:            MIT
author:             Rubelito Abella
maintainer:         bbadoodles@gmail.com
category:           Text
build-type:         Simple
extra-doc-files:
    README.md
    CHANGELOG.md

source-repository head
    type: git
    location: https://github.com/HowDoIGitHelp/autoslides-pandocfilter.git

common warnings
    ghc-options: -Wall

executable md-slides
    import:           warnings
    main-is:          Pandoc-filter.hs
    build-depends:    base ^>=4.20.2.0,
                      pandoc-types ^>= 1.23.1,
                      text ^>=2.1.4,
                      pcre2 ^>=2.3.1,
                      regex-tdfa ^>=1.3.2,
                      path ^>=0.9.6,
                      path-io ^>=1.8.2,
                      filepath ^>=1.5.5,
                      optparse-applicative ^>= 0.19.0,
                      aeson ^>= 2.3.2,
                      yaml ^>= 0.11.11
    hs-source-dirs:   app
    default-language: Haskell2010

executable remarkjs
    import:           warnings
    main-is:          Remarkjs-pandoc-filter.hs
    build-depends:    base ^>=4.20.2.0,
                      pandoc-types ^>= 1.23.1,
                      text ^>=2.1.4,
    hs-source-dirs:   app
    default-language: Haskell2010
