cabal-version:      3.4
name:               coerce-with-substitution
version:            0.0.0.0
synopsis:           Coercions with improved type inference
description:
    This package defines aliases of 'Data.Coerce.coerce' and
    'Unsafe.Coerce.unsafeCoerce' that accept a type argument containing type
    substitutions, creating a relationship between the argument and result
    types of the coercion that GHC can use when inferring one type from the
    other.

    See "Data.CoerceSubst" for a full introduction to this package.

    Requires GHC 9.6 or later, due to use of the
    [`TypeData`](https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/type_data.html)
    extension.
license:            BSD-3-Clause
license-file:       LICENSE
author:             Ryan Hendrickson
maintainer:         contact-project+rhendric-haskell-coerce-with-substitution-71023049-issue-@incoming.gitlab.com
homepage:           https://gitlab.com/rhendric/haskell-coerce-with-substitution
bug-reports:        https://gitlab.com/rhendric/haskell-coerce-with-substitution/-/issues
copyright:          © 2025 Ryan Hendrickson
category:           Development
build-type:         Simple
extra-doc-files:    CHANGELOG.md
tested-with:        GHC == { 9.12.2, 9.10.2, 9.8.4, 9.6.7, 9.6.1 }

source-repository head
    type: git
    location: https://gitlab.com/rhendric/haskell-coerce-with-substitution.git

library
    hs-source-dirs:   src
    exposed-modules:  Data.CoerceSubst
    build-depends:    base >=4.7 && <5
    ghc-options:
        -fprint-unicode-syntax
        -haddock
        -Wall
        -Wcompat
        -Winvalid-haddock
        -Wmissing-export-lists
        -Woperator-whitespace
        -Wunused-packages
        -Wunused-type-patterns
    if impl(ghc >= 9.10.1)
        ghc-options:
            -Wmissing-poly-kind-signatures
    default-language: GHC2021
    default-extensions:
        AllowAmbiguousTypes,
        DataKinds,
        FunctionalDependencies,
      NoImplicitPrelude,
      NoStarIsType,
        TypeData,
        TypeFamilies,
        UndecidableInstances,
        UnicodeSyntax,
