cabal-version: 3.8
author: Liisi Kerik
category: Composition, Lilypond, MIDI, Music
description:
  This library provides data structures and a custom file format for describing music and generates Lilypond and MIDI files. In
  addition it contains a module with some music-theoretical functions. The library is focused on the very basics of standard
  Western musical notation and does not support dynamic indications, articulation marks, double accidentals, tempo changes,
  polyrhythms, time signature changes and microtonality.
license: BSD-3-Clause
license-file: LICENSE
maintainer: liisikerik@hotmail.com
name: Aoide
synopsis: A simple music library that can generate Lilypond and MIDI files.
version: 1.0.0.0
common Common
  build-depends:
    Kawaii-Parser, barbies, base < 4.22, bytestring, containers, directory, filepath, generic-lens, lens, mtl, process, transformers
  default-extensions:
    DeriveGeneric,
    DuplicateRecordFields,
    FlexibleContexts,
    FlexibleInstances,
    GADTs,
    NamedFieldPuns,
    NegativeLiterals,
    NoFieldSelectors,
    OrPatterns,
    OverloadedLabels,
    QuantifiedConstraints,
    RankNTypes,
    ScopedTypeVariables,
    StandaloneDeriving,
    TypeData,
    UndecidableInstances
  default-language: Haskell2010
  ghc-options: -Wall -Wno-x-partial
library
  import: Common
  exposed-modules:
    Composition.Errors,
    Composition.Keyboard,
    Composition.Lilypond,
    Composition.MIDI,
    Composition.Notes,
    Composition.Parser,
    Composition.Score,
    Composition.Theory,
    Composition.Time,
    Composition.Write
executable Aoide
  import: Common
  main-is: Main.hs
  other-modules:
    Composition.Errors,
    Composition.Keyboard,
    Composition.Lilypond,
    Composition.MIDI,
    Composition.Notes,
    Composition.Parser,
    Composition.Score,
    Composition.Theory,
    Composition.Time,
    Composition.Write
source-repository head
  location: https://github.com/liisikerik/aoide.git
  type: git