cabal-version: 3.0
name: circuits
version: 0.2.0.0
license: BSD-3-Clause
license-file: LICENSE
copyright: Tony Day (c) 2025-2026
category: control
author: Tony Day
maintainer: tonyday567@gmail.com
homepage: https://github.com/tonyday567/circuits#readme
bug-reports: https://github.com/tonyday567/circuits/issues
synopsis: first-class circuits
description:
  circuits provides a suite of tools that make coding with circuits first-class.

build-type: Simple
tested-with:
  ghc ==9.10.1
  ghc ==9.12.2
  ghc ==9.14.1

extra-doc-files:
  ChangeLog.md
  LICENSE
  other/*.html
  readme.md

source-repository head
  type: git
  location: https://github.com/tonyday567/circuits

common ghc-options-stanza
  ghc-options:
    -Wall
    -Wno-unused-imports
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints

library
  import: ghc-options-stanza
  default-language: GHC2024
  hs-source-dirs: src
  exposed-modules:
    Circuit
    Circuit.Algebra
    Circuit.Category
    Circuit.Channel
    Circuit.Dagger
    Circuit.Discrete
    Circuit.Ends
    Circuit.Free
    Circuit.Hyper
    Circuit.Layer
    Circuit.Loop
    Circuit.Net
    Circuit.Sym
    Circuit.Tensor

  build-depends:
    base >=4.18 && <5,
    profunctors >=5.0 && <6,
    stm >=2.5 && <3,
