cabal-version:      1.18
name:               freckle-stats
version:            0.0.0.1
license:            MIT
license-file:       LICENSE
maintainer:         Freckle Education
homepage:           https://github.com/freckle/freckle-stats#readme
bug-reports:        https://github.com/freckle/freckle-stats/issues
synopsis:           An intentionally-leaky StatsD interface to Datadog
description:        Please see README.md
category:           Prelude
build-type:         Simple
extra-source-files: package.yaml
extra-doc-files:
    README.md
    CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/freckle/freckle-stats

library
    exposed-modules:
        Freckle.App.Stats
        Freckle.App.Stats.Rts

    hs-source-dirs:     library
    other-modules:      Paths_freckle_stats
    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingVia DerivingStrategies GADTs
        LambdaCase NoImplicitPrelude NoMonomorphismRestriction
        OverloadedStrings RecordWildCards TypeFamilies

    ghc-options:
        -fignore-optim-changes -fwrite-ide-info -Weverything
        -Wno-all-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-kind-signatures
        -Wno-missing-local-signatures -Wno-missing-safe-haskell-mode
        -Wno-monomorphism-restriction -Wno-prepositive-qualified-module
        -Wno-safe -Wno-unsafe

    build-depends:
        Blammo >=2.1.0.0,
        aeson >=2.0.3.0,
        base >=4.16.4.0 && <5,
        datadog >=0.3.0.0,
        ekg-core >=0.1.1.7,
        freckle-ecs >=0.0.0.0,
        freckle-env >=0.0.1.2,
        freckle-prelude >=0.0.4.0,
        immortal >=0.3,
        lens >=5.1.1,
        mtl >=2.2.2,
        time >=1.11.1.1,
        unliftio >=0.2.25.0,
        unordered-containers >=0.2.19.1

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures
