Cabal-Version:       2.2
Name:                crypton-pubkey-types
Version:             0.5.0
Description:         Generic cryptography public keys algorithm types
License:             BSD-3-Clause
License-file:        LICENSE
Copyright:           Vincent Hanquez <vincent@snarc.org>
Author:              Vincent Hanquez <vincent@snarc.org>
Maintainer:          Pranay Sashank <pranaysashank@gmail.com>
Synopsis:            Public keys algorithm types
Category:            Cryptography
Build-Type:          Simple
Tested-With:         GHC ==9.12.4 || ==9.14.1
Homepage:            http://github.com/kronor-io/crypton-pubkey-types
Extra-Doc-Files:
  CHANGELOG.md
  README.md

Library
  Exposed-modules:   Crypto.Types.PubKey.RSA
                     Crypto.Types.PubKey.DSA
                     Crypto.Types.PubKey.DH
                     Crypto.Types.PubKey.ECC
                     Crypto.Types.PubKey.ECDSA
  Build-depends:     base >= 4 && < 5
                   , crypton-asn1-types >= 0.4 && < 0.5
                   , crypton-asn1-encoding >= 0.10 && < 0.11
  Default-Language:  Haskell98

source-repository head
  type:     git
  location: https://github.com/kronor-io/crypton-pubkey-types
