cabal-version:      3.0
name:               weave-core
version:            0.1.0.0
synopsis: Core definitions for weave
description:
  The four variants of @Weave@, a control structure for defining
  /breadth-first unfolds/ compositionally.
  .
  See <https://hackage.haskell.org/package/weave weave> for more information.
license:            BSD-3-Clause
license-file:       LICENSE
author:             Li-yao Xia
maintainer:         lysxia@gmail.com
homepage:           https://gitlab.com/lysxia/weave
category:           Control
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Weave.Endless
        Weave.Lazy
        Weave.Oblivious
        Weave.Strict
    build-depends:
        some < 1.1,
        base >= 4 && < 5
    hs-source-dirs:   src
    default-language: Haskell2010
