Name:           numeric-quest
Version:        0.2.1
License:        GPL
License-File:   LICENSE
Author:         Jan Skibinski
Maintainer:     Henning Thielemann <numeric-quest@henning-thielemann.de>
Homepage:       http://www.haskell.org/haskellwiki/Numeric_Quest
Category:       Math
Synopsis:       Math and quantum mechanics
Description:
  List based linear algebra,
  similtaneous linear equations,
  eigenvalues and eigenvectors,
  roots of polynomials,
  transcendent functions with arbitrary precision
  implemented by continued fractions,
  quantum operations,
  tensors
Tested-With:    GHC==6.*, GHC==7.*, GHC==8.*, GHC==9.*
Cabal-Version:  >=1.10
Build-Type:     Simple

Data-Files:
  Makefile
  README

Source-Repository this
  Tag:         0.2.1
  Type:        darcs
  Location:    http://code.haskell.org/~thielema/numeric-quest/

Source-Repository head
  Type:        darcs
  Location:    http://code.haskell.org/~thielema/numeric-quest/

Library
  Build-Depends:
    non-empty >=0.3.2 && <0.4,
    utility-ht >=0.0.2 && <0.1,
    prelude-compat >=0.0.0.1 && <0.1,
    array >=0.1 && <0.6,
    base >=3 && <5

  Default-Language: Haskell98
  GHC-Options:    -Wall
  Hs-source-dirs: .
  Exposed-modules:
     Eigensystem
     EigensystemNum
     Fraction
     LinearAlgorithms
     Orthogonals
     QuantumVector
     Roots
     RowEchelon
     Tensor

Test-Suite numeric-quest-test
  Type: exitcode-stdio-1.0
  Default-Language: Haskell98
  GHC-Options:    -Wall
  Hs-Source-Dirs: test
  Other-Modules:  Test.RowEchelon
  Main-Is: Test/Main.hs

  Build-Depends:
    numeric-quest,
    doctest-exitcode-stdio >=0.0 && <0.1,
    doctest-lib >=0.1 && <0.2,
    QuickCheck >=2 && <3,
    non-empty,
    utility-ht,
    base
