cabal-version:      3.0
name:               multisets
version:            0.1.0.0
synopsis: Multisets with arbitrary-precision Natural multiplicities
description:
  Finite multisets with arbitrary-precision 'Natural' multiplicities.

  A 'MultiSet' is like a 'Data.Set.Set', except that values may occur more than
  once. The number of occurrences of a value is its /multiplicity/.

  Unlike "Data.MultiSet", this package represents multiplicities using
  'Natural' rather than 'Int', allowing them to grow beyond the range of 'Int'
  while reflecting that multiplicities cannot be negative.

  The API is broadly similar to "Data.MultiSet", and many common uses are
  source-compatible after changing the module import.
homepage:           https://github.com/rafl/multisets
bug-reports:        https://github.com/rafl/multisets/issues
license:            MIT
license-file:       LICENSE
author:             Florian Ragwitz
maintainer:         florian.ragwitz@gmail.com
copyright:          (c) 2026 Florian Ragwitz
category:           Data
build-type:         Simple
extra-doc-files:    CHANGELOG.md

source-repository head
  type: git
  branch: main
  location: https://github.com/rafl/multisets

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  Data.MultiSet.Natural
    build-depends:    base >= 4.9 && < 4.24, containers >= 0.6.2.1 && < 0.9, deepseq >= 1.4 && < 1.6
    hs-source-dirs:   src
    default-language: Haskell2010

test-suite multisets-test
    import:           warnings
    default-language: Haskell2010
    other-modules: Test.Gen, Test.Valid, Test.ToFrom, Test.Queries, Test.Instances, Test.Effects, Test.Folds, Test.Transformations, Test.Updates, Test.Combining, Test.Extremes
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base, containers, multisets, deepseq,
        tasty >= 1.2.3 && < 1.6, tasty-quickcheck >= 0.10.1.1 && < 0.12, QuickCheck >= 2.13.2 && < 2.19
    ghc-options: -Wall -threaded -rtsopts
