cabal-version:       3.0
name:                sectile
version:             0.1.0.0
author:              Gautier DI FOLCO
maintainer:          foss@difolco.dev
category:            Terminal
build-type:          Simple
license:             ISC
license-file:        LICENSE
synopsis:            Composable status line builder
description:         Composable status line builder.
Homepage:            https://github.com/blackheaven/sectile
tested-with:         GHC==9.6.6, GHC==9.8.4, GHC==9.10.1, GHC==9.12.1

library
  default-language:   Haskell2010
  build-depends:
      base == 4.*
    , aeson == 2.*
    , bytestring == 0.12.*
    , ede >= 0.3.4.0 && < 0.4
    , lens == 5.*
    , lens-regex-pcre == 1.1.*
    , mtl >= 2.3.1 && < 2.4
    , optics == 0.4.*
    , optics-core == 0.4.*
    , pcre-light == 0.4.*
    , process == 1.6.*
    , directory == 1.3.*
    , text == 2.*
    , time >= 1.12 && < 2
    , unordered-containers >= 0.2.20.1 && < 0.3
  hs-source-dirs: src
  exposed-modules:
    Data.Sectile
    Data.Sectile.Display
    Data.Sectile.Runners
    Data.Sectile.Segments
    Data.Sectile.Style
    Data.Sectile.System.Linux
    Data.Sectile.System.Linux.Battery
    Data.Sectile.System.Linux.Cpu
    Data.Sectile.System.Linux.Disk
    Data.Sectile.System.Linux.Internal
    Data.Sectile.System.Linux.Load
    Data.Sectile.System.Linux.Memory
    Data.Sectile.System.Linux.Network
    Data.Sectile.System.Linux.Thermal
    Data.Sectile.System.Linux.Uptime
    Data.Sectile.System.Linux.Wifi
    Data.Sectile.Themes
    Data.Sectile.Tmux
    Data.Sectile.Types
  other-modules:
    Paths_sectile
  autogen-modules:
    Paths_sectile
  default-extensions:
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveGeneric
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    FlexibleContexts
    GADTs
    GeneralizedNewtypeDeriving
    KindSignatures
    LambdaCase
    OverloadedStrings
    OverloadedRecordDot
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators
  ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints

test-suite spec
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Spec.hs
  other-modules:
    Data.Sectile.DisplaySpec
    Data.Sectile.SegmentsSpec
    Data.Sectile.StyleSpec
    Data.Sectile.TmuxSpec
    Data.Sectile.System.LinuxSpec
    Data.Sectile.TypesSpec
    Paths_sectile
  autogen-modules:
    Paths_sectile
  default-extensions:
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveGeneric
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    FlexibleContexts
    GADTs
    GeneralizedNewtypeDeriving
    KindSignatures
    LambdaCase
    OverloadedStrings
    OverloadedRecordDot
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators
  ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints
  build-depends:
      base
    , bytestring
    , sectile
    , hedgehog
    , hspec
    , hspec-core
    , hspec-discover
    , hspec-hedgehog
    , mtl
    , aeson
    , unordered-containers
    , optics-core
    , text
    , time
    , pcre-light
  default-language: Haskell2010

executable sectile
  main-is: Main.hs
  hs-source-dirs: app
  other-modules:
    Convert
    DhallTypes
  default-extensions:
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveGeneric
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    FlexibleContexts
    GADTs
    GeneralizedNewtypeDeriving
    KindSignatures
    LambdaCase
    OverloadedStrings
    OverloadedRecordDot
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators
  ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints
  build-depends:
      base
    , sectile
    , bytestring
    , dhall == 1.*
    , either == 5.*
    , optparse-applicative
    , text
    , async
    , optics-core

  default-language: Haskell2010
