cabal-version:       3.0
name:                hopenpgp-tools
version:             0.25.10
synopsis:            hOpenPGP-based command-line tools
description:         command-line tools for performing some OpenPGP-related operations
homepage:            https://salsa.debian.org/clint/hOpenPGP-tools
license:             AGPL-3.0-or-later
license-file:        LICENSE
author:              Clint Adams
maintainer:          Clint Adams <clint@debian.org>
copyright:           2012-2026 Clint Adams
category:            Codec, Data
build-type:          Simple

flag use-memory
  description: Use the 'memory' package instead of 'ram'
  default: False

common deps
  autogen-modules:     Paths_hopenpgp_tools
  build-depends:       base                   >= 4.15       && < 5
               ,       aeson
               ,       binary                 >= 0.6.4
               ,       binary-conduit
               ,       bytestring
               ,       conduit                >= 1.3
               ,       errors
               ,       hOpenPGP               >= 3.6        && < 3.7
               ,       lens
               ,       optparse-applicative   >= 0.18.1
               ,       prettyprinter          >= 1.7
               ,       text
               ,       transformers           >= 0.4
               ,       yaml
  ghc-options:         -Wall
  other-modules:       HOpenPGP.Tools.Common.Common
               ,       Paths_hopenpgp_tools

executable hot
  import:              deps
  main-is:             hot.hs
  autogen-modules:     Paths_hopenpgp_tools
  other-modules:       HOpenPGP.Tools.Common.Armor
               ,       HOpenPGP.Tools.Common.Lexer
               ,       HOpenPGP.Tools.Common.Parser
  build-depends:       array
               ,       conduit-extra          >= 1.1
               ,       monad-loops
               ,       openpgp-asciiarmor     >= 1
  build-tool-depends:  alex:alex, happy:happy
  default-language: Haskell2010

executable hokey
  import:              deps
  main-is:             hokey.hs
  other-modules:       HOpenPGP.Tools.Common.HKP
               ,       HOpenPGP.Tools.Common.TKUtils
               ,       HOpenPGP.Tools.Common.WKD
               ,       HOpenPGP.Tools.Hokey.Options
               ,       HOpenPGP.Tools.Hokey.Canonicalize
               ,       HOpenPGP.Tools.Hokey.Fetch
               ,       HOpenPGP.Tools.Hokey.InjectSSHAgent
               ,       HOpenPGP.Tools.Hokey.Lint
               ,       HOpenPGP.Tools.Hokey.Lint.Types
               ,       HOpenPGP.Tools.Hokey.Lint.Policy
  build-depends:       base16-bytestring
               ,       conduit-extra          >= 1.1
               ,       containers
               ,       http-client            >= 0.4.30
               ,       http-client-tls
               ,       http-types
               ,       network
               ,       openpgp-asciiarmor     >= 1
               ,       prettyprinter-ansi-terminal >= 1.1.2
               ,       time
               ,       time-locale-compat
  if flag(use-memory)
    build-depends: crypton < 1.1, memory
  else
    build-depends: crypton >= 1.1, ram
  default-language: Haskell2010

executable hkt
  import:              deps
  main-is:             hkt.hs
  other-modules:       HOpenPGP.Tools.Common.Lexer
               ,       HOpenPGP.Tools.Common.Parser
               ,       HOpenPGP.Tools.Common.TKUtils
  build-depends:       array
               ,       containers
               ,       conduit-extra          >= 1.1
               ,       directory
               ,       fgl                    >= 5.5.4
               ,       graphviz
               ,       ixset-typed
               ,       monad-loops
               ,       resourcet
               ,       time
               ,       unordered-containers
  build-tool-depends:  alex:alex, happy:happy
  default-language: Haskell2010

executable hop
  import:              deps
  main-is:             hop.hs
  other-modules:       HOpenPGP.Tools.Common.Armor
               ,       HOpenPGP.Tools.Common.Lexer
               ,       HOpenPGP.Tools.Common.Parser
               ,       HOpenPGP.Tools.Common.TKUtils
  build-depends:       array
               ,       conduit-extra          >= 1.1
               ,       containers
               ,       crypton
               ,       directory
               ,       monad-loops
               ,       mtl
               ,       openpgp-asciiarmor     >= 1
               ,       resourcet
               ,       time
               ,       vector
  if flag(use-memory)
    build-depends: memory
  else
    build-depends: ram
  build-tool-depends:  alex:alex, happy:happy
  default-language: Haskell2010

source-repository head
  type:     git
  location: https://salsa.debian.org/clint/hopenpgp-tools.git

source-repository this
  type:     git
  location: https://salsa.debian.org/clint/hopenpgp-tools.git
  tag:      hopenpgp-tools/0.25.10
