cabal-version: 2.4
name: aeson-openapi-record-as-tuple
version: 1.0.0
build-type: Simple
license: MPL-2.0
author: Michael Ledger
maintainer: mike@quasimal.com
category: Default
synopsis: Encode and decode Haskell records as JSON tuples
description: This package lets you derive ToJSON/FromJSON instances for record data-types that are encoded into tuples
extra-doc-files:
  CHANGELOG.md

source-repository head
  type: git
  location: https://gitlab.com/_mike/aeson-record-as-tuple

library
  build-depends:
    aeson >=1.0.0.0 && <2.3,
    base >=4.16 && <5,
    openapi3 >=3 && <4,
    primitive >=0.7.3.0,
    vector >=0.12.2.0,

  hs-source-dirs: src
  exposed-modules:
    Data.Aeson.RecordAsTuple

  ghc-options:
    -Wall
    -Wno-partial-type-signatures

  default-language: GHC2021
  default-extensions:
    AllowAmbiguousTypes
    BangPatterns
    BlockArguments
    DataKinds
    DerivingStrategies
    DerivingVia
    ExplicitNamespaces
    FlexibleContexts
    FlexibleInstances
    ImportQualifiedPost
    OverloadedStrings
    PartialTypeSignatures
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators
    TypeSynonymInstances
    UndecidableInstances

test-suite aeson-record-as-tuple-tests
  type: exitcode-stdio-1.0
  main-is: spec.hs
  hs-source-dirs: tests
  build-depends:
    QuickCheck,
    aeson,
    aeson-openapi-record-as-tuple,
    base,
    bytestring,
    generic-random,
    hspec,

  ghc-options:
    -Wall
    -Wno-partial-type-signatures

  default-language: GHC2021
  default-extensions:
    AllowAmbiguousTypes
    BangPatterns
    BlockArguments
    DataKinds
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    ExplicitNamespaces
    FlexibleContexts
    FlexibleInstances
    ImportQualifiedPost
    OverloadedStrings
    PartialTypeSignatures
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators
    TypeSynonymInstances
    UndecidableInstances
