cabal-version:      3.0
name:               yamlstar
version:            0.1.17.0
synopsis:           Haskell bindings for YAMLStar
description:        Haskell bindings for YAMLStar, a pure YAML 1.2 loader.
license:            MIT
license-file:       License
author:             Ingy dot Net <ingy@ingy.net>
maintainer:         Ingy dot Net <ingy@ingy.net>
category:           Data, Text, YAML
homepage:           https://yamlstar.org
bug-reports:        https://github.com/yaml/yamlstar/issues
tested-with:        GHC==9.4.7, GHC==9.6.3, GHC==9.8.1, GHC==9.12.1

library
    exposed-modules:    YAMLStar
    other-modules:      YAMLStar.FFI
    build-depends:      base >=4.17.0.0 && <5,
                        bytestring ^>=0.11.0.0,
                        text >=2.0.0.0 && <3,
                        aeson >=2.0.0.0 && <3,
                        unix >=2.7.0.0 && <3
    hs-source-dirs:     lib
    default-language:   Haskell2010
    default-extensions: ForeignFunctionInterface
    ghc-options:        -Wall -Wcompat -Widentities
                        -Wincomplete-record-updates
                        -Wincomplete-uni-patterns
                        -Wmissing-home-modules
                        -Wpartial-fields
                        -Wredundant-constraints
    include-dirs:       /tmp/libyamlstar/lib
    extra-libraries:    yamlstar
    extra-lib-dirs:     /tmp/libyamlstar/lib

executable yamlstar-test
    main-is:            Main.hs
    build-depends:      base >=4.17.0.0 && <5,
                        yamlstar,
                        text >=2.0.0.0 && <3,
                        aeson >=2.0.0.0 && <3,
                        aeson-pretty >=0.8.0.0 && <1,
                        bytestring ^>=0.11.0.0
    hs-source-dirs:     test
    default-language:   Haskell2010
    ghc-options:        -Wall

test-suite yamlstar-tests
    type:               exitcode-stdio-1.0
    main-is:            Test.hs
    other-modules:      YAMLStar.Tests
    build-depends:      base >=4.17.0.0 && <5,
                        yamlstar,
                        hspec >=2.8.0.0 && <3,
                        aeson >=2.0.0.0 && <3,
                        text >=2.0.0.0 && <3,
                        unix >=2.7.0.0 && <3,
                        vector >=0.13.0.0 && <1
    hs-source-dirs:     test
    default-language:   Haskell2010
    ghc-options:        -Wall

