cabal-version: 1.12

-- SPDX-FileCopyrightText: Gregor Kleen
--
-- SPDX-License-Identifier: BSD-3-Clause

name:           cryptoids-types
version:        1.0.0.1
synopsis:       Shared types for encrypting internal object identifiers before exposure
category:       Web
author:         Gregor Kleen <aethoago@141.li>
maintainer:     Gregor Kleen <aethoago@141.li>
license:        BSD3
license-file:   LICENSE
build-type:     Simple
extra-source-files:
    changes.md

source-repository head
  type: git
  location: https://gitlab.com/gkleen/cryptoids.git
  subdir: cryptoids-types

library
  exposed-modules:
      Data.CryptoID
  other-modules:
      Paths_cryptoids_types
  hs-source-dirs:
      src
  default-extensions: KindSignatures DataKinds GeneralizedNewtypeDeriving DeriveGeneric DeriveDataTypeable
  ghc-options: -Wall -fno-warn-name-shadowing
  build-depends:
      aeson >=1.2.4.0 && <1.6
    , base >=4.9 && <5
    , binary >=0.8.3 && <0.11
    , deepseq >=1.4.3.0 && <1.5
    , hashable >=1.2.6.1 && <1.4
    , http-api-data >=0.3.7 && <0.5
    , path-pieces >=0.2.1 && <0.3
  default-language: Haskell2010
