cabal-version:        2.4
name:                 valuations
version:              0.0.5
synopsis:             Valuations
description:          Valuations: Valuation and Valuation Algebra
license:              BSD-3-Clause
license-file:         LICENCE
author:               Tony Morris <ʇǝu˙sıɹɹoɯʇ@ןןǝʞsɐɥ>
maintainer:           Tony Morris <ʇǝu˙sıɹɹoɯʇ@ןןǝʞsɐɥ>
copyright:            Copyright (C) 2026 Tony Morris
category:             Math
build-type:           Simple
extra-doc-files:      changelog.md
homepage:             https://gitlab.com/tonymorris/valuations
bug-reports:          https://gitlab.com/tonymorris/valuations/issues
tested-with:          GHC == 9.6.7

source-repository     head
  type:               git
  location:           git@gitlab.com:tonymorris/valuations.git

library
  exposed-modules:
                      Data.Valuation
                      Data.Valuation.CovariantFunctor
                      Data.Valuation.DomainLattice
                      Data.Valuation.PartialOrder
                      Data.Valuation.Poset
                      Data.Valuation.Presheaf
                      Data.Valuation.PresheafValuationAlgebra
                      Data.Valuation.ProjectValuation
                      Data.Valuation.Semigroup
                      Data.Valuation.SemiValuationAlgebra
                      Data.Valuation.Valuation
                      Data.Valuation.ValuationAlgebra
                      Data.Valuation.ValuationAlgebraOp

                      Data.Valuation.PresheafExample

  build-depends:        base >= 4.8 && < 6
                      , adjunctions >= 4.4 && < 5
                      , bifunctors >= 5 && < 6
                      , comonad >= 5 && < 6
                      , containers >= 0.5 && < 1
                      , contravariant >= 1 && < 2
                      , distributive >= 0.5 && < 1
                      , lens >= 4 && < 6
                      , mtl >= 2.2 && < 3
                      , profunctors >= 5 && < 6
                      , selective >= 0.7.0.1 && < 1
                      , semigroupoids >= 5.2 && < 7
                      , witherable >= 0.4 && < 1

  hs-source-dirs:     src
                      examples

  default-language:   Haskell2010

  ghc-options:        -Wall

test-suite doctest
  type:               exitcode-stdio-1.0
  hs-source-dirs:     test
  main-is:            Main.hs
  build-depends:      base >= 4.8 && < 6
                    , process >= 1 && < 2
  build-tool-depends: doctest:doctest >= 0.22
  default-language:   Haskell2010
  ghc-options:        -Wall
