cabal-version:   3.0
name:            aztecs-glfw
version:         0.1.0
license:         BSD-3-Clause
license-file:    LICENSE
maintainer:      matt@hunzinger.me
author:          Matt Hunzinger
homepage:        https://github.com/aztecs-hs/aztecs
synopsis:        GLFW backed for Aztecs
description:     GLFW backend for the Aztecs game engine and ECS
category:        Game Engine
build-type:      Simple
extra-doc-files: CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/aztecs-hs/aztecs-glfw.git

library
    exposed-modules:  Aztecs.GLFW
    hs-source-dirs:   src
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.2 && <5,
        aztecs >=0.16.1,
        containers >=0.7,
        GLFW-b >=3

executable aztecs-glfw
    main-is:          Main.hs
    hs-source-dirs:   app
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.2 && <5,
        aztecs-glfw,
        aztecs

test-suite aztecs-glfw-test
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    hs-source-dirs:   test
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.2 && <5,
        aztecs-glfw
