cabal-version:      1.18
name:               memo-map
version:            0.0.0.0
license:            MIT
license-file:       LICENSE
maintainer:         Freckle Education
homepage:           https://github.com/freckle/memo-map#readme
bug-reports:        https://github.com/freckle/memo-map/issues
synopsis:           Memoization in a Map
description:
    Utility for memoizing an effectful function (e.g. database query) using a Map.

category:           Memoization
build-type:         Simple
extra-source-files: package.yaml
extra-doc-files:
    README.md
    CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/freckle/memo-map

library
    exposed-modules:    MemoMap
    hs-source-dirs:     src
    other-modules:      Paths_memo_map
    default-language:   GHC2021
    default-extensions:
        BangPatterns DataKinds DerivingStrategies GADTs
        GeneralizedNewtypeDeriving LambdaCase MultiParamTypeClasses
        NoFieldSelectors NoImplicitPrelude NoMonomorphismRestriction
        OverloadedRecordDot OverloadedStrings StandaloneDeriving
        TypeApplications TypeFamilies

    ghc-options:
        -fwrite-ide-info -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-monomorphism-restriction -Wno-safe -Wno-unsafe
        -Wno-missing-kind-signatures -Wno-missing-safe-haskell-mode
        -Wno-prepositive-qualified-module

    build-depends:
        base >=4.16.4.0 && <5,
        containers >=0.6.5.1,
        unliftio >=0.2.25.0

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures

test-suite readme
    type:               exitcode-stdio-1.0
    main-is:            README.lhs
    other-modules:      Paths_memo_map
    default-language:   GHC2021
    default-extensions:
        BangPatterns DataKinds DerivingStrategies GADTs
        GeneralizedNewtypeDeriving LambdaCase MultiParamTypeClasses
        NoFieldSelectors NoImplicitPrelude NoMonomorphismRestriction
        OverloadedRecordDot OverloadedStrings StandaloneDeriving
        TypeApplications TypeFamilies

    ghc-options:
        -fwrite-ide-info -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-monomorphism-restriction -Wno-safe -Wno-unsafe
        -Wno-missing-kind-signatures -Wno-missing-safe-haskell-mode
        -Wno-prepositive-qualified-module -pgmL markdown-unlit

    build-depends:
        base >=4.16.4.0 && <5,
        markdown-unlit >=0.5.1,
        memo-map

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures
