cabal-version: 3.4
name:          tagliatelle
version:       0.9.0
synopsis:      Tagged encodings that are not spaghetti
license:       BSD-3-Clause
license-file:  LICENSE
category:      Text, Web, JSON
author:        Victor Miraldo <vcm.oss@fastmail.com>
maintainer:    Victor Miraldo <vcm.oss@fastmail.com>
homepage: https://codeberg.org/VictorCMiraldo/tagliatelle
bug-reports: https://codeberg.org/VictorCMiraldo/tagliatelle/issues

description:
  A simple codec library for producing @Data.Aeson.Value@s and a @Data.OpenApi.Schema@, focused
  on simplicity and performance.

extra-source-files:
    CHANGELOG.md
    README.md

tested-with:
    GHC == 9.12.3
  , GHC == 9.10.3
  , GHC == 9.6.7

common defaults
  default-language:   GHC2021
  default-extensions: OverloadedStrings
  ghc-options:        -Wall -Wunused-imports

library
  import:          defaults
  hs-source-dirs:  library
  exposed-modules:
    Data.Tagliatelle
    Data.Tagliatelle.Properties
    Data.Tagliatelle.OpenApi
  build-depends:
      aeson >= 2.2.5 && < 2.3
    , base >= 4.18 && < 5
    , bytestring >= 0.11.5 && < 0.13
    , containers >= 0.6.7 && < 1
    , deepseq >= 1.4.8 && < 1.6
    , hedgehog >= 1.7 && < 1.8
    , insert-ordered-containers >= 0.2.7 && < 0.3
    , microlens >= 0.5 && < 0.6
    , openapi3 >= 3.2.5 && < 3.3
    , tasty >= 1.5.4 && < 1.6
    , tasty-hedgehog >= 1.4 && < 1.5
    , text >= 2.0.2 && < 3
    , vector >= 0.13.2 && < 0.14

test-suite tests
  import:             defaults
  type:               exitcode-stdio-1.0
  hs-source-dirs:     test
  main-is:            Spec.hs
  build-depends:
      tagliatelle
    , aeson >= 2.2.5 && < 2.3
    , base >= 4.18 && < 5
    , bytestring >= 0.11.5 && < 0.13
    , containers >= 0.6.7 && < 1
    , deepseq >= 1.4.8 && < 1.6
    , hedgehog >= 1.7 && < 1.8
    , openapi3 >= 3.2.5 && < 3.3
    , tasty >= 1.5.4 && < 1.6
    , tasty-hedgehog >= 1.4 && < 1.5
    , tasty-hunit >= 0.10.2 && < 0.11
    , text >= 2.0.2 && < 3
