cabal-version: 3.0
name: hasql-mapping
version: 0.1.0.1
synopsis: SDK for defining modular mappings to databases on top of Hasql
description:
  SDK for defining mappings to databases using Hasql that promotes modular design.

  It avoids exporting abstractions unrelated to mapping, ensuring more stable versioning.

homepage: https://github.com/nikita-volkov/hasql-mapping
bug-reports: https://github.com/nikita-volkov/hasql-mapping/issues
author: Nikita Volkov <nikita.y.volkov@mail.ru>
maintainer: Nikita Volkov <nikita.y.volkov@mail.ru>
copyright: (c) 2026, Nikita Volkov
license: MIT
license-file: LICENSE
extra-doc-files:
  LICENSE
  README.md

source-repository head
  type: git
  location: https://github.com/nikita-volkov/hasql-mapping

common base
  default-language: Haskell2010
  default-extensions:
    ApplicativeDo
    BlockArguments
    DefaultSignatures
    DeriveFunctor
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    FlexibleContexts
    FlexibleInstances
    FunctionalDependencies
    GeneralizedNewtypeDeriving
    LambdaCase
    MultiParamTypeClasses
    NoImplicitPrelude
    OverloadedStrings
    ScopedTypeVariables
    TypeApplications
    TypeFamilies

library
  import: base
  hs-source-dirs: src/library
  exposed-modules:
    Hasql.Mapping
    Hasql.Mapping.IsScalar
    Hasql.Mapping.IsStatement

  build-depends:
    aeson >=2.0 && <3,
    base >=4.12 && <5,
    bytestring >=0.10 && <0.13,
    hasql ^>=1.10.1,
    iproute >=1.7 && <2,
    scientific >=0.3 && <0.4,
    text >=1.2 && <3,
    time >=1.9 && <2,
    uuid >=1.3 && <2,
