cabal-version: 1.12
name: keuringsdienst
version: 1.2.0.0
maintainer:     Josep Bigorra <jjbigorra@gmail.com>
build-type:     Simple
license:        LGPL-3
license-file: COPYING
synopsis: Data validation in Haskell: composable, easy and clean.              
description:
  Validation rules should be expressive and serve as documentation of your data.
  Based on Semigroup and Monoid operations, this makes validation rules that are easy to write, read, compose and maintain.
  See README at https://codeberg.org/jjba23/keuringsdienst.
homepage: https://codeberg.org/jjba23/keuringsdienst
         
library
  exposed-modules:
    Keuringsdienst
    Keuringsdienst.Helpers        
  hs-source-dirs:
    src
  default-extensions:
      BangPatterns
      BinaryLiterals
      ConstraintKinds
      DataKinds
      DefaultSignatures
      DeriveDataTypeable
      DeriveFoldable
      DeriveFunctor
      DeriveGeneric
      DeriveTraversable
      DoAndIfThenElse
      EmptyDataDecls
      ExistentialQuantification
      FlexibleContexts
      FlexibleInstances
      FunctionalDependencies
      GADTs
      InstanceSigs
      KindSignatures
      LambdaCase
      MultiParamTypeClasses
      MultiWayIf
      NamedFieldPuns
      OverloadedStrings
      PartialTypeSignatures
      PatternGuards
      PolyKinds
      RankNTypes
      RecordWildCards
      ScopedTypeVariables
      StandaloneDeriving
      TupleSections
      TypeFamilies
      TypeSynonymInstances
      ViewPatterns
  ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints
  build-depends:
    base < 5
    , aeson < 3
    , containers < 1
    , text < 3
  default-language: GHC2021

test-suite keuringsdienst-spec
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules:
      Paths_keuringsdienst
      KeuringsdienstSpec
      Keuringsdienst.HelpersSpec
  hs-source-dirs:
      test
  default-extensions:
      BangPatterns
      BinaryLiterals
      ConstraintKinds
      DataKinds
      DefaultSignatures
      DeriveDataTypeable
      DeriveFoldable
      DeriveFunctor
      DeriveGeneric
      DeriveTraversable
      DoAndIfThenElse
      EmptyDataDecls
      ExistentialQuantification
      FlexibleContexts
      FlexibleInstances
      FunctionalDependencies
      GADTs
      InstanceSigs
      KindSignatures
      LambdaCase
      MultiParamTypeClasses
      MultiWayIf
      NamedFieldPuns
      OverloadedStrings
      PartialTypeSignatures
      PatternGuards
      PolyKinds
      RankNTypes
      RecordWildCards
      ScopedTypeVariables
      StandaloneDeriving
      TupleSections
      TypeFamilies
      TypeSynonymInstances
      ViewPatterns
  ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints
  build-depends:
      base < 5
    , aeson < 3
    , containers < 1
    , text < 3
    , HUnit
    , keuringsdienst
  default-language: GHC2021
    
