cabal-version:   3.0
name:            aztecs-gl
version:         0.1.1
license:         BSD-3-Clause
license-file:    LICENSE
maintainer:      matt@hunzinger.me
author:          Matt Hunzinger
homepage:        https://github.com/aztecs-hs/aztecs
synopsis:        OpenGL rendering for Aztecs
description:     OpenGL rendering for the Aztecs game engine and ECS
category:        Game Engine
build-type:      Simple
extra-doc-files: CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/aztecs-hs/aztecs-gl.git

library
    exposed-modules:  Aztecs.GL
    hs-source-dirs:   src
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.2 && <5,
        aztecs >=0.17,
        aztecs-glfw >=0.2,
        aztecs-transform >=0.3.2,
        GLFW-b >=1,
        OpenGL >=3,
        vector >=0.10

test-suite aztecs-gl-test
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    hs-source-dirs:   test
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.2 && <5,
        aztecs-gl
