cabal-version:      3.8
name:               coco
version:            1.0.0.0
build-type:         Simple
category:           Conversion
author:             Konrad Czech
maintainer:         konrad@disroot.org
synopsis:           cozy conversions
description:
 A simple conversions library.
 Laws are optional and separate.
license:            MIT
homepage:           https://codeberg.org/czech/coco
bug-reports:        https://codeberg.org/czech/coco/issues
source-repository head
 type:              git
 location:          https://codeberg.org/czech/coco.git

library
 ghc-options: -Wall -Wno-tabs
 default-language: GHC2021
 build-depends:
  base >= 4.16.4.0 && < 4.23,
  utility-ht >= 0.0.16 && < 0.1,
  vector >= 0.12.3.0 && < 0.14,
  bytestring >= 0.11.4.0 && < 0.13,
  utf8-string >= 1.0.1.1 && < 1.1,
  text >= 1.2.5.0 && < 2.2,
  uuid >= 1.3.13 && < 1.4,
 exposed-modules: Coco, Coco.Laws
