cabal-version: 3.0
name: ditto-lucid
version: 0.5.0
synopsis: Add support for using lucid with Ditto
description:
  Ditto is a library for building and validating forms using applicative
  functors. This package adds support for using Ditto with Lucid.
license: BSD-3-Clause
license-file: LICENSE
author: Jeremy Shaw, Zachary Churchill
maintainer: zacharyachurchill@gmail.com
copyright:
  2012 Jeremy Shaw, SeeReason Partners LLC,
  2019 Zachary Churchill
homepage: https://github.com/goolord/ditto-lucid
bug-reports: https://github.com/goolord/ditto-lucid/issues
category: Web
build-type: Simple
extra-doc-files:
  CHANGELOG.md
  README.md
  cabal.project.local.example
tested-with:
  GHC == 9.6.7
  GHC == 9.8.4
  GHC == 9.10.3
  GHC == 9.12.4
  GHC == 9.14.1

source-repository head
  type: git
  location: https://github.com/goolord/ditto-lucid.git

common warnings-base
  ghc-options: -Wall

common warnings-modern
  if impl(ghc >= 8.10)
    ghc-options:
      -Wcompat
      -Widentities
      -Wincomplete-record-updates
      -Wincomplete-uni-patterns
      -Wmissing-deriving-strategies
      -Wunused-packages

common extensions-shared
  default-extensions:
    OverloadedStrings
    ScopedTypeVariables
    TypeFamilies

common defaults-ghc2024
  import: warnings-base, warnings-modern, extensions-shared
  default-language: GHC2024

common defaults-ghc2021
  import: warnings-base, warnings-modern, extensions-shared
  default-language: GHC2021

library
  if impl(ghc >= 9.10)
    import: defaults-ghc2024
  else
    import: defaults-ghc2021
  exposed-modules:
    Ditto.Lucid
    Ditto.Lucid.Unnamed
    Ditto.Lucid.Named
  build-depends:
      base        >= 4.14 && < 5
    , lucid       >= 2.9  && < 4
    , ditto       >= 0.4  && < 0.6
    , text        >= 1.2  && < 3
    , path-pieces >= 0.2  && < 0.4
  hs-source-dirs: src
