cabal-version:      2.2
name:               data-reify-gadt
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
copyright:          2025 Arthur Jamet
maintainer:         aj530@kent.ac.uk
author:             Arthur Jamet
tested-with:        ghc ==9.6.6 ghc ==9.8.4 ghc ==9.10.1 ghc ==9.12.1
homepage:           https://github.com/Arthi-chaud/data-reify-gadt#readme
bug-reports:        https://github.com/Arthi-chaud/data-reify-gadt/issues
synopsis:           Data.Reify for GADTs
description:
    Please see the README on GitHub at <https://github.com/Arthi-chaud/data-reify-gadt#readme>

category:           Data
build-type:         Simple
extra-source-files: README.md

source-repository head
    type:     git
    location: https://github.com/Arthi-chaud/data-reify-gadt

library
    exposed-modules:
        Data.Reify.GADT
        Data.Reify.GADT.Graph

    hs-source-dirs:     src
    other-modules:
        Lib
        Paths_data_reify_gadt

    autogen-modules:    Paths_data_reify_gadt
    default-language:   Haskell2010
    default-extensions:
        RankNTypes QuantifiedConstraints UndecidableInstances
        ExistentialQuantification TypeOperators

    ghc-options:
        -Wall -Wcompat -Widentities -Wincomplete-record-updates
        -Wincomplete-uni-patterns -Wmissing-export-lists
        -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints

    build-depends:
        base >=4.7 && <5,
        containers >=0.7 && <0.8,
        hashable >=1.5.0.0 && <1.6,
        unordered-containers >=0.2.20 && <0.3

executable example-ast
    main-is:            ast.hs
    hs-source-dirs:     examples
    other-modules:      Paths_data_reify_gadt
    autogen-modules:    Paths_data_reify_gadt
    default-language:   Haskell2010
    default-extensions:
        RankNTypes QuantifiedConstraints UndecidableInstances
        ExistentialQuantification TypeOperators

    ghc-options:
        -Wall -Wcompat -Widentities -Wincomplete-record-updates
        -Wincomplete-uni-patterns -Wmissing-export-lists
        -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints

    build-depends:
        base >=4.7 && <5,
        containers >=0.7 && <0.8,
        data-reify-gadt,
        hashable >=1.5.0.0 && <1.6,
        unordered-containers >=0.2.20 && <0.3

test-suite test
    type:               exitcode-stdio-1.0
    main-is:            Spec.hs
    hs-source-dirs:     test
    other-modules:      Paths_data_reify_gadt
    autogen-modules:    Paths_data_reify_gadt
    default-language:   Haskell2010
    default-extensions:
        RankNTypes QuantifiedConstraints UndecidableInstances
        ExistentialQuantification TypeOperators

    ghc-options:
        -Wall -Wcompat -Widentities -Wincomplete-record-updates
        -Wincomplete-uni-patterns -Wmissing-export-lists
        -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints
        -threaded -rtsopts -with-rtsopts=-N

    build-depends:
        base >=4.7 && <5,
        containers >=0.7 && <0.8,
        data-reify-gadt,
        hashable >=1.5.0.0 && <1.6,
        hspec >=2.11.11 && <2.12,
        unordered-containers >=0.2.20 && <0.3
