cabal-version:      3.0
name:               ecstatic
version:            0.1.0.0
synopsis: Build "as static as possible" executable on Linux.
tested-with: GHC ==9.12.2
description:
    The following stanzas in your cabal file will make sure that the executable
    is linked statically with all libraries except for glibc:

    @
    executable your-awesome-program
        build-tool-depends: ecstatic:ecstatic >= 0.1.0
        ghc-options: -pgml ecstatic
    @

    See README.md for background and more details.
license:            MIT
license-file:       LICENSE
author:             slycelote
maintainer:         slycelot@yandex.ru
-- copyright:
category:           Distribution
build-type:         Simple
extra-doc-files:
    CHANGELOG.md
    README.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    hs-source-dirs:   lib
    build-depends:    base >=4.11.1 && < 4.22,
                      directory >= 1.0.1 && < 1.4,
                      process >= 1.4.3.0 && < 1.7
    exposed-modules:  Distribution.Ecstatic
    default-language: Haskell2010

executable ecstatic
    import:           warnings
    main-is:          Main.hs
    -- other-modules:
    -- other-extensions:
    build-depends:    base,
                      ecstatic
    hs-source-dirs:   app
    default-language: Haskell2010
