name:                   makefile
version:                0.1.0.4
synopsis:            Simple Makefile parser
description:
  This package provides a few @Attoparser@ parsers and convenience functions
  for parsing Makefiles.

  The datatypes used for describing Makefiles are located in 'Data.Makefile'.
  The parsers and parsing functions are located in 'Data.Makefile.Parse'.

  To parse a Makefile in the current folder, simply run 'parseMakefile'. To
  parse a Makefile located at @path@, run 'parseAsMakefile' @path@.

homepage:               http://github.com/nmattia/mask
license:                MIT
license-file:           LICENSE
author:                 Nicolas Mattia
maintainer:             nicolas@nmattia.com
copyright:              2016 Nicolas Mattia
category:               Parsing
build-type:             Simple
cabal-version:          >=1.10

extra-source-files:
  test-data/basic/Makefile1
  test-data/basic/Makefile2
  test-data/elfparse/Makefile

source-repository head
  type:     git
  location: https://github.com/nmattia/mask.git

library
  hs-source-dirs:       src
  default-language:     Haskell2010
  build-depends:        base         >= 4.7 && < 5
                      , attoparsec   >= 0.12
                      , bytestring   >= 0.10
  exposed-modules:
                        Data.Makefile
                      , Data.Makefile.Parse
                      , Data.Makefile.Parse.Internal
  ghc-options:        -Wall


test-suite test
  hs-source-dirs:       src
  default-language:     Haskell2010
  type:                 exitcode-stdio-1.0
  main-is:              Test.hs
  build-depends:        base
                      , attoparsec   >= 0.12
                      , bytestring   >= 0.10
                      , doctest      >= 0.9
                      , Glob         >= 0.7
                      , makefile
  other-modules:        Data.Makefile
                      , Data.Makefile.Parse
                      , Data.Makefile.Parse.Internal
