Cabal-Version:          1.12
Name:                   regex-pcre2
Version:                1.0.0.0

build-type:             Simple
license:                BSD3
license-file:           LICENSE
copyright:
  Copyright (c) 2025, Homebrew Holdings
  Copyright (c) 2006, Christopher Kuklewicz
author:                 Pete Ryland, based on regex-pcre by Christopher Kuklewicz
maintainer:             Pete Ryland <pdr@piglet.ch>
homepage:               https://dev.piglet.ch/pdr/regex-pcre2
bug-reports:            https://dev.piglet.ch/pdr/regex-pcre2/-/issues
category:               Text

synopsis:    PCRE2 Backend for "Text.Regex" (regex-base)
description:
  This package provides a <http://pcre.org/ PCRE2> backend for the <//hackage.haskell.org/package/regex-base regex-base> API.

extra-source-files:
  ChangeLog.md

tested-with:
  GHC == 9.6.6

flag pkg-config
  default:     True
  manual:      True
  description: Use @pkg-config(1)@ to locate foreign @pcre2@ library.

source-repository head
  type:     git
  location: https://dev.piglet.ch/pdr/regex-pcre2

source-repository this
  type:     git
  location: https://dev.piglet.ch/pdr/regex-pcre2
  tag:      v1.0.0.0

library
  hs-source-dirs: src
  exposed-modules:
      Text.Regex.PCRE2
      Text.Regex.PCRE2.Wrap
      Text.Regex.PCRE2.String
      Text.Regex.PCRE2.Sequence
      Text.Regex.PCRE2.ByteString
      Text.Regex.PCRE2.ByteString.Lazy

  other-modules:
      Paths_regex_pcre2

  default-language: Haskell2010
  default-extensions:
      MultiParamTypeClasses
      FunctionalDependencies
      ForeignFunctionInterface
      ScopedTypeVariables
      GeneralizedNewtypeDeriving
      FlexibleContexts
      TypeSynonymInstances
      FlexibleInstances

  build-depends: regex-base == 0.94.*
               , base       >= 4.3 && < 5
               , containers >= 0.4 && < 0.8
               , bytestring >= 0.9 && < 0.13
               , array      >= 0.3 && < 0.6

  if !impl(ghc >= 8)
      build-depends: fail == 4.9.*

  if flag(pkg-config)
    pkgconfig-depends: libpcre2-8
  else
    extra-libraries: pcre2-8

  ghc-options:
    -O2 -Wall

test-suite regex-pcre2-test
  default-language: Haskell2010
  ghc-options:      -Wall
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Main.hs
  build-depends:    base >= 4.3 && < 5
                  , bytestring >= 0.9 && < 0.13
                  , HUnit >= 1.6 && < 1.7
                  , regex-pcre2
                  , utf8-string >= 1.0 && < 1.1

  if flag(pkg-config)
    pkgconfig-depends: libpcre2-8
  else
    extra-libraries: pcre2-8
