name:           hsmrc
version:        0.1.1
cabal-version:  >=1.10
build-type:     Simple
stability:      experimental
category:       Data
license:        BSD3
synopsis:       Library for Marc21 bibliographic records
copyright:      2025
homepage:       https://codeberg.org/brunberg/hsmrc/

library
  hs-source-dirs:   src
  build-depends:
  -- TODO: In base v4.17, Data.List docs have added warnings that the
  -- head and tail functions are partial. We should do some code rewriting
  -- to avoid compile-time warnings about this in GHC >= 9.8. See:
  -- https://github.com/haskell/core-libraries-committee/blob/main/guides/warning-for-head-and-tail.md
                    base >= 4.13.0 && < 4.17,
                    text >= 1.2.4 && < 2.2,
                    bytestring >= 0.10.10 && < 0.13
  ghc-options:      -Wall
  other-modules:
                    Data.Marc21.Constants,
                    Data.Marc21.Convenience,
                    Data.Marc21.MnemText21
  exposed-modules:
                    Data.Marc21,
                    Data.Marc21.Mnem
  default-language: Haskell2010
