Cabal-Version: 3.0
Name:		   ZipperAG
Version:	   1.0.0
License:	   BSD-3-Clause
Author:		   Pedro Martins <pedromartins4@gmail.com>, José Nuno Macedo <zenunomacedo@gmail.com>
Maintainer:    José Nuno Macedo <zenunomacedo@gmail.com>
Homepage:	   www.di.uminho.pt/~prmartins
Category:	   Experimental
Synopsis:	   An implementation of Attribute Grammars using Functional Zippers
Description:   An implementation of Attribute Grammars using Functional Zippers, includes some usage examples. For more information, refer to works such as "Zipper-based Attribute Grammars and their Extensions". 
build-type:    Simple
Copyright:     Pedro Martins
Extra-source-files: README.md
license-file:  LICENSE

source-repository head
  type:     git
  location: https://github.com/SLE-Laboratory/ZipperAG

Library
  Build-Depends:	base == 4.*, syz == 0.2.0.0, syb < 1.0
  default-language: Haskell2010
  Exposed-modules:  Language.ZipperAG,
                    Language.ZipperAG.Examples.Algol68,
                    Language.ZipperAG.Examples.BreadthFirst,
                    Language.ZipperAG.Examples.HTMLTableFormatter,
                    Language.ZipperAG.Examples.RepMin,
                    Language.ZipperAG.Examples.SmartParentesis,
                    Language.ZipperAG.Examples.DESK.DESK_circular,
                    Language.ZipperAG.Examples.DESK.DESK_HighOrder,
                    Language.ZipperAG.Examples.DESK.DESK_references,
                    Language.ZipperAG.Examples.DESK.DESK,
                    Language.ZipperAG.Examples.LET.ExampleLet,
                    Language.ZipperAG.Examples.LET.Let_Bidi,
                    Language.ZipperAG.Examples.LET.Let_DataTypes_Boilerplate,
                    Language.ZipperAG.Examples.LET.Let_Meaning_HO_NestedST_Circ,
                    Language.ZipperAG.Examples.LET.Let_No_Blocks,
                    Language.ZipperAG.Examples.LET.Let_Scope,
                    Language.ZipperAG.Examples.LET.Let_Circular_Flatening
  hs-source-dirs:   src 


