cabal-version:      3.0
name:               devforms
version:            0.1.0.0
synopsis:           A builder DSL for HTML survey forms with built-in server and storage
description:
    devforms is a Haskell library for building HTML survey forms using a
    monadic builder DSL. It bundles a Scotty web server with htmx and
    _hyperscript for client-side interactivity, Lucid2 for HTML rendering,
    and Pico CSS for styling. Submissions are stored as JSONL files.
    .
    @
    import DevForms
    .
    main :: IO ()
    main = devFormServer 9000 $ do
    \    form "My survey" "mysurvey" $ do
    \        questionLikert  "I enjoy surveys"
    \        questionChoice  "Favourite colour" ["Red", "Green", "Blue"]
    \        questionDate    "Pick a date"
    @
license:            BSD-3-Clause
license-file:       LICENSE
author:             Lassi Haasio
maintainer:         ilikeavocadoes@devmail.cc
copyright:          2026 Lassi Haasio
category:           Web
build-type:         Simple
extra-doc-files:    CHANGELOG.md
extra-source-files: static/_hyperscript.min.js
    , static/htmx.min.js
    , static/pico.classless.green.min.css

source-repository head
    type:     git
    location: https://git.sr.ht/~ilikeavocadoes/devforms

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  DevForms
    other-modules: Server
        , Form
        , Question
    -- other-extensions:
    default-extensions:
        OverloadedStrings
    build-depends:    base                 >= 4.18  && < 5
        , relude               >= 1.2   && < 1.3
        , mtl                  >= 2.2   && < 2.4
        , scotty               >= 0.22  && < 0.31
        , lucid2               >= 0.0.20230706 && < 0.1
        , htmx-lucid           >= 0.2   && < 0.3
        , warp                 >= 3.3   && < 3.5
        , wai                  >= 3.2   && < 3.3
        , http-types           >= 0.12  && < 0.13
        , aeson                >= 2.1   && < 2.3
        , time                 >= 1.12  && < 1.16
        , filepath             >= 1.4   && < 1.6
        , string-interpolate   >= 0.3   && < 0.4
        , file-embed           >= 0.0.15 && < 0.1
        , containers           >= 0.6   && < 0.9
    hs-source-dirs:   src
    default-language: GHC2021
    mixins: base hiding (Prelude)
        , relude (Relude as Prelude)
        , relude

executable example
    main-is: Example.hs
    hs-source-dirs: examples
    build-depends: base     >= 4.18 && < 5
        , devforms
        , relude    >= 1.2  && < 1.3
    default-language: GHC2021
    ghc-options:
        -threaded
    mixins: base hiding (Prelude)
        , relude (Relude as Prelude)
        , relude
