cabal-version:      3.0
name:               ppad-bolt3
version:            0.1.0
synopsis:           Bitcoin transaction formats per BOLT #3
license:            MIT
license-file:       LICENSE
author:             Jared Tobin
maintainer:         jared@ppad.tech
category:           Cryptography
build-type:         Simple
tested-with:        GHC == { 9.10.3 }
extra-doc-files:    CHANGELOG
description:
  Bitcoin transaction and script formats for the Lightning Network, per
  [BOLT #3](https://github.com/lightning/bolts/blob/master/03-transactions.md).

source-repository head
  type:     git
  location: git.ppad.tech/bolt3.git

library
  default-language: Haskell2010
  hs-source-dirs:   lib
  ghc-options:
      -Wall
  exposed-modules:
      Lightning.Protocol.BOLT3
  other-modules:
      Lightning.Protocol.BOLT3.Keys
      Lightning.Protocol.BOLT3.Scripts
      Lightning.Protocol.BOLT3.Tx
      Lightning.Protocol.BOLT3.Types
  build-depends:
      base >= 4.9 && < 5
    , bytestring >= 0.9 && < 0.13
    , deepseq >= 1.4 && < 1.6
    , ppad-bolt1 >= 0.1 && < 0.2
    , ppad-fixed >= 0.2 && < 0.3
    , ppad-ripemd160 >= 0.1.4 && < 0.2
    , ppad-secp256k1 >= 0.5.8 && < 0.6
    , ppad-sha256 >= 0.3.2 && < 0.4
    , ppad-tx >= 0.2 && < 0.3

test-suite bolt3-tests
  type:                exitcode-stdio-1.0
  default-language:    Haskell2010
  hs-source-dirs:      test
  main-is:             Main.hs
  other-modules:
      Vectors

  ghc-options:
    -rtsopts -Wall

  build-depends:
      base
    , bytestring
    , ppad-base16
    , ppad-bolt1
    , ppad-bolt3
    , ppad-secp256k1
    , ppad-sha256
    , ppad-tx
    , QuickCheck
    , tasty
    , tasty-hunit
    , tasty-quickcheck

benchmark bolt3-bench
  type:                exitcode-stdio-1.0
  default-language:    Haskell2010
  hs-source-dirs:      bench
  main-is:             Main.hs
  other-modules:       Fixtures

  ghc-options:
    -rtsopts -O2 -Wall

  build-depends:
      base
    , bytestring
    , criterion
    , deepseq
    , ppad-base16
    , ppad-bolt1
    , ppad-bolt3
    , ppad-secp256k1
    , ppad-sha256
    , ppad-tx

benchmark bolt3-weigh
  type:                exitcode-stdio-1.0
  default-language:    Haskell2010
  hs-source-dirs:      bench
  main-is:             Weight.hs
  other-modules:       Fixtures

  ghc-options:
    -rtsopts -O2 -Wall

  build-depends:
      base
    , bytestring
    , deepseq
    , ppad-base16
    , ppad-bolt1
    , ppad-bolt3
    , ppad-secp256k1
    , ppad-sha256
    , ppad-tx
    , weigh
