cabal-version:      3.0
name:               network-light
version:            0.1.0.5
synopsis:           A slimmed down version of network
description:        A slimmed down version of network, that works with both GHC and MHS. Very incomplete -- pull-requests welcome.
license:            Apache-2.0
license-file:       LICENSE
author:             Robert Krook
maintainer:         robert@krook.dev
copyright:          2025 Robert Krook
category:           Network
build-type:         Simple
extra-doc-files:    CHANGELOG.md
bug-reports:        https://github.com/Rewbert/network-light/issues
tested-with:        GHC ==9.10.3
                     || ==9.12.2
                     || ==9.14.1
                    MHS ==0.16.4.0
-- extra-source-files:

source-repository head
  type:     git
  location: https://github.com/Rewbert/network-light

flag zephyr
  description: Use the Zephyr RTOS sockaddr_in ABI
  default: False
  manual:  True

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  System.Network
    other-modules:    System.Network.Types
    -- other-extensions:
    if flag(zephyr)
        cpp-options: -DZEPHYR
    build-depends:    base >=4.20 && <5, bytestring >=0.12.2.0 && <0.13
    hs-source-dirs:   src
    default-language: Haskell2010

Test-Suite test-sockaddr-storable
    type: exitcode-stdio-1.0
    Default-language: Haskell2010
    hs-source-dirs: test/Network
    main-is: SockAddr.hs
    build-depends: base, network-light, QuickCheck
