cabal-version: 3.0
name: http2-client-grpc-effectful
version: 1.0.1
synopsis: Effectful gRPC client built on http2-client-effectful
description:
  <https://grpc.io gRPC> client for the @<https://hackage.haskell.org/package/effectful Effectful>@ ecosystem, built on top of @<https://hackage.haskell.org/package/http2-client-effectful http2-client-effectful>@.

homepage: https://digital-autonomy.institute
license: EUPL-1.2
license-file: LICENCE
author: IDA
maintainer: IDA
bug-reports: https://issues.digital-autonomy.institute
category: Web
build-type: Simple
extra-doc-files:
  CHANGELOG.md

common common
  default-language: Haskell2010
  ghc-options:
    -Weverything
    -Wno-unsafe
    -Wno-missing-safe-haskell-mode
    -Wno-missing-export-lists
    -Wno-missing-import-lists
    -Wno-missing-kind-signatures
    -Wno-all-missed-specialisations
    -Wno-missing-role-annotations

  default-extensions:
    BlockArguments
    DataKinds
    DerivingStrategies
    ExplicitNamespaces
    FlexibleContexts
    ImportQualifiedPost
    LambdaCase
    NoImplicitPrelude
    OverloadedStrings
    RecordWildCards
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators

library
  import: common
  hs-source-dirs: src
  build-depends:
    base >=4.10 && <5,
    binary >=0.8 && <0.9,
    bytestring >=0.12 && <0.13,
    effectful >=2.6 && <2.7,
    http-types >=0.12 && <0.13,
    http2 >=5.3 && <5.5,
    http2-client-effectful >=1.0 && <1.1,
    http2-grpc-types >=0.5 && <0.6,

  exposed-modules:
    Effectful.GrpcClient
