cabal-version: 3.0
name: quickcheck-effectful
version: 1.0.0
synopsis: Effectful bindings for the QuickCheck library
description:
  Adaptation of the @<https://hackage.haskell.org/package/QuickCheck QuickCheck>@ library for the @<https://hackage.haskell.org/package/effectful effectful>@ ecosystem.

homepage: https://digital-autonomy.institute
license: EUPL-1.2
license-file: LICENCE
author: IDA
maintainer: IDA
bug-reports: https://issues.digital-autonomy.institute
category: Test
build-type: Simple
extra-doc-files:
  CHANGELOG.md

common common
  default-language: Haskell2010
  ghc-options:
    -Weverything
    -Wno-unsafe
    -Wno-missing-safe-haskell-mode
    -Wno-missing-export-lists
    -Wno-missing-import-lists
    -Wno-missing-kind-signatures
    -Wno-all-missed-specialisations
    -Wno-missing-role-annotations
    -Wno-x-unstable-interface

  default-extensions:
    ApplicativeDo
    BangPatterns
    BlockArguments
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveGeneric
    DerivingStrategies
    DerivingVia
    ExistentialQuantification
    ExplicitNamespaces
    FlexibleContexts
    FlexibleInstances
    FunctionalDependencies
    GeneralizedNewtypeDeriving
    ImportQualifiedPost
    ImpredicativeTypes
    LambdaCase
    MultiParamTypeClasses
    NamedFieldPuns
    NoImplicitPrelude
    NumericUnderscores
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    QuasiQuotes
    RankNTypes
    RecordWildCards
    RecursiveDo
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators
    ViewPatterns

  build-depends:
    base >=4.10 && <5,
    effectful >=2.6 && <2.7,

library
  import: common
  hs-source-dirs: src
  exposed-modules:
    Effectful.QuickCheck

  build-depends:
    QuickCheck >=2.15 && <3,
    deepseq >=1.1 && <2,

test-suite test
  import: common
  type: exitcode-stdio-1.0
  ghc-options: -threaded
  hs-source-dirs: test
  main-is: Main.hs
  build-depends:
    quickcheck-effectful
