cabal-version: 1.12
name:           restman
-- version Controlled by semantic-release
version: 0.7.1.1
synopsis:       Web request TUI program.
description:    Please see the README on GitLab at <https://gitlab.com/krakrjak/restman#readme>
category:       Web
homepage:       https://gitlab.com/krakrjak/restman#readme
bug-reports:    https://gitlab.com/krakrjak/restman/issues
author:         Zac Slade
maintainer:     krakrjak@gmail.com, boyd.stephen.smith.jr@gmail.com
copyright:      Zac Slade or Boyd Stephen Smith Jr, 2024
license:        BSD2
license-file:   LICENSE
build-type:     Simple
extra-source-files:
    README.md
    ChangeLog.md

source-repository head
  type: git
  location: https://gitlab.com/krakrjak/restman

library
  exposed-modules:
      HTTP.Client
      Skylighting.Format.Vty
      Lib
      Types
      UI
  other-modules:
      Paths_restman
  hs-source-dirs:
      src
  build-depends:
      ansi-terminal-types
    , base >=4.7 && <5
    , binary
    , brick
    , bytestring
    , case-insensitive
    , containers
    , http-client
    , http-client-tls
    , http-types
    , lens
    , microlens-mtl
    , mime-types
    , mtl
    , skylighting
    , text
    , text-zipper
    , unliftio
    , vector
    , vty
    , wreq
  default-language: GHC2024

executable restman
  main-is: Main.hs
  other-modules:
      TUI
      Paths_restman
  hs-source-dirs:
      app
  ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
  build-depends:
      base >=4.7 && <5
    , brick
    , bytestring
    , case-insensitive
    , http-types
    , microlens
    , optparse-applicative
    , restman
    , text
    , utf8-string
    , wreq
  default-language: GHC2024

test-suite restman-test
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules:
      Paths_restman
  hs-source-dirs:
      test
  ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
  build-depends:
      base >=4.7 && <5
    , restman
  default-language: GHC2024
