name: makefile
version: 1.0.0.0
cabal-version: >=1.10
build-type: Simple
license: MIT
license-file: LICENSE
copyright: 2016-2017 Nicolas Mattia
maintainer: nicolas@nmattia.com
homepage: http://github.com/nmattia/mask
synopsis: Simple Makefile parser and generator
description:
    This package provides a few @Attoparser@ parsers and convenience functions
    for parsing Makefiles.
    The datatypes used for describing Makefiles are located in 'Data.Makefile'.
    The parsers and parsing functions are located in 'Data.Makefile.Parse'.
    To parse a Makefile in the current folder, simply run 'parseMakefile'. To
    parse a Makefile located at @path@, run 'parseAsMakefile' @path@.
category: Parsing
author: Nicolas Mattia
extra-source-files:
    test-data/basic/Makefile1
    test-data/basic/Makefile2
    test-data/elfparse/Makefile

source-repository head
    type: git
    location: https://github.com/nmattia/mask.git

library
    exposed-modules:
        Data.Makefile
        Data.Makefile.Parse
        Data.Makefile.Parse.Internal
        Data.Makefile.Render
        Data.Makefile.Render.Internal
    build-depends:
        base >=4.7 && <5,
        attoparsec >=0.12 && <0.14,
        text >=1.1 && <1.3
    default-language: Haskell2010
    hs-source-dirs: src
    ghc-options: -Wall

test-suite test
    type: exitcode-stdio-1.0
    main-is: Test.hs
    build-depends:
        base >=4.9.1.0 && <4.10,
        attoparsec >=0.12 && <0.14,
        text >=1.1 && <1.3,
        doctest >=0.9 && <0.12,
        Glob ==0.7.*,
        QuickCheck >=2.9.2 && <2.10,
        makefile >=1.0.0.0 && <1.1
    default-language: Haskell2010
    hs-source-dirs: src
    other-modules:
        Data.Makefile
        Data.Makefile.Parse
        Data.Makefile.Parse.Internal
        Data.Makefile.Render
        Data.Makefile.Render.Internal
