cabal-version:      1.18
name:               freckle-exception
version:            0.0.1.0
license:            MIT
license-file:       LICENSE
maintainer:         Freckle Education
homepage:           https://github.com/freckle/freckle-exception#readme
bug-reports:        https://github.com/freckle/freckle-exception/issues
synopsis:           Some extensions to the annotated-exception library
description:        Please see README.md
category:           Exceptions
build-type:         Simple
extra-source-files: package.yaml
extra-doc-files:
    README.md
    CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/freckle/freckle-exception

library
    exposed-modules:
        Freckle.App.Exception
        Freckle.App.Exception.MonadThrow
        Freckle.App.Exception.MonadUnliftIO
        Freckle.App.Exception.Types
        Freckle.App.Test.Hspec.AnnotatedException

    hs-source-dirs:     library
    other-modules:      Paths_freckle_exception
    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingVia DerivingStrategies GADTs
        LambdaCase NoImplicitPrelude NoMonomorphismRestriction
        OverloadedStrings TypeFamilies

    ghc-options:
        -fignore-optim-changes -fwrite-ide-info -Weverything
        -Wno-all-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-kind-signatures
        -Wno-missing-local-signatures -Wno-missing-safe-haskell-mode
        -Wno-monomorphism-restriction -Wno-prepositive-qualified-module
        -Wno-safe -Wno-unsafe

    build-depends:
        HUnit >=1.6.2.0,
        aeson >=2.0.3.0,
        annotated-exception >=0.2.0.4,
        base >=4.16.4.0 && <5,
        exceptions >=0.10.4,
        hspec >=2.10.0,
        monad-logger-aeson >=0.4.0.4,
        prettyprinter >=1.7.1,
        text >=1.2.5.0,
        unliftio >=0.2.25.0

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures

test-suite spec
    type:               exitcode-stdio-1.0
    main-is:            Spec.hs
    hs-source-dirs:     tests
    other-modules:
        Freckle.App.Test.Hspec.AnnotatedExceptionSpec
        Paths_freckle_exception

    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingVia DerivingStrategies GADTs
        LambdaCase NoImplicitPrelude NoMonomorphismRestriction
        OverloadedStrings TypeFamilies

    ghc-options:
        -fignore-optim-changes -fwrite-ide-info -Weverything
        -Wno-all-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-kind-signatures
        -Wno-missing-local-signatures -Wno-missing-safe-haskell-mode
        -Wno-monomorphism-restriction -Wno-prepositive-qualified-module
        -Wno-safe -Wno-unsafe -threaded -rtsopts -with-rtsopts=-N

    build-depends:
        HUnit >=1.6.2.0,
        annotated-exception >=0.2.0.4,
        base >=4.16.4.0 && <5,
        freckle-exception,
        hspec >=2.10.0,
        text >=1.2.5.0

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures
