cabal-version: 1.12

name:           crypton-box
version:        1.2.0
synopsis:       NaCl crypto/secret box implementations based on crypton primitives.
description:
    This library provides a high-level API for authenticated encryption and
    decryption using the NaCl [crypto_box](https://nacl.cr.yp.to/box.html) and
    [crypto_secretbox](https://nacl.cr.yp.to/secretbox.html) constructs.
    .
    The API is implemented in pure Haskell using XSalsa and Poly1305 primitives
    provided by the [crypton](https://hackage.haskell.org/package/crypton) library.
    .
    __Important: This library has not been professionally reviewed. Side__
    __channel attacks and memory-related vulnerabilities may exist! Use at your__
    __own risk.__
    .
    /(P.S. I would love to hear from you if you can audit this library and/
    /improve its security!)/
category:       Cryptography
homepage:       https://github.com/yutotakano/crypton-box#readme
bug-reports:    https://github.com/yutotakano/crypton-box/issues
author:         Yuto Takano
maintainer:     moa17stock@gmail.com
copyright:      2025-2026 Yuto Takano
license:        BSD3
license-file:   LICENSE
build-type:     Simple
extra-source-files:
    README.md
    ChangeLog.md

tested-with:
    GHC == 8.10.7
    GHC == 9.4.8
    GHC == 9.12.2

source-repository head
  type: git
  location: https://github.com/yutotakano/crypton-box

library
  exposed-modules:
      Crypto.Box
      Crypto.SecretBox
  hs-source-dirs:
      src
  default-extensions:
      OverloadedStrings
  build-depends:
      base >=4.7 && <5
    , bytestring  >= 0.9 && <1
    , crypton  >= 1.0.0 && <2
    , ram  >= 0.19 && <1
  default-language: Haskell2010

test-suite crypton-box-test
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules:
      Crypto.BoxSpec
      Crypto.SecretBoxSpec
  hs-source-dirs:
      test
  default-extensions:
      OverloadedStrings
  build-tool-depends:
      hspec-discover:hspec-discover
  build-depends:
      base >=4.7 && <5
    , bytestring
    , crypton
    , hspec
    , ram
    , crypton-box
  default-language: Haskell2010
