cabal-version:   3.4
name:            list1
version:         0.1.0
license:         BSD-3-Clause
license-file:    LICENSE
author:          Melanie Phoenix Brown
maintainer:      brown.m@proton.me
category:        Data
build-type:      Simple
extra-doc-files: CHANGELOG.md
synopsis:        Helpers for working with NonEmpty lists.
description:     Please see the README at https://github.com/mixphix/list1

library
  ghc-options:        -Wall
  default-language:   GHC2021
  default-extensions:
    BlockArguments
    LambdaCase
    PatternSynonyms
    ViewPatterns

  hs-source-dirs:     lib
  exposed-modules:    Data.List1
  build-depends:
    , base   >=4.15   && <5
