name:               waiz
version:            0.0.1.0
license:            BSD3
license-file:       LICENCE
author:             Tony Morris <tmorris@tmorris.net>
maintainer:         Tony Morris <tmorris@tmorris.net>
copyright:          Copyright (c) 2026 Tony Morris
synopsis:           Classy optics for the wai package
category:           Web
description:
  Classy optics (@GetXXX@, @HasXXX@, @ReviewXXX@, @AsXXX@) for all
  data types in the
  <https://hackage.haskell.org/package/wai wai> package.
  .
  For each data type in @wai@ (@Request@, @Response@, @FilePart@,
  @RequestBodyLength@), this package provides:
  .
  * Getter type class (@GetXXX@)
  * Lens type class (@HasXXX@)
  * Review type class (@ReviewXXX@)
  * Prism type class (@AsXXX@)
  .
  For record types, individual field lenses are provided.
  For sum types, constructor prisms with their own classy optics are provided.

homepage:           https://gitlab.com/tonymorris/waiz
bug-reports:        https://gitlab.com/tonymorris/waiz/-/issues
cabal-version:      >= 1.10
build-type:         Simple
extra-source-files: changelog
tested-with:        GHC == 9.6.7

source-repository   head
  type:             git
  location:         git@gitlab.com:tonymorris/waiz.git

library
  default-language:
                    Haskell2010

  build-depends:
                      base          >= 4.18   && < 5
                    , bytestring    >= 0.11   && < 1
                    , http-types    >= 0.12   && < 1
                    , lens          >= 4.20   && < 6
                    , network       >= 3.1    && < 4
                    , text          >= 2.0    && < 3
                    , vault         >= 0.3    && < 1
                    , wai           >= 3.2    && < 4

  ghc-options:
                    -Wall

  hs-source-dirs:
                    src

  exposed-modules:
                    Network.Wai.Optics
                    Network.Wai.Optics.FilePart
                    Network.Wai.Optics.Request
                    Network.Wai.Optics.RequestBodyLength
                    Network.Wai.Optics.Response

  other-modules:
                    Network.Wai.Optics.Internal

test-suite doctest
  type:
                    exitcode-stdio-1.0

  main-is:
                    doctest_tests.hs

  default-language:
                    Haskell2010

  build-depends:
                      base       >= 4.18   && < 5
                    , process    >= 1.6    && < 2
                    , waiz

  ghc-options:
                    -Wall
                    -threaded

  hs-source-dirs:
                    test
