name:               fuzzystrmatch-pg
version:            0.1.0.0
synopsis:           Determine string similarities and distance
description:        Haskell implementation of PostgreSQL fuzzystrmatch
                    extension
license:            MIT
license-file:       LICENSE
author:             Taimoor Zaeem
maintainer:         Taimoor Zaeem <taimoorzaeem@gmail.com>
category:           Data, Text, Algorithms
homepage:           https://github.com/taimoorzaeem/fuzzystrmatch-pg
bug-reports:        https://github.com/taimoorzaeem/fuzzystrmatch-pg/issues
build-type:         Simple
extra-source-files: CHANGELOG.md
extra-doc-files:    README.md
cabal-version:      1.18

tested-with:
    GHC == 9.4.8
  , GHC == 9.6.6
  , GHC == 9.8.4
  , GHC == 9.10.1
  , GHC == 9.12.2

source-repository head
  type: git
  location: https://github.com/taimoorzaeem/fuzzystrmatch-pg

library
  default-language:   Haskell2010
  default-extensions: NoImplicitPrelude
                      OverloadedStrings
  hs-source-dirs:     src
  exposed-modules:    Data.FuzzyStrMatch
                      Data.FuzzyStrMatch.Levenshtein
  build-depends:      base    >= 4.9   && < 4.23
                    , text    >= 1.2.2 && < 2.2
                    , vector  >= 0.11  && < 0.14

  ghc-options:        -Wall -Wunused-packages

test-suite spec
  type:               exitcode-stdio-1.0
  default-language:   Haskell2010
  default-extensions: NoImplicitPrelude
                      OverloadedStrings
  hs-source-dirs:     test/spec
  main-is:            Main.hs
  other-modules:      LevenshteinSpec
  build-depends:      base                  >= 4.9   && < 4.23
                    , criterion
                    , fuzzystrmatch-pg
                    , hspec                 >= 2.3   && < 2.12
                    , quickcheck-instances  >= 0.3.33 && < 0.4
                    , text                  >= 1.2.2 && < 2.2

  ghc-options:        -Wall -Wunused-packages
