cabal-version:      1.18
name:               iri-orphans
version:            0.0.0.0
license:            MIT
license-file:       LICENSE
maintainer:         Freckle Education
homepage:           https://github.com/freckle/iri-orphans#readme
bug-reports:        https://github.com/freckle/iri-orphans/issues
synopsis:           Orphan instances for iri
description:        Orphan instances for types defined in the `iri` package.
category:           Utils
build-type:         Simple
extra-source-files: package.yaml
extra-doc-files:
    README.md
    CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/freckle/iri-orphans

library
    exposed-modules:
        Iri.Orphans
        Iri.Orphans.Aeson
        Iri.Orphans.Aeson.FromJSON
        Iri.Orphans.Aeson.ToJSON
        Iri.Orphans.Autodocodec
        Iri.Orphans.Autodocodec.HasCodec
        Iri.Orphans.DebugPrint
        Iri.Orphans.DebugPrint.ToDebugPrintValue
        Iri.Orphans.OpenApi
        Iri.Orphans.OpenApi.ToSchema
        Iri.Orphans.Persistent
        Iri.Orphans.Persistent.PersistField
        Iri.Orphans.Persistent.PersistFieldSql
        Iri.Orphans.QuickCheck
        Iri.Orphans.QuickCheck.Arbitrary
        Iri.Orphans.Serialise
        Iri.Orphans.Serialise.Serialise

    hs-source-dirs:     src
    other-modules:      Paths_iri_orphans
    default-language:   GHC2021
    default-extensions:
        ApplicativeDo BangPatterns BlockArguments DataKinds
        DerivingStrategies DerivingVia FlexibleContexts FlexibleInstances
        GADTs GeneralizedNewtypeDeriving LambdaCase MultiParamTypeClasses
        NoImplicitPrelude NoMonomorphismRestriction OverloadedStrings
        RankNTypes RecordWildCards ScopedTypeVariables StandaloneDeriving
        TypeApplications TypeFamilies

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-monomorphism-restriction -Wno-safe -Wno-unsafe

    build-depends:
        QuickCheck >=2.14.3,
        aeson >=2.1.2.1,
        autodocodec >=0.2.2.0,
        base >=4.17.2.1 && <5,
        debug-print >=0.2.0.1,
        generic-arbitrary >=1.0.1,
        ip >=1.7.8,
        iri >=0.5.1.1,
        lens >=5.2.3,
        openapi3 >=3.2.4,
        persistent >=2.14.6.0,
        serialise >=0.2.6.1,
        text >=2.0.2,
        vector >=0.13.1.0,
        wide-word >=0.1.6.0

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures

    if impl(ghc >=9.2)
        ghc-options: -Wno-missing-kind-signatures

    if impl(ghc >=8.10)
        ghc-options:
            -Wno-missing-safe-haskell-mode -Wno-prepositive-qualified-module

    if impl(ghc >=8.8)
        ghc-options: -fwrite-ide-info

test-suite spec
    type:               exitcode-stdio-1.0
    main-is:            Spec.hs
    hs-source-dirs:     test
    other-modules:
        Iri.Orphans.QuickCheck.ArbitrarySpec
        SpecHook
        Paths_iri_orphans

    default-language:   GHC2021
    default-extensions:
        ApplicativeDo BangPatterns BlockArguments DataKinds
        DerivingStrategies DerivingVia FlexibleContexts FlexibleInstances
        GADTs GeneralizedNewtypeDeriving LambdaCase MultiParamTypeClasses
        NoImplicitPrelude NoMonomorphismRestriction OverloadedStrings
        RankNTypes RecordWildCards ScopedTypeVariables StandaloneDeriving
        TypeApplications TypeFamilies

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-monomorphism-restriction -Wno-safe -Wno-unsafe -threaded
        -rtsopts -with-rtsopts=-N

    build-depends:
        QuickCheck >=2.14.3,
        base >=4.17.2.1 && <5,
        hspec >=2.11.10,
        hspec-junit-formatter >=1.1.2.1,
        iri >=0.5.1.1,
        iri-orphans

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures

    if impl(ghc >=9.2)
        ghc-options: -Wno-missing-kind-signatures

    if impl(ghc >=8.10)
        ghc-options:
            -Wno-missing-safe-haskell-mode -Wno-prepositive-qualified-module

    if impl(ghc >=8.8)
        ghc-options: -fwrite-ide-info
