cabal-version: 3.0
name:          tigerbeetle-hs
version:       0.1.0.0
license:       BSD-3-Clause
license-file:  LICENSE
maintainer:    james@agentultra.com
author:        James King
homepage:      https://github.com/agentultra/tigerbeetle-hs#README
bug-reports:   https://github.com/agentultra/tigerbeetle-hs/issues
synopsis:      A Haskell client library for Tigerbeetle database
description:
    Please see the README on GitHub at <https://github.com/agentultra/tigerbeetle-hs#README>

category:      Experimental, Database
extra-doc-files:
    README.md
    CHANGELOG.md
    LICENSE

source-repository head
    type:     git
    location: https://github.com/agentultra/tigerbeetle-hs

library
    exposed-modules:
        Database.TigerBeetle.Account
        Database.TigerBeetle.Amount
        Database.TigerBeetle.Client
        Database.TigerBeetle.Client.Async
        Database.TigerBeetle.Client.Sync
        Database.TigerBeetle.Code
        Database.TigerBeetle.Internal.FFI.Account
        Database.TigerBeetle.Internal.FFI.Client
        Database.TigerBeetle.Ledger
        Database.TigerBeetle.Raw.Account
        Database.TigerBeetle.Raw.Client
        Database.TigerBeetle.Raw.Transfer
        Database.TigerBeetle.Response
        Database.TigerBeetle.Response.Account
        Database.TigerBeetle.Response.Transfer
        Database.TigerBeetle.Transfer
        Database.TigerBeetle.Timestamp

    pkgconfig-depends:  tb_client
    hs-source-dirs:     src
    other-modules:
        Database.TigerBeetle.Address
        Database.TigerBeetle.ClusterId
        Database.TigerBeetle.Internal.FFI.Transfer
        Database.TigerBeetle.Internal.FFI.Query
        Database.TigerBeetle.Internal.FFI.Client.ClusterId
        Database.TigerBeetle.Internal.FFI.BitFlag
        Database.TigerBeetle.Raw.Response

    default-language:   Haskell2010
    default-extensions:
        DerivingStrategies GeneralizedNewtypeDeriving ImportQualifiedPost
        OverloadedRecordDot OverloadedStrings ScopedTypeVariables

    ghc-options:        -Wall -fwrite-ide-info
    build-depends:
        base ^>=4.18.0.0,
        binary >=0.8.9 && <0.9,
        bytestring >=0.11.5 && <0.12,
        containers >=0.6.7 && <0.7,
        mtl >=2.3.1 && <2.4,
        stm >=2.5.1 && <2.6,
        text >=2.0.2 && <2.1,
        wide-word ==0.1.6.0,
        vector >=0.13.1 && <0.14

executable tigerbeetle-hs
    main-is:          Main.hs
    hs-source-dirs:   app
    default-language: Haskell2010
    extra-libraries:  tb_client
    ghc-options:      -Wall -fwrite-ide-info
    build-depends:
        base ^>=4.18.0.0,
        containers,
        tigerbeetle-hs,
        stm

test-suite tigerbeetle-hs-test
    type:             exitcode-stdio-1.0
    main-is:          Spec.hs
    hs-source-dirs:   test
    default-language: Haskell2010
    extra-libraries:  tb_client
    ghc-options:      -Wall -fwrite-ide-info
    build-depends:
        base ^>=4.18.0.0,
        hspec,
        QuickCheck,
        tigerbeetle-hs
