cabal-version:        2.4
name:                 id
version:              0.0.6
synopsis:             Id (f a) and BiId (p (s a) (t b)) data types
description:
                      Id (f a) and BiId (p (s a) (t b)) data types, with optics and functions for switching the type constructors
                      .
                      <<https://logo.systemf.com.au/systemf-450x450.jpg>>
license:              BSD-3-Clause
license-file:         LICENCE
author:               Tony Morris <ʇǝu˙sıɹɹoɯʇ@ןןǝʞsɐɥ>
maintainer:           Tony Morris <ʇǝu˙sıɹɹoɯʇ@ןןǝʞsɐɥ>
copyright:            Copyright (C) 2025-2026 Tony Morris
category:             Data
build-type:           Simple
extra-doc-files:      changelog.md
homepage:             https://gitlab.com/system-f/code/id
bug-reports:          https://gitlab.com/system-f/code/id/issues
tested-with:          GHC == 9.6.7

source-repository     head
  type:               git
  location:           git@gitlab.com:system-f/code/id.git

library
  exposed-modules:    Data.Id
                    , Data.BiId

  build-depends:        base >= 4.18 && < 6
                      , bifunctors >= 5 && < 6
                      , comonad >= 5 && < 6
                      , contravariant >= 1.4 && < 2
                      , deepseq >= 1.4 && < 2
                      , distributive >= 0.5 && < 1
                      , hashable >= 1.3 && < 2
                      , lens >= 4 && < 6
                      , mtl >= 2.2 && < 3
                      , profunctors >= 5 && < 6
                      , semigroupoids >= 6 && < 7
                      , tagged >= 0.8 && < 1
                      , selective >= 0.7 && < 1
                      , transformers >= 0.5 && < 1

  hs-source-dirs:     src

  default-language:   Haskell2010

  ghc-options:        -Wall

  if flag(dev)
    ghc-options:      -Werror

flag dev
  description:        Enable -Werror for development
  manual:             True
  default:            False

test-suite doctest
  type:               exitcode-stdio-1.0
  hs-source-dirs:     test
  main-is:            Main.hs
  build-depends:      base >= 4.8 && < 6
                    , process >= 1 && < 2
  build-tool-depends: doctest:doctest >= 0.22
  default-language:   Haskell2010
  ghc-options:        -Wall
