cabal-version:   3.0
name:            heterogeneous-comparison
version:         0.1.0.0
synopsis:        Comparison of distinctly typed values with evidence capture
description:
  There are times when values need to be tested for equality or compared for ordering, even if they aren't statically known to be of equivalent types.
  Such a test, if successful, may allow that knowledge to be recovered.
  We improve upon the state of the art in this domain by generalising over different notions of type equivalence.
license:         BSD-3-Clause
license-file:    LICENSE
author:          L. S. Leary
maintainer:      L.S.Leary.II@gmail.com
copyright:       (c) L. S. Leary 2025
category:        Data
build-type:      Simple
extra-doc-files: CHANGELOG.md README.md
tested-with:     GHC == 9.6.7, GHC == 9.8.4, GHC == 9.10.2, GHC == 9.12.2
homepage:        https://github.com/LSLeary/heterogeneous-comparison
bug-reports:     https://github.com/LSLeary/heterogeneous-comparison/issues

library
  exposed-modules:    Data.Hetero.PtrEq
                      Data.Hetero.Role
                      Data.Hetero.Evidence.Exactly
                      Data.Hetero.Evidence.AtLeast
                      Data.Hetero.Evidence
                      Data.Hetero.Eq
                      Data.Hetero.Ord
                      Data.Hetero.Some
                      Data.Hetero.ID
                      Data.Hetero.Void
                      Data.Hetero

  other-modules:      Data.Hetero.Evidence.AtLeast.Internal
  hs-source-dirs:     src
  build-depends:      base         >=4.18  && <5   ,
                      stm          >=2.4   && <2.6 ,
                      primitive    >=0.6.2 && <0.10,
                      hashable     >=1.1.1 && <1.6 ,
                      deepseq      >=1.1   && <1.6 ,
                      ord-axiomata >=0.1   && <0.2 ,

  default-language:   GHC2021
  default-extensions: LambdaCase
                      BlockArguments
                      DerivingVia
                      RoleAnnotations
  ghc-options:        -Wall
                      -Wcompat

source-repository head
  type:     git
  location: https://github.com/LSLeary/heterogeneous-comparison.git

source-repository this
  type:     git
  location: https://github.com/LSLeary/heterogeneous-comparison.git
  tag:      v0.1.0.0
