Name:                   cpsa
Version:                4.4.7
Maintainer:             guttman@mitre.org
Cabal-Version:          >= 1.10
License:                BSD3
License-File:           license.txt
Synopsis:               Symbolic cryptographic protocol analyzer
Description:
  The Cryptographic Protocol Shapes Analyzer (CPSA) attempts to
  enumerate all essentially different executions possible for a
  cryptographic protocol.  We call them the shapes of the protocol.
  Many naturally occurring protocols have only finitely many, indeed
  very few shapes.  Authentication and secrecy properties are easy to
  determine from them, as are attacks and anomalies, and an auxiliary
  tool reads off strongest authentication and secrecy goals from the
  shapes.
  .
  For each input problem, the CPSA program is given some initial
  behavior, and it discovers what shapes are compatible with it.
  Normally, the initial behavior is from the point of view of one
  participant.  The analysis reveals what the other participants must
  have done, given the participant's view.  The search is complete,
  i.e. we proved every shape can in fact be found in a finite number
  of steps, relative to a procedural semantics of protocol roles.
  .
  The package contains a set of programs used to perform the analysis
  and display it in a browser.  Program documentation is in the doc
  directory in the source distribution, and installed in the package's
  data directory.  You can locate the package's data directory by
  typing "cpsa --help" to a command prompt.  New users should study
  the documentation and the sample inputs in the data directory.  The
  source distribution includes a test suite with an expanded set of
  input files and is easily installed on operating systems that decend
  from Unix.  Serious Windows users should install MSYS so as to allow
  the use of make and script execution.
  .
  The theory and algorithm used by CPSA was developed with the help of
  Joshua D. Guttman, John D. Ramsdell, Jon C. Herzog, Shaddin
  F. Doghmi, F. Javier Thayer, Paul D. Rowe, and Moses D. Liskov.
  John D. Ramsdell implemented the algorithm in Haskell.  CPSA was
  designed and implemented at The MITRE Corporation.
Category:               Cryptography
Build-Type:             Simple
Data-Files:
  index.html cpsalogo.svg readme.html cpsauser.html cpsa4.mk Make4.hs
  init/Makefile cpsaprimer.pdf cpsagoals.pdf cpsaintroslides.pdf
  cpsaspec.pdf cpsafoundation.pdf cpsadesign.pdf
  cpsa4roletran.md roletran.pdf cpsa4prolog.pl
  ffgg.scm ns.scm blanchet.scm or.scm woolam.scm yahalom.scm goals.scm
  rules.scm cpsa4manual.pdf

Data-Dir:               doc
Extra-Source-Files:
  Makefile ChangeLog README NEWS mkghci cpsatst fixperms setup.bat
  cinstall dbtst doc/README
  doc/src/cpsa.bib doc/src/cmstrands.mp doc/src/macros.tex
  doc/src/cpsa4manual/ns_skel1.pdf doc/src/cpsa4manual/intro.tex
  doc/src/cpsa4manual/cmstrands.mp doc/src/cpsa4manual/state-rules.scm
  doc/src/cpsa4manual/ns_skel0.pdf doc/src/cpsa4manual/algebra.tex
  doc/src/cpsa4manual/tools.tex doc/src/cpsa4manual/declarations.tex
  doc/src/cpsa4manual/ns_skel2.pdf
  doc/src/cpsa4manual/ns_search_tree.eps
  doc/src/cpsa4manual/CPSA_cribsheet.pptx
  doc/src/cpsa4manual/algorithm.tex
  doc/src/cpsa4manual/yahalom_q_resp_pov1.png
  doc/src/cpsa4manual/blanchet_skel13.eps
  doc/src/cpsa4manual/kerb_skel3_operation_circled.pdf
  doc/src/cpsa4manual/secureprotocols.bib
  doc/src/cpsa4manual/envelope_skel10.pdf
  doc/src/cpsa4manual/ns_skel4.pdf doc/src/cpsa4manual/macros.tex
  doc/src/cpsa4manual/plaindh_skel4_5.pdf doc/src/cpsa4manual/ltxs.mk
  doc/src/cpsa4manual/blanchet_tree6.pdf doc/src/cpsa4manual/Makefile
  doc/src/cpsa4manual/yahalom_ch_resp_pov.png
  doc/src/cpsa4manual/kerb_skel4.eps doc/src/cpsa4manual/blanchet.mp
  doc/src/cpsa4manual/cpsadiagrams.mp doc/src/cpsa4manual/goals.tex
  doc/src/cpsa4manual/kerb_skel7.eps
  doc/src/cpsa4manual/ns_skel1_cursor.pdf
  doc/src/cpsa4manual/kerb_skel7.pdf doc/src/cpsa4manual/bcasyntax.tex
  doc/src/cpsa4manual/termtree.mp doc/src/cpsa4manual/strands.mp
  doc/src/cpsa4manual/basic.tex doc/src/cpsa4manual/kerb_skel4.pdf
  doc/src/cpsa4manual/blanchet_tree6.eps
  doc/src/cpsa4manual/ns_skel2_cursor.pdf
  doc/src/cpsa4manual/input.tex
  doc/src/cpsa4manual/examples/plaindh.scm
  doc/src/cpsa4manual/examples/plaindh.tst
  doc/src/cpsa4manual/examples/dhcr_um_expt_assume.scm
  doc/src/cpsa4manual/examples/dhcr_um_expt_assume.tst
  doc/src/cpsa4manual/examples/commitment.scm
  doc/src/cpsa4manual/examples/Makefile
  doc/src/cpsa4manual/examples/minipay-rely-guar.scm
  doc/src/cpsa4manual/examples/open-closed.tst
  doc/src/cpsa4manual/examples/ns.tst
  doc/src/cpsa4manual/examples/kerberos-variant-guar.tst
  doc/src/cpsa4manual/examples/ns.scm
  doc/src/cpsa4manual/examples/open-closed.scm
  doc/src/cpsa4manual/examples/minipay-rely-guar.tst
  doc/src/cpsa4manual/examples/or.scm
  doc/src/cpsa4manual/examples/minipay.tst
  doc/src/cpsa4manual/examples/bltk_test.scm
  doc/src/cpsa4manual/examples/blanchet.scm
  doc/src/cpsa4manual/examples/chan-yahalom-role-decl.tst
  doc/src/cpsa4manual/examples/pkinit.scm
  doc/src/cpsa4manual/examples/blanchet.tst
  doc/src/cpsa4manual/examples/pkinit.tst
  doc/src/cpsa4manual/examples/chan-yahalom-role-decl.scm
  doc/src/cpsa4manual/examples/or.tst
  doc/src/cpsa4manual/examples/minipay.scm
  doc/src/cpsa4manual/examples/bltk_test.tst
  doc/src/cpsa4manual/examples/cpsa4diff_out.tst
  doc/src/cpsa4manual/examples/cpsa4.mk
  doc/src/cpsa4manual/examples/minipay-guar.tst
  doc/src/cpsa4manual/examples/rules.scm
  doc/src/cpsa4manual/examples/minipay-guar.scm
  doc/src/cpsa4manual/examples/kerb.tst
  doc/src/cpsa4manual/examples/kerb.scm
  doc/src/cpsa4manual/examples/open-closed-late-destructure.tst
  doc/src/cpsa4manual/examples/new_dhcr_um_expt_assume.tst
  doc/src/cpsa4manual/examples/chan-yahalom.scm
  doc/src/cpsa4manual/examples/open-closed-late-destructure.scm
  doc/src/cpsa4manual/examples/chan-yahalom.tst
  doc/src/cpsa4manual/cpsaprimer.tex doc/src/cpsa4manual/carriers.mp
  doc/src/cpsa4manual/ns_skel1_cursor.eps
  doc/src/cpsa4manual/CPSA_cribsheet.pdf
  doc/src/cpsa4manual/mitrelogo.mp
  doc/src/cpsa4manual/channels_state.tex
  doc/src/cpsa4manual/blanchet_skel13.pdf
  doc/src/cpsa4manual/ns_search_tree.pdf
  doc/src/cpsa4manual/ns_skel2.eps doc/src/cpsa4manual/ltxmp.mk
  doc/src/cpsa4manual/ns_skel0.eps doc/src/cpsa4manual/ns_skel1.eps
  doc/src/cpsa4manual/trace_constraints.tex
  doc/src/cpsa4manual/cpsa4manual.tex doc/src/cpsa4manual/setup.tex
  doc/src/cpsa4manual/state.tex
  doc/src/cpsa4manual/plaindh_skel4_5.eps
  doc/src/cpsa4manual/ns_skel4.eps
  doc/src/cpsa4manual/envelope_skel10.eps
  doc/src/cpsa4manual/troubleshooting.tex
  doc/src/cpsa4manual/kerb_skel3_operation_circled.eps
  doc/src/Makefile doc/src/blanchet.mp doc/src/cpsadiagrams.mp
  doc/src/cpsaspec.tex doc/src/bcasyntax.tex doc/src/termtree.mp
  doc/src/strands.mp doc/src/cpsaintroslides.tex doc/src/mkdoc
  doc/src/mitreslides.sty doc/src/cpsafoundation.tex
  doc/src/cpsaprimer.tex doc/src/carriers.mp doc/src/mitrelogo.mp
  doc/src/cpsagoals.tex doc/src/rulestheory.tex doc/src/cpsadesign.tex
  doc/SDAG.lhs doc/cpsalogo.mp src/index.html src/cpsajson.py
  src/split.py src/cpsa2svg src/cpsa.el src/cpsaperm.scm src/lastlabel.py
  src/cpsaops.scm src/preskel src/cpsa.pl src/unsorted.pl src/pp.pl
  src/sexpr.pl src/perm.pl src/prover9.pl src/zoom.js
  src/js2hs src/ghcmemlimit build.xml src/scala/Main.scala
  src/scala/Pretty.scala src/scala/Printer.scala src/scala/SExpr.scala
  src/ocaml/Makefile src/ocaml/README src/ocaml/cpsa.d.itarget
  src/ocaml/cpsa.itarget src/ocaml/cpsa.mllib src/ocaml/cpsa.mltop
  src/ocaml/cpsa.odocl src/ocaml/expand.ml src/ocaml/main.ml
  src/ocaml/main.mli src/ocaml/pp.ml src/ocaml/token.ml
  src/ocaml/token.mli src/ocaml/scanner.mll src/ocaml/sexpr.ml
  src/ocaml/sexpr.mli src/ocaml/sexpr_type.ml tst/README tst/Makefile
  tst/ab.scm tst/abc.scm tst/aik.scm tst/atomic-open-closed.scm
  tst/attest.scm tst/auth-enc.scm tst/auth-hash.scm
  tst/blanchet-strandmax.scm tst/blanchet.scm tst/bug_example.scm
  tst/cert_lang.scm tst/chan-envelope.scm tst/chan-perrig-song.scm
  tst/chan-unilateral.scm tst/chan-yahalom-role-decl.scm
  tst/chan-yahalom.scm tst/commitment.scm tst/comp_test.scm
  tst/completeness-test.scm tst/crushing.scm tst/dass_simple.scm
  tst/denning-sacco.scm tst/deorig_contract.scm tst/deorig_mesg.scm
  tst/deorig_simple.scm tst/dh_encrypt_hack.scm
  tst/dh_group_sig_auth_failure.scm tst/dh_group_sig.scm
  tst/DH_hack.scm tst/dh_mim_hack.scm tst/dh-ca_hack.scm
  tst/dhnsl_hack.scm tst/dhstatic-state.scm tst/disclosure.scm
  tst/doorsep.scm tst/doorsep2invk.scm tst/encsig.scm tst/envelope.scm
  tst/epmo_acctnum-key-hash.scm tst/epmo-hash.scm
  tst/epmo-key-hash.scm tst/epmo.scm tst/expand.scm tst/facts.scm
  tst/factvar.scm tst/ffgg.scm tst/fluffy_draft03_gske.scm
  tst/fragile_pruning.scm tst/goals.scm tst/goalsvar.scm
  tst/hashtest-key-hash.scm tst/hashtest.scm
  tst/incompleteness_example.scm tst/isoreject-corrected.scm
  tst/isoreject.scm tst/kelly1.scm tst/kerberos.scm
  tst/locn_envelope.scm tst/missing_contraction.scm tst/neq_test.scm
  tst/neuman-stubblebine.scm tst/no_contraction.scm
  tst/non_transforming.scm tst/nonaug-prune.scm tst/ns-l.scm
  tst/ns-rebinding.scm tst/ns-unrebinding.scm tst/ns.scm tst/nsl3.scm tst/nslsk.scm
  tst/open-closed-multiloc.scm tst/open-closed-tag.scm
  tst/open-closed.scm tst/or.scm tst/ordered.scm tst/orderedvar.scm
  tst/pca.scm tst/pen-non-orig-test.scm tst/pfs-via-pubkey.scm
  tst/pkinit.scm tst/preprocess.scm tst/print.scm tst/prottrans.scm
  tst/pruning1.scm tst/puzzle_example.scm tst/reflect.scm
  tst/renamings.scm tst/role_uniq.scm tst/rule-node.scm
  tst/rule-order.scm tst/sigenc.scm tst/sorted_epmo_acctnum.scm
  tst/sts_non_role.scm tst/sts_weakened_reflect.scm tst/sts.scm
  tst/subatomic-open-closed-test-genrule.scm
  tst/subatomic-open-closed.scm tst/sync_locn_envelope.scm
  tst/targetterms1.scm tst/targetterms2.scm tst/targetterms6.scm
  tst/targetterms8.scm tst/thisthat.scm tst/tickle-unique.scm
  tst/timestamping.scm tst/trust-anchor.scm tst/ugen-at.scm
  tst/ugo.scm tst/uncarried_keys.scm tst/unilateral.scm
  tst/uniq-at.scm tst/uniq-gen-test.scm tst/uo.scm tst/wang-hash.scm
  tst/wang-key-hash.scm tst/weird.scm tst/wonthull.scm
  tst/wonthull2.scm tst/wonthull3.scm tst/woolam.scm
  tst/yahalom-6.3.6.scm tst/yahalom-forward.scm tst/yahalom.scm
  tst/yes-or-no.scm
  tst/dass-mod.lisp tst/dass.lisp tst/dh_mim.lisp tst/dhke2.lisp
  tst/ds-short.lisp tst/kelly64.lisp tst/kerb5.lisp
  tst/neuman-stubblebine-alt.lisp tst/neuman-stubblebine-reauth.lisp
  tst/nsl4.lisp tst/nsl4cm1.lisp tst/nsl4init.lisp tst/nsl4resp1.lisp
  tst/nsl4resp2.lisp tst/nsl4resp3.lisp tst/nsl5.lisp tst/nsl5i.lisp
  tst/nsl5resp3.lisp tst/tnsl5.lisp tst/wang.lisp  
  tst/dy.lsp tst/epmo_acctnum.lsp tst/mass.lsp tst/mass2.lsp
  tst/neuman-stubblebine-reauth.lsp tst/wide-mouth-frog-scyther.lsp
  tst/wide-mouth-frog.lsp  
  tst/blanchet_doorsep.prot
  tst/ab.tst tst/abc.tst tst/aik.tst tst/atomic-open-closed.tst
  tst/attest.tst tst/auth-enc.tst tst/auth-hash.tst
  tst/blanchet_doorsep.tst tst/blanchet-strandmax.tst tst/blanchet.tst
  tst/bug_example.tst tst/cert_lang.tst tst/chan-envelope.tst
  tst/chan-perrig-song.tst tst/chan-unilateral.tst
  tst/chan-yahalom-role-decl.tst tst/chan-yahalom.tst
  tst/commitment.tst tst/comp_test.tst tst/completeness-test.tst
  tst/crushing.tst tst/dass_simple.tst
  tst/defact-atomic-open-closed_shapes.tst
  tst/defact-atomic-open-closed.tst
  tst/defact-dhstatic-state_shapes.tst tst/defact-dhstatic-state.tst
  tst/defact-locn_envelope_shapes.tst tst/defact-locn_envelope.tst
  tst/defact-open-closed_shapes.tst
  tst/defact-open-closed-multiloc_shapes.tst
  tst/defact-open-closed-multiloc.tst
  tst/defact-open-closed-tag_shapes.tst tst/defact-open-closed-tag.tst
  tst/defact-open-closed.tst
  tst/defact-subatomic-open-closed_shapes.tst
  tst/defact-subatomic-open-closed-test-genrule_shapes.tst
  tst/defact-subatomic-open-closed-test-genrule.tst
  tst/defact-subatomic-open-closed.tst
  tst/defact-sync_locn_envelope_shapes.tst
  tst/defact-sync_locn_envelope.tst tst/denning-sacco.tst
  tst/deorig_contract.tst tst/deorig_mesg.tst tst/deorig_simple.tst
  tst/dh_encrypt_hack.tst tst/dh_group_sig_auth_failure.tst
  tst/dh_group_sig.tst tst/DH_hack.tst tst/dh_mim_hack.tst
  tst/dh-ca_hack.tst tst/dhnsl_hack.tst tst/dhstatic-state.tst
  tst/disclosure.tst tst/doorsep.tst tst/doorsep2invk.tst tst/dy.tst
  tst/encsig.tst tst/envelope.tst tst/epmo_acctnum-key-hash.tst
  tst/epmo_acctnum.tst tst/epmo-hash.tst tst/epmo-key-hash.tst
  tst/epmo.tst tst/example.tst tst/expand.tst tst/facts.tst
  tst/factvar.tst tst/ffgg.tst tst/fluffy_draft03_gske.tst
  tst/fragile_pruning.tst tst/goals.tst tst/goalsvar.tst
  tst/hashtest-key-hash.tst tst/hashtest.tst
  tst/incompleteness_example.tst tst/isoreject-corrected.tst
  tst/isoreject.tst tst/jdg-wonthull.tst tst/kelly1.tst
  tst/kerberos-variant-guar.tst tst/kerberos.tst tst/locn_envelope.tst
  tst/mass.tst tst/mass2.tst tst/missing_contraction.tst
  tst/neq_test.tst tst/neuman-stubblebine-reauth-tagged.tst
  tst/neuman-stubblebine-reauth.tst tst/neuman-stubblebine.tst
  tst/no_contraction.tst tst/non_transforming.tst tst/nonaug-prune.tst
  tst/ns-l.tst tst/ns-rebinding.tst tst/ns-unrebinding.tst tst/ns.tst tst/nsl3.tst
  tst/nslsk.tst tst/open-closed-multiloc.tst tst/open-closed-tag.tst
  tst/open-closed.tst tst/or.tst tst/ordered.tst tst/orderedvar.tst
  tst/pca.tst tst/pen-non-orig-test.tst tst/pfs-via-pubkey.tst
  tst/pkinit.tst tst/preprocess.tst tst/print.tst tst/prottrans.tst
  tst/pruning1.tst tst/puzzle_example.tst tst/reflect.tst
  tst/renamings.tst tst/role_uniq.tst tst/rule-node.tst
  tst/rule-order.tst tst/sa.tst tst/sigenc.tst
  tst/sorted_epmo_acctnum.tst tst/sts_non_role.tst
  tst/sts_weakened_reflect.tst tst/sts.tst
  tst/subatomic-open-closed-dist.tst
  tst/subatomic-open-closed-test-genrule.tst
  tst/subatomic-open-closed.tst tst/sync_locn_envelope.tst
  tst/targetterms1.tst tst/targetterms2.tst tst/targetterms6.tst
  tst/targetterms8.tst tst/thisthat.tst tst/tickle-unique.tst
  tst/timestamping.tst tst/tmp-yahalom.tst tst/trust-anchor.tst
  tst/ugen-at.tst tst/ugo.tst tst/uncarried_keys.tst
  tst/unilateral.tst tst/uniq-at.tst tst/uniq-gen-test.tst tst/uo.tst
  tst/wang-hash.tst tst/wang-key-hash.tst tst/weird.tst
  tst/wide-mouth-frog-scyther.tst tst/wide-mouth-frog.tst
  tst/wonthull.tst tst/wonthull2.tst tst/wonthull3.tst tst/woolam.tst
  tst/yahalom-6.3.6.tst tst/yahalom-forward.tst tst/yahalom.tst
  tst/yes-or-no.tst
  coq/Sem_tactics.v coq/Comp.v coq/Alt_sem.v coq/Match.v coq/Alg.v
  coq/Exec.v coq/Intro.v coq/Nonce.v coq/Preamble.v
  coq/Unilateral_proof.v coq/Makefile coq/Run.v coq/procdoc.tex
  coq/Run_sem.v coq/_CoqProject coq/Monad.v coq/procdoc.mk coq/README
  coq/Sem.v coq/mkdist coq/Unilateral_role.v coq/mkdoc
  coq/Examples/Bad_unilateral.v coq/Examples/Bad_unilateral_proof.v
  coq/Examples/Bad_unilateral_role.v coq/Examples/Blanchet.v
  coq/Examples/Blanchet_akey.v coq/Examples/Blanchet_akey_proof.v
  coq/Examples/Blanchet_akey_role.v coq/Examples/Blanchet_proof.v
  coq/Examples/Blanchet_role.v coq/Examples/Invk.v
  coq/Examples/Invk_proof.v coq/Examples/Invk_role.v
  coq/Examples/Makefile coq/Examples/Nsl.v coq/Examples/Nsl_proof.v
  coq/Examples/Nsl_role.v coq/Examples/Otway_rees.v
  coq/Examples/Otway_rees_proof.v coq/Examples/Otway_rees_role.v
  coq/Examples/README coq/Examples/Yahalom.v
  coq/Examples/Yahalom_proof.v coq/Examples/Yahalom_role.v
  coq/Examples/_CoqProject coq/Examples/bad_unilateral.scm
  coq/Examples/blanchet.scm coq/Examples/blanchet_akey.scm
  coq/Examples/invk.scm coq/Examples/nsl.scm
  coq/Examples/otway_rees.scm coq/Examples/update
  coq/Examples/yahalom.scm coq/Proc.v
  coq/Derives.v coq/unilateral.scm coq/Unilateral.v coq/Role.v
  coq/Subst.v coq/CSem.v coq/CRun.v coq/CRun_csem.v

Source-Repository head
  Type:     git
  Location: https://github.com/mitre/cpsa.git

Executable cpsa4
  Main-Is:              CPSA/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 4.13 && < 5, containers, parallel, deepseq
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports -threaded -rtsopts
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Utilities CPSA.Lib.ReturnFail CPSA.Lib.Pretty
    CPSA.Lib.SExpr CPSA.Lib.Printer CPSA.Lib.Entry CPSA.Options
    CPSA.Algebra CPSA.Protocol CPSA.Strand CPSA.Characteristic
    CPSA.Channel CPSA.LoadFormulas CPSA.GenRules CPSA.Loader
    CPSA.Displayer CPSA.Cohort CPSA.Operation
    CPSA.Lib.Expand CPSA.Reduction CPSA.Signature

Executable cpsa4sas
  Main-Is:              CPSA/SAS/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 4.13 && < 5, containers
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Utilities CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry CPSA.Options CPSA.Algebra
    CPSA.Signature CPSA.SAS.SAS

Executable cpsa4prot
  Main-Is:              CPSA/Prot/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 3 && < 5, containers
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Utilities CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry CPSA.Lib.Expand

Executable cpsa4goalsat
  Main-Is:              CPSA/GoalSat/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 3 && < 5
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry

Executable cpsa4diff
  Main-Is:              CPSA/Diff/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 3 && < 5
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry

Executable cpsa4graph
  Main-Is:              CPSA/Graph/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 4.13 && < 5, containers
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Utilities CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry CPSA.Graph.XMLOutput
    CPSA.Graph.Config CPSA.Graph.SVG CPSA.Graph.Loader
    CPSA.Graph.Preskeleton CPSA.Graph.Layout CPSA.Graph.Tree
    CPSA.Graph.CompactView CPSA.Graph.ExpandedView
    CPSA.Graph.LaTeXView

Executable cpsa4shapes
  Main-Is:              CPSA/Shapes/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 4.13 && < 5, containers
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.SExpr CPSA.Lib.Pretty CPSA.Lib.Printer
    CPSA.Lib.Entry CPSA.Shapes.Shapes

Executable cpsa4pp
  Main-Is:              CPSA/Pretty/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 4.13 && < 5
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry

Executable cpsa4json
  Main-Is:              CPSA/JSON/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 3 && < 5
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry

Executable cpsa4init
  Main-Is:              CPSA/Init/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 3 && < 5, directory
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa

Executable cpsa42latex
  Main-Is:              CPSA/Latex/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 3 && < 5
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry CPSA.Lib.Expand

Executable cpsa4roletran
  Main-Is:              CPSA/Roletran/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 4.13 && < 5, containers
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.ReturnFail CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry CPSA.Lib.Expand
    CPSA.Roletran.Algebra CPSA.Roletran.Protocol CPSA.Roletran.Loader
    CPSA.Roletran.Displayer CPSA.Roletran.Derivation CPSA.Roletran.Emitter

Executable cpsa4coq
  Main-Is:              CPSA/Coq/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 4.13 && < 5, containers
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Pretty CPSA.Lib.SExpr CPSA.Lib.Printer
    CPSA.Lib.Entry CPSA.Lib.Expand CPSA.Proc.Proc

Executable cpsa4rolecoq
  Main-Is:              CPSA/RoleCoq/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 4.13 && < 5, containers
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.ReturnFail CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry CPSA.Lib.Expand
    CPSA.Roletran.Algebra CPSA.Roletran.Protocol CPSA.Roletran.Loader
    CPSA.Roletran.Displayer CPSA.Roletran.Emitter

Executable cpsa4debranch
  Main-Is:              CPSA/Debranch/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 3 && < 5
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry CPSA.Lib.Expand

Executable cpsa4query
  Main-Is:              CPSA/Query/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base  >= 3 && < 5, containers
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry CPSA.Lib.Expand
    CPSA.Lib.Utilities
    CPSA.Query.Loader CPSA.Query.Tree CPSA.Query.Query

Executable cpsa4db
  Main-Is:              CPSA/Db/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 4.13 && < 5, containers
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.Utilities CPSA.Lib.Pretty CPSA.Lib.SExpr
    CPSA.Lib.Printer CPSA.Lib.Entry CPSA.Options CPSA.Algebra
    CPSA.Signature CPSA.Db.Loader CPSA.Db.Structs CPSA.Channel
    CPSA.Protocol CPSA.Db.Tree CPSA.Db.Displayer

Executable cpsa4dbprolog
  Main-Is:              CPSA/DbProlog/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base  >= 3 && < 5, containers
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.SExpr CPSA.Lib.Pretty CPSA.Lib.Printer
    CPSA.Lib.Entry CPSA.Lib.Utilities

Executable cpsa4dl
  Main-Is:              CPSA/DL/Main.hs
  Default-Language:     Haskell2010
  Build-Depends:        base >= 3 && < 5, containers
  GHC-Options:
    -Wall -fno-warn-name-shadowing -fwarn-unused-imports
  Hs-Source-Dirs:       src
  Other-Modules:
    Paths_cpsa CPSA.Lib.SExpr CPSA.Lib.Pretty CPSA.Lib.Printer
    CPSA.Lib.Entry CPSA.Lib.Utilities CPSA.DL.Structs
    CPSA.DL.Loader CPSA.DL.Prolog CPSA.DL.Compiler CPSA.DL.Simplifier
