cabal-version:  3.4

name:           bloodhound
version:        1.0.0.0
synopsis:       Elasticsearch and OpenSearch client library for Haskell
description:    Elasticsearch and OpenSearch client and query DSL for Haskell. Provides per-backend, type-safe modules for Elasticsearch 7/8/9 and OpenSearch 1/2/3, a shared Common layer, and runtime dynamic backend dispatch.
category:       Database, Search
homepage:       https://github.com/bitemyapp/bloodhound.git#readme
bug-reports:    https://github.com/bitemyapp/bloodhound.git/issues
author:         Chris Allen
maintainer:     foss@difolco.dev
copyright:      2018 Chris Allen
license:        BSD-3-Clause
license-file:   LICENSE
build-type:     Simple
extra-doc-files:
    README.md
    changelog.md
tested-with: GHC==9.8.4, GHC==9.10.3, GHC==9.12.4, GHC==9.14.1


source-repository head
  type: git
  location: https://github.com/bitemyapp/bloodhound.git

library
  exposed-modules:
      Database.Bloodhound
      Database.Bloodhound.Client
      Database.Bloodhound.Client.Cluster
      Database.Bloodhound.Requests
      Database.Bloodhound.Types
      Database.Bloodhound.Common.Client
      Database.Bloodhound.Common.Requests
      Database.Bloodhound.Common.Types
      Database.Bloodhound.Dynamic.Client
      Database.Bloodhound.ElasticSearch7.Client
      Database.Bloodhound.ElasticSearch7.Requests
      Database.Bloodhound.ElasticSearch7.Types
      Database.Bloodhound.ElasticSearch8.Client
      Database.Bloodhound.ElasticSearch8.Requests
      Database.Bloodhound.ElasticSearch8.Types
      Database.Bloodhound.ElasticSearch9.Client
      Database.Bloodhound.ElasticSearch9.Requests
      Database.Bloodhound.ElasticSearch9.Types
      Database.Bloodhound.OpenSearch1.Client
      Database.Bloodhound.OpenSearch1.Requests
      Database.Bloodhound.OpenSearch1.Types
      Database.Bloodhound.OpenSearch2.Client
      Database.Bloodhound.OpenSearch2.Requests
      Database.Bloodhound.OpenSearch2.Types
        Database.Bloodhound.OpenSearch3.Client
        Database.Bloodhound.OpenSearch3.Requests
        Database.Bloodhound.OpenSearch3.Types
        Database.Bloodhound.Internal.Utils.SSE
  other-modules:
      Database.Bloodhound.Internal.Client.BHRequest
      Database.Bloodhound.Internal.Client.Doc
      Database.Bloodhound.Internal.Utils.Requests
      Database.Bloodhound.Internal.Utils.Imports
      Database.Bloodhound.Internal.Utils.Secret
      Database.Bloodhound.Internal.Utils.StringlyTyped
      Database.Bloodhound.Internal.Versions.Common.Types.Aggregation
      Database.Bloodhound.Internal.Versions.Common.Types.Analysis
      Database.Bloodhound.Internal.Versions.Common.Types.Analyze
      Database.Bloodhound.Internal.Versions.Common.Types.AsyncSearch
      Database.Bloodhound.Internal.Versions.Common.Types.Autoscaling
      Database.Bloodhound.Internal.Versions.Common.Types.Bulk
      Database.Bloodhound.Internal.Versions.Common.Types.Cat
      Database.Bloodhound.Internal.Versions.Common.Types.Cluster
      Database.Bloodhound.Internal.Versions.Common.Types.ClusterSettings
      Database.Bloodhound.Internal.Versions.Common.Types.ClusterState
      Database.Bloodhound.Internal.Versions.Common.Types.ClusterStats
      Database.Bloodhound.Internal.Versions.Common.Types.Count
      Database.Bloodhound.Internal.Versions.Common.Types.Dangling
      Database.Bloodhound.Internal.Versions.Common.Types.DiskUsage
      Database.Bloodhound.Internal.Versions.Common.Types.Document
      Database.Bloodhound.Internal.Versions.Common.Types.Enrich
      Database.Bloodhound.Internal.Versions.Common.Types.Explain
      Database.Bloodhound.Internal.Versions.Common.Types.ExpandWildcards
      Database.Bloodhound.Internal.Versions.Common.Types.FieldCaps
      Database.Bloodhound.Internal.Versions.Common.Types.FieldUsageStats
      Database.Bloodhound.Internal.Versions.Common.Types.Fleet
      Database.Bloodhound.Internal.Versions.Common.Types.Highlight
      Database.Bloodhound.Internal.Versions.Common.Types.ILM
      Database.Bloodhound.Internal.Versions.Common.Types.Indices
      Database.Bloodhound.Internal.Versions.Common.Types.Ingest
      Database.Bloodhound.Internal.Versions.Common.Types.KeepAlive
      Database.Bloodhound.Internal.Versions.Common.Types.Logstash
      Database.Bloodhound.Internal.Versions.Common.Types.Migration
      Database.Bloodhound.Internal.Versions.Common.Types.Newtypes
      Database.Bloodhound.Internal.Versions.Common.Types.Nodes
      Database.Bloodhound.Internal.Versions.Common.Types.PendingTask
      Database.Bloodhound.Internal.Versions.Common.Types.PointInTime
      Database.Bloodhound.Internal.Versions.Common.Types.Query
      Database.Bloodhound.Internal.Versions.Common.Types.Query.CommonTerms
      Database.Bloodhound.Internal.Versions.Common.Types.Query.Commons
      Database.Bloodhound.Internal.Versions.Common.Types.Query.Fuzzy
      Database.Bloodhound.Internal.Versions.Common.Types.Query.Match
      Database.Bloodhound.Internal.Versions.Common.Types.Query.MoreLikeThis
      Database.Bloodhound.Internal.Versions.Common.Types.Query.Neural
      Database.Bloodhound.Internal.Versions.Common.Types.Query.NeuralSparse
      Database.Bloodhound.Internal.Versions.Common.Types.Query.Prefix
      Database.Bloodhound.Internal.Versions.Common.Types.Query.QueryString
      Database.Bloodhound.Internal.Versions.Common.Types.Query.Range
      Database.Bloodhound.Internal.Versions.Common.Types.Query.Regexp
      Database.Bloodhound.Internal.Versions.Common.Types.Query.SimpleQueryString
       Database.Bloodhound.Internal.Versions.Common.Types.Query.Wildcard
      Database.Bloodhound.Internal.Versions.Common.Types.Knn
      Database.Bloodhound.Internal.Versions.Common.Types.OpType
      Database.Bloodhound.Internal.Versions.Common.Types.RankEval
      Database.Bloodhound.Internal.Versions.Common.Types.Reindex
      Database.Bloodhound.Internal.Versions.Common.Types.Refresh
      Database.Bloodhound.Internal.Versions.Common.Types.ReloadSearchAnalyzers
      Database.Bloodhound.Internal.Versions.Common.Types.RemoteClusterInfo
      Database.Bloodhound.Internal.Versions.Common.Types.RepositoriesMetering
      Database.Bloodhound.Internal.Versions.Common.Types.Reroute
      Database.Bloodhound.Internal.Versions.Common.Types.Retriever
      Database.Bloodhound.Internal.Versions.Common.Types.Rollup
      Database.Bloodhound.Internal.Versions.Common.Types.Script
      Database.Bloodhound.Internal.Versions.Common.Types.ScriptContexts
      Database.Bloodhound.Internal.Versions.Common.Types.ScriptLanguages
      Database.Bloodhound.Internal.Versions.Common.Types.Security
      Database.Bloodhound.Internal.Versions.Common.Types.Security.ApiKeys
      Database.Bloodhound.Internal.Versions.Common.Types.Security.Authentication
      Database.Bloodhound.Internal.Versions.Common.Types.Security.Privileges
      Database.Bloodhound.Internal.Versions.Common.Types.Security.RoleMappings
      Database.Bloodhound.Internal.Versions.Common.Types.Security.Roles
      Database.Bloodhound.Internal.Versions.Common.Types.Security.ServiceAccounts
      Database.Bloodhound.Internal.Versions.Common.Types.Security.Sso
      Database.Bloodhound.Internal.Versions.Common.Types.Security.Users
      Database.Bloodhound.Internal.Versions.Common.Types.MultiGet
      Database.Bloodhound.Internal.Versions.Common.Types.MultiSearch
      Database.Bloodhound.Internal.Versions.Common.Types.MultiSearchTemplate
      Database.Bloodhound.Internal.Versions.Common.Types.Search
      Database.Bloodhound.Internal.Versions.Common.Types.SearchableSnapshots
      Database.Bloodhound.Internal.Versions.Common.Types.SearchShards
      Database.Bloodhound.Internal.Versions.Common.Types.SLM
      Database.Bloodhound.Internal.Versions.Common.Types.Snapshots
      Database.Bloodhound.Internal.Versions.Common.Types.Sort
      Database.Bloodhound.Internal.Versions.Common.Types.Suggest
      Database.Bloodhound.Internal.Versions.Common.Types.Task
      Database.Bloodhound.Internal.Versions.Common.Types.TermVectors
      Database.Bloodhound.Internal.Versions.Common.Types.TextStructure
      Database.Bloodhound.Internal.Versions.Common.Types.Transform
      Database.Bloodhound.Internal.Versions.Common.Types.Units
      Database.Bloodhound.Internal.Versions.Common.Types.Validate
      Database.Bloodhound.Internal.Versions.Common.Types.VectorTile
      Database.Bloodhound.Internal.Versions.Common.Types.VersionType
      Database.Bloodhound.Internal.Versions.Common.Types.VotingConfigExclusion
      Database.Bloodhound.Internal.Versions.Common.Types.Watcher
      Database.Bloodhound.Internal.Versions.ElasticSearch7.Types.DataStream
      Database.Bloodhound.Internal.Versions.ElasticSearch7.Types.EventQueryLanguage
      Database.Bloodhound.Internal.Versions.ElasticSearch7.Types.PointInTime
      Database.Bloodhound.Internal.Versions.ElasticSearch7.Types.SyncedFlush
      Database.Bloodhound.Internal.Versions.ElasticSearch7.Types.TermsEnum
      Database.Bloodhound.Internal.Versions.ElasticSearch8.Types.EsQueryLanguage
      Database.Bloodhound.Internal.Versions.ElasticSearch8.Types.EsQueryViews
      Database.Bloodhound.Internal.Versions.ElasticSearch8.Types.Inference
      Database.Bloodhound.Internal.Versions.ElasticSearch8.Types.MigrationReindex
      Database.Bloodhound.Internal.Versions.ElasticSearch8.Types.QueryRules
      Database.Bloodhound.Internal.Versions.ElasticSearch8.Types.SearchApplications
      Database.Bloodhound.Internal.Versions.ElasticSearch8.Types.Synonyms
      Database.Bloodhound.Internal.Versions.ElasticSearch8.Types.BehavioralAnalytics
      Database.Bloodhound.Internal.Versions.ElasticSearch8.Types.Connectors
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.EsQueryLanguage
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.Features
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.HealthReport
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.PointInTime
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.Streams
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.IngestGeoIp
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.SimulateIngest
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.Downsample
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.ResolveCluster
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.MlDataFrameAnalytics
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.MlTrainedModels
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.MlAnomalyJobs
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.MlDatafeeds
      Database.Bloodhound.Internal.Versions.ElasticSearch9.Types.MlFiltersCalendars
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.Alerting
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.CCR
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.AnomalyDetection
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.ISM
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.IndexTransforms
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.KnnModel
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.KnnStats
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.KnnTrain
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.MLModel
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.MLStats
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.MLTask
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.Rollups
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.SQLPPL
      Database.Bloodhound.Internal.Versions.OpenSearch1.Types.SQLStats
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.Alerting
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.CCR
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.AnomalyDetection
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.ISM
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.IndexTransforms
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.KnnModel
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.KnnStats
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.KnnTrain
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.MLAgent
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.MLConnectors
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.MLControllers
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.MLModel
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.MLModelGroups
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.MLMemory
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.MLProfile
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.MLStats
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.MLTask
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.Notifications
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.PointInTime
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.Rollups
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.SecurityAnalytics
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.SnapshotManagement
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.SQLPPL
      Database.Bloodhound.Internal.Versions.OpenSearch2.Types.SQLStats
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.Alerting
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.CCR
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.AnomalyDetection
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.FlowFramework
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.IndexTransforms
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.ISM
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.JobScheduler
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.KnnModel
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.KnnStats
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.KnnTrain
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.MLAgent
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.MLConnectors
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.MLControllers
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.MLModel
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.MLModelGroups
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.MLMemory
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.MLProfile
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.MLStats
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.MLTask
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.NeuralStats
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.Notifications
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.PointInTime
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.Rollups
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.SecurityAnalytics
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.SnapshotManagement
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.SQLPPL
      Database.Bloodhound.Internal.Versions.OpenSearch3.Types.SQLStats
      Paths_bloodhound
  autogen-modules:
      Paths_bloodhound
  hs-source-dirs:
      src
  ghc-options: -Wall
  build-depends:
      aeson >=2.0 && <3
    , base >=4.14 && <5
    , blaze-builder >= 0.1 && <1
    , bytestring >=0.10.0 && <1
    , conduit >=1.3 && <2
    , containers >=0.5.0.0 && <1
    , exceptions >=0.1 && <1
    , hashable >=1 && <2
    , http-client >=0.4.30 && <1
    , http-types >=0.8 && <1
    , microlens >=0.4 && <1
    , mtl >=1.0 && <3
    , network-uri >=2.6 && <3
    , optics-core >=0.4 && <0.5
    , resourcet >=1.2 && <2
    , scientific >=0.3.0.0 && <1
    , template-haskell >=2.10 && <3
    , text >=0.11 && <3
    , time >=1.4 && <2
    , unordered-containers >=0.1 && <1
    , vector >=0.10.9 && <1
    , versions >= 5.0.2 && <7
  default-language: GHC2021
  default-extensions:
      DataKinds
      DeriveAnyClass
      DerivingStrategies
      DerivingVia

test-suite bloodhound-tests
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules:
      Test.AggregationSpec
      Test.AlertingSpec
      Test.AnalyzeSpec
      Test.AnomalyDetectionSpec
      Test.AsyncSearchSpec
      Test.AutoscalingSpec
      Test.BehavioralAnalyticsSpec
      Test.BulkAPISpec
      Test.CatSpec
      Test.ConnectorsSpec
      Test.CCRSpec
      Test.CountSpec
      Test.DocumentOptionsSpec
      Test.DocumentsSpec
      Test.DataStreamsSpec
      Test.DiskUsageSpec
      Test.DownsampleSpec
      Test.EnrichSpec
      Test.EsQueryLanguageSpec
      Test.EsQueryViewsSpec
      Test.EventQueryLanguageSpec
      Test.ExplainSpec
      Test.ExplainOptionsSpec
      Test.FieldCapsSpec
      Test.FieldUsageStatsSpec
      Test.FeaturesSpec
      Test.FleetSpec
      Test.FreezeIndexSpec
      Test.HighlightsSpec
      Test.HealthReportSpec
      Test.HybridQuerySpec
      Test.ILMSpec
      Test.IndexDocumentParamsSpec
      Test.IndexTransformsSpec
      Test.IndicesSpec
      Test.IngestPipelineSpec
      Test.IngestGeoIpSpec
      Test.IndexSettingsOptionsSpec
      Test.InferenceSpec
      Test.ISMSpec
      Test.JSONSpec
      Test.JobSchedulerSpec
      Test.ClusterAllocationExplainSpec
      Test.ClusterHealthSpec
      Test.ClusterSettingsSpec
      Test.ClusterStateSpec
      Test.ClusterStatsSpec
      Test.ClusterRemoteInfoSpec
      Test.LogstashSpec
      Test.MLStatsSpec
      Test.MLModelSpec
      Test.MLTrainSpec
      Test.MLModelGroupsSpec
      Test.MLConnectorsSpec
      Test.MLMemorySpec
      Test.MLControllersSpec
      Test.MLProfileSpec
      Test.MlDataFrameAnalyticsSpec
      Test.MlTrainedModelsSpec
      Test.MlAnomalySpec
      Test.MigrationReindexSpec
      Test.MigrationSpec
      Test.MultiGetOptionsSpec
      Test.MultiGetSpec
      Test.MultiSearchSpec
      Test.MultiSearchTemplateSpec
      Test.NeuralQuerySpec
      Test.NeuralSearchSpec
      Test.NeuralSparseQuerySpec
      Test.NeuralStatsSpec
      Test.NeuralWarmupSpec
      Test.NeuralClearCacheSpec
      Test.NodesSpec
      Test.OSAsyncSearchSpec
      Test.ParseEsResponseSpec
      Test.PointInTimeSpec
      Test.PendingTasksSpec
      Test.QuerySpec
      Test.QueryRulesSpec
      Test.RankEvalSpec
      Test.RenderTemplateSpec
      Test.RerouteSpec
      Test.ReloadSearchAnalyzersSpec
      Test.RepositoriesMeteringSpec
      Test.ResolveClusterSpec
      Test.RollupSpec
      Test.SearchApplicationsSpec
      Test.SearchableSnapshotsSpec
      Test.SecurityApiKeysSpec
      Test.SecurityAuthenticateSpec
      Test.SecurityPrivilegesSpec
      Test.SecurityRoleMappingsSpec
      Test.SecurityRolesSpec
      Test.SecurityServiceAccountsSpec
      Test.SecuritySsoSpec
      Test.SecurityUsersSpec
      Test.SimulateIngestSpec
      Test.ReindexSpec
      Test.ReindexOptionsSpec
      Test.ReindexResponseSpec
      Test.ResizeSpec
      Test.RolloverSpec
      Test.RollupsSpec
      Test.ScanScrollSpec
      Test.ScrollSpec
      Test.ScriptSpec
      Test.ScriptContextsSpec
      Test.ScriptLanguagesSpec
      Test.SearchAfterSpec
      Test.SearchBodySpec
      Test.SearchOptionsSpec
      Test.SearchIntegrationSpec
      Test.SearchShardsSpec
      Test.SnapshotsSpec
      Test.SnapshotManagementSpec
      Test.SLMSpec
      Test.StreamsSpec
      Test.SortingSpec
      Test.SourceFilteringSpec
      Test.SuggestSpec
      Test.SyncedFlushSpec
      Test.SynonymsSpec
      Test.TasksSpec
      Test.TemplatesSpec
      Test.TermVectorsOptionsSpec
      Test.TermVectorsSpec
      Test.TextStructureSpec
      Test.TermsEnumSpec
      Test.TransformSpec
      Test.FlowFrameworkSpec
      Test.KnnClearCacheSpec
      Test.KnnEs8Spec
      Test.KnnEs9Spec
      Test.KnnModelSpec
      Test.KnnOs1Spec
      Test.KnnOs2Spec
      Test.KnnOs3Spec
      Test.KnnStatsSpec
      Test.KnnTrainSpec
      Test.KnnWarmupSpec
      Test.MLTaskSpec
      Test.NotificationsSpec
      Test.SQLPPLSpec
      Test.SQLStatsSpec
      Test.SecurityAnalyticsSpec
      Test.SSESpec
      Test.TypesSpec
      Test.ValidateSpec
      Test.VectorTileSpec
      Test.VotingConfigExclusionsSpec
      Test.WatcherSpec
      TestsUtils.ApproxEq
      TestsUtils.Common
      TestsUtils.Generators
      TestsUtils.Import
      Paths_bloodhound
  autogen-modules:
      Paths_bloodhound
  hs-source-dirs:
      tests
  ghc-options: -Wall -fno-warn-orphans
  build-depends:
      QuickCheck
    , aeson >=2.0
    , base
    , bloodhound
    , bytestring >=0.10.0
    , containers >=0.5.0.0
    , errors
    , exceptions
    , generic-random
    , hspec >=1.8
    , hspec-discover
    , http-client >=0.4.30
    , http-types >=0.8
    , microlens
    , mtl >=1.0
    , optics
    , pretty-simple
    , quickcheck-properties
    , scientific >=0.3.0.0 && <1
    , temporary
    , text >=0.11
    , time >=1.4
    , unix-compat
    , unordered-containers >=0.1 && <1
    , vector >=0.10.9
    , versions >= 5.0.2
  default-language: GHC2021
  default-extensions:
      DataKinds
      DefaultSignatures
      DeriveAnyClass
      DerivingStrategies
      DerivingVia
      DuplicateRecordFields
      LambdaCase
      OverloadedStrings
      RecordWildCards
      TypeFamilies

test-suite doctests
  type:             exitcode-stdio-1.0
  hs-source-dirs:   tests
  main-is:          Doctests.hs
  autogen-modules:
      Paths_bloodhound
  other-modules:
      Paths_bloodhound
  default-language: GHC2021
  ghc-options:      -threaded
  build-depends: 
      aeson
    , base
    , bloodhound
    , doctest >= 0.8
    , text
