cabal-version:      1.18
name:               persistent-sql-lifted
version:            0.4.2.0
license:            MIT
license-file:       LICENSE
maintainer:         Freckle Education
homepage:           https://github.com/freckle/persistent-sql-lifted#readme
bug-reports:        https://github.com/freckle/persistent-sql-lifted/issues
synopsis:
    Monad classes for running queries with Persistent and Esqueleto

description:
    This package introduces two classes: MonadSqlBackend for monadic contexts in
    which a SqlBackend is available, and MonadSqlTx for contexts in which we
    can execute a SQL transaction.
    .
    Additionally, this package provides variants of query-running utilities from
    Persistent and Esqueleto which are concretized to use SqlBackend, generalized
    to a MonadSqlBackend m constraint rather than "ReaderT backend", and wrapped in
    checkpointCallStack so that exceptions will include call stacks.

category:           Database
build-type:         Simple
extra-source-files: package.yaml
extra-doc-files:
    README.md
    CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/freckle/persistent-sql-lifted

library
    exposed-modules:
        Database.Persist.Sql.Lifted
        Database.Persist.Sql.Lifted.Core
        Database.Persist.Sql.Lifted.Esqueleto
        Database.Persist.Sql.Lifted.Expression
        Database.Persist.Sql.Lifted.Expression.ArrayAggregate.PostgreSQL
        Database.Persist.Sql.Lifted.Expression.Bool
        Database.Persist.Sql.Lifted.Expression.Case
        Database.Persist.Sql.Lifted.Expression.Comparison
        Database.Persist.Sql.Lifted.Expression.Constant
        Database.Persist.Sql.Lifted.Expression.Count
        Database.Persist.Sql.Lifted.Expression.Exists
        Database.Persist.Sql.Lifted.Expression.Insert
        Database.Persist.Sql.Lifted.Expression.Key
        Database.Persist.Sql.Lifted.Expression.List
        Database.Persist.Sql.Lifted.Expression.Maybe
        Database.Persist.Sql.Lifted.Expression.Number
        Database.Persist.Sql.Lifted.Expression.OrderBy
        Database.Persist.Sql.Lifted.Expression.Projection
        Database.Persist.Sql.Lifted.Expression.String
        Database.Persist.Sql.Lifted.Expression.SubSelect
        Database.Persist.Sql.Lifted.Expression.Table
        Database.Persist.Sql.Lifted.Expression.Type
        Database.Persist.Sql.Lifted.Expression.Update
        Database.Persist.Sql.Lifted.Filter
        Database.Persist.Sql.Lifted.From
        Database.Persist.Sql.Lifted.HasSqlBackend
        Database.Persist.Sql.Lifted.MonadSqlBackend
        Database.Persist.Sql.Lifted.MonadSqlTx
        Database.Persist.Sql.Lifted.Persistent
        Database.Persist.Sql.Lifted.Query
        Database.Persist.Sql.Lifted.Query.Aggregate
        Database.Persist.Sql.Lifted.Query.CommonTableExpressions
        Database.Persist.Sql.Lifted.Query.Core
        Database.Persist.Sql.Lifted.Query.Locking
        Database.Persist.Sql.Lifted.Query.SetOperations
        Database.Persist.Sql.Lifted.Query.Update
        Database.Persist.Sql.Lifted.Savepoint
        Database.Persist.Sql.Lifted.Update

    hs-source-dirs:     library
    other-modules:      Paths_persistent_sql_lifted
    default-language:   GHC2021
    default-extensions:
        ExplicitNamespaces FunctionalDependencies GADTs NoImplicitPrelude
        NoMonomorphismRestriction OverloadedStrings

    ghc-options:
        -fignore-optim-changes -fwrite-ide-info -Weverything
        -Wno-all-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-kind-signatures
        -Wno-missing-local-signatures -Wno-missing-safe-haskell-mode
        -Wno-monomorphism-restriction -Wno-prepositive-qualified-module
        -Wno-safe -Wno-unsafe

    build-depends:
        annotated-exception >=0.2.0.4,
        base >=4.16.4.0 && <5,
        containers >=0.6.5.1,
        esqueleto >=3.6.0.0,
        mtl >=2.2.2,
        persistent >=2.14.5.0,
        random >=1.2.1.1,
        text >=1.2.5.0,
        unliftio-core >=0.2.1.0,
        vector >=0.12.3.1

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures
