name: strict-impl-params
cabal-version: 1.12
build-type: Simple
version: 1.2.0
synopsis: Plugin for making implicit parameters strict
homepage: https://github.com/AndrasKovacs/ghc-strict-implicit-params
bug-reports: https://github.com/AndrasKovacs/ghc-strict-implicit-params/issues
copyright: 2022 András Kovács
license:        MIT
license-file:   LICENSE.txt
maintainer:     puttamalac@gmail.com
category:       Development

library
  default-language: Haskell2010
  build-depends:
      base >=4.7 && <5
    , ghc >= 9.4.8 && < 9.16
  exposed-modules: StrictImplParams

test-suite strictness
  default-language: Haskell2010
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  other-modules: Defs
  build-depends:
      base >=4.7 && <5
    , strict-impl-params
  -- -O2 and -dcore-lint needed to catch GHC
  -- miscompilation, but Hackage does not accept
  -- -dcore-lint
  ghc-options: -O2 -fplugin StrictImplParams
  -- ghc-options: -dcore-lint
