cabal-version:   3.4
name:            hasql-effectful
version:         0.2.0.0
synopsis:        Effectful bindings for hasql
description:
  @<https://hackage.haskell.org/package/effectful Effectful>@ bindings for @<https://hackage.haskell.org/package/hasql hasql>@

category:        Database
homepage:        https://github.com/shinzui/hasql-effectful
license:         MIT
license-file:    LICENSE
author:          Nadeem Bitar
maintainer:      nadeem@gmail.com
build-type:      Simple
tested-with:     GHC >=9.12
extra-doc-files: CHANGELOG.md

source-repository head
  type:     git
  location: https://github.com/shinzui/hasql-effectful.git

flag examples
  description: Build example executables
  manual:      True
  default:     False

common warnings
  ghc-options:
    -Wall -Wcompat -Widentities -Wincomplete-uni-patterns
    -Wincomplete-record-updates -Wredundant-constraints
    -fhide-source-paths -Wmissing-export-lists -Wpartial-fields
    -Wmissing-deriving-strategies

common common
  import:             warnings
  default-extensions:
    DataKinds
    DerivingStrategies
    LambdaCase
    TypeFamilies

library
  import:           common
  exposed-modules:  Effectful.Hasql
  build-depends:
    , base        >=4.21 && <5
    , effectful   >=2.5  && <3
    , hasql       >=1.10 && <1.11
    , hasql-pool  >=1.4  && <1.5

  hs-source-dirs:   src
  default-language: GHC2021

executable hasql-effectful-example
  import:           common
  ghc-options:      -threaded -rtsopts -with-rtsopts=-N
  main-is:          Main.hs
  hs-source-dirs:   examples
  default-language: GHC2021

  if !flag(examples)
    buildable: False

  build-depends:
    , base               >=4.21 && <5
    , bytestring         >=0.11 && <0.13
    , effectful          >=2.5  && <3
    , hasql              >=1.10 && <1.11
    , hasql-effectful
    , hasql-pool         >=1.4  && <1.5
    , hasql-transaction  >=1.2  && <1.3
    , text               >=2.0  && <2.2

test-suite hasql-effectful-test
  import:           common
  default-language: GHC2021
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Main.hs
  build-depends:
    , base             >=4.21 && <5
    , hasql-effectful
