cabal-version: 3.0
name: caliper
version: 0.1.0.0
category: CLI

synopsis:
  A time tracker that is way too precise.

description:
  Reads from caliper format and can generate histogram and time summation.
  Supports query syntax to filter entries.

author:        Léana 江
maintainer:    leana.jiang@icloud.com

license: GPL-3.0-or-later
license-files: ./LICENSE

extra-source-files:
  -- golden test files
  ./test/data/**/*.clp
  ./test/data/**/*.expr

common common
  default-language:   GHC2021
  default-extensions:
    OverloadedStrings

  ghc-options:
    -Wall -Wcompat -Widentities -Wincomplete-record-updates
    -Wincomplete-patterns -Wincomplete-uni-patterns
    -Wredundant-constraints -Werror=missing-fields

  build-depends:      base >=4 && <5

library caliper-lib
  import:          common
  hs-source-dirs:  src
  exposed-modules:
    Caliper.Cli
    Caliper.Cli.Parsing
    Caliper.Cli.Printing
    Caliper.Syntax
    Caliper.Syntax.Ast
    Caliper.Syntax.Parsing
    Caliper.Syntax.Position
    Caliper.Syntax.Resolution
    Caliper.Syntax.Transform

  build-depends:
    , containers            >=0.6.8     && <0.8
    , deepseq               >=1.5       && <2
    , filepath              >=1.4.100.3 && <1.5.4
    , megaparsec            >=9.5       && <9.7
    , optparse-applicative  >=0.15      && <0.19
    , text                  >=2.1.2     && <2.1.3
    , time                  >=1.9       && <1.15
    , transformers          >=0.5.6     && <0.6.3

executable caliper
  import:         common
  hs-source-dirs: app/
  main-is:        Main.hs
  build-depends:
    , megaparsec            >=9.5   && <9.7
    , optparse-applicative  >=0.15  && <0.19
    , caliper-lib
    , text                  >=2.1.2 && <2.1.3
    , time                  >=1.9   && <1.15

  other-modules:

test-suite caliper-spec
  import:         common
  type:           exitcode-stdio-1.0
  main-is:        Main.hs
  hs-source-dirs: test
  other-modules:  Data.TreeDiff.Instances.Caliper
  build-depends:
    , containers    >=0.6.8     && <0.8
    , filepath      >=1.4.100.3 && <1.5.4
    , megaparsec    >=9.5       && <9.7
    , caliper-lib
    , tasty         >=1.4.2.2   && <1.5.3
    , tasty-golden  >=2.3.1.1   && <2.3.5
    , text          >=2.1.2     && <2.1.3
    , time          >=1.9       && <1.15
    , tree-diff     >=0.3.1     && <0.3.4
