cabal-version:   1.18
name:            yaml-marked
version:         0.1.0.0
license:         MIT
license-file:    LICENSE
maintainer:      Pat Brisbin <pbrisbin@gmail.com>
author:          Pat Brisbin <pbrisbin@gmail.com>
stability:       stable
homepage:        https://github.com/pbrisbin/yaml-marked#readme
bug-reports:     https://github.com/pbrisbin/yaml-marked/issues
synopsis:
    Support for parsing and rendering YAML documents with marks.

description:     Please see README.md
category:        Data
build-type:      Simple
extra-doc-files:
    README.md
    CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/pbrisbin/yaml-marked

library
    exposed-modules:
        Data.Aeson.Compat
        Data.Aeson.Compat.Key
        Data.Aeson.Compat.KeyMap
        Data.Yaml.Marked
        Data.Yaml.Marked.Decode
        Data.Yaml.Marked.Internal
        Data.Yaml.Marked.Parse
        Data.Yaml.Marked.Replace
        Data.Yaml.Marked.Value

    hs-source-dirs:     src
    other-modules:      Paths_yaml_marked
    default-language:   Haskell2010
    default-extensions:
        BangPatterns DataKinds DeriveAnyClass DeriveFoldable DeriveFunctor
        DeriveGeneric DeriveLift DeriveTraversable DerivingStrategies
        FlexibleContexts FlexibleInstances GADTs GeneralizedNewtypeDeriving
        LambdaCase MultiParamTypeClasses NoImplicitPrelude
        NoMonomorphismRestriction OverloadedStrings RankNTypes
        RecordWildCards ScopedTypeVariables StandaloneDeriving
        TypeApplications TypeFamilies

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-monomorphism-restriction -Wno-safe -Wno-unsafe

    build-depends:
        aeson >=1.4.7.1,
        attoparsec >=0.13.2.4,
        base >=4.13.0.0 && <5,
        bytestring >=0.10.10.1,
        conduit >=1.3.4,
        containers >=0.6.2.1,
        dlist >=0.8.0.8,
        libyaml >=0.1.2,
        mtl >=2.2.2,
        resourcet >=1.2.4.2,
        scientific >=0.3.6.2,
        text >=1.2.4.0,
        transformers >=0.5.6.2,
        unliftio >=0.2.13.1,
        unordered-containers >=0.2.10.0,
        vector >=0.12.1.2,
        yaml >=0.11.5.0

    if impl(ghc >=9.8)
        ghc-options: -Wno-missing-role-annotations

    if impl(ghc >=9.2)
        ghc-options: -Wno-missing-kind-signatures

    if impl(ghc >=8.10)
        ghc-options:
            -Wno-missing-safe-haskell-mode -Wno-prepositive-qualified-module

test-suite readme
    type:               exitcode-stdio-1.0
    main-is:            README.lhs
    other-modules:      Paths_yaml_marked
    default-language:   Haskell2010
    default-extensions:
        BangPatterns DataKinds DeriveAnyClass DeriveFoldable DeriveFunctor
        DeriveGeneric DeriveLift DeriveTraversable DerivingStrategies
        FlexibleContexts FlexibleInstances GADTs GeneralizedNewtypeDeriving
        LambdaCase MultiParamTypeClasses NoImplicitPrelude
        NoMonomorphismRestriction OverloadedStrings RankNTypes
        RecordWildCards ScopedTypeVariables StandaloneDeriving
        TypeApplications TypeFamilies

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-monomorphism-restriction -Wno-safe -Wno-unsafe -pgmL
        markdown-unlit

    build-depends:
        base >=4.13.0.0 && <5,
        bytestring >=0.10.10.1,
        markdown-unlit >=0.5.1,
        text >=1.2.4.0,
        yaml-marked

    if impl(ghc >=9.8)
        ghc-options: -Wno-missing-role-annotations

    if impl(ghc >=9.2)
        ghc-options: -Wno-missing-kind-signatures

    if impl(ghc >=8.10)
        ghc-options:
            -Wno-missing-safe-haskell-mode -Wno-prepositive-qualified-module

test-suite spec
    type:               exitcode-stdio-1.0
    main-is:            Spec.hs
    hs-source-dirs:     test
    other-modules:
        Data.Yaml.Marked.DecodeSpec
        Data.Yaml.Marked.InternalSpec
        Data.Yaml.Marked.ReplaceSpec
        Paths_yaml_marked

    default-language:   Haskell2010
    default-extensions:
        BangPatterns DataKinds DeriveAnyClass DeriveFoldable DeriveFunctor
        DeriveGeneric DeriveLift DeriveTraversable DerivingStrategies
        FlexibleContexts FlexibleInstances GADTs GeneralizedNewtypeDeriving
        LambdaCase MultiParamTypeClasses NoImplicitPrelude
        NoMonomorphismRestriction OverloadedStrings RankNTypes
        RecordWildCards ScopedTypeVariables StandaloneDeriving
        TypeApplications TypeFamilies

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-monomorphism-restriction -Wno-safe -Wno-unsafe -threaded
        -rtsopts -with-rtsopts=-N

    build-depends:
        aeson >=1.4.7.1,
        base >=4.13.0.0 && <5,
        bytestring >=0.10.10.1,
        hspec >=2.7.6,
        hspec-expectations-json >=1.0.2.1,
        semigroupoids >=5.3.4,
        text >=1.2.4.0,
        yaml >=0.11.5.0,
        yaml-marked

    if impl(ghc >=9.8)
        ghc-options: -Wno-missing-role-annotations

    if impl(ghc >=9.2)
        ghc-options: -Wno-missing-kind-signatures

    if impl(ghc >=8.10)
        ghc-options:
            -Wno-missing-safe-haskell-mode -Wno-prepositive-qualified-module
