cabal-version: 3.6
name: A-gent
version: 0
synopsis: Λ-gent, based on placeholder definitions for TODO and unimplemented
description: Λ-gent, based placeholder definitions for TODO and unimplemented code
homepage: https://a-gent.org
license: AGPL-3.0-only
license-file: LICENSE
author: SPISE MISU
maintainer: SPISE MISU <mail+hackage@spisemisu.com>
copyright: Copyright (c) 2026 SPISE MISU ApS
stability: experimental
category: Agent, LLM
build-type: Simple
extra-doc-files: README.md, CHANGELOG.md

source-repository head
  type:
      git
  location:
      https://gitlab.com/a-gent/a-gent

common base
  default-language:
      Haskell2010
  default-extensions:
      Safe
  build-depends:
      -- Prelude
      base >= 4 && < 5
  ghc-options:
      -Wall

library
  import:
      base
  hs-source-dirs:
      src
  exposed-modules:
      Agent.LLM
