cabal-version:      1.18
name:               hspec-annotated-exception
version:            0.0.0.0
license:            MIT
license-file:       LICENSE
maintainer:         Freckle Education
homepage:           https://github.com/freckle/hspec-annotated-exception#readme
bug-reports:        https://github.com/freckle/hspec-annotated-exception/issues
synopsis:
    Hspec hook that unwraps test failures from AnnotatedException

description:
    An hspec hook that lets hspec catch and pretty-print HUnitFailure,
    the exception that is thrown when a test assertion fails, in the
    correct way even if it is wrapped in AnnotatedException.

category:           Utils
build-type:         Simple
extra-source-files: package.yaml
extra-doc-files:
    README.md
    CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/freckle/hspec-annotated-exception

library
    exposed-modules:    Test.Hspec.AnnotatedException
    hs-source-dirs:     src
    other-modules:      Paths_hspec_annotated_exception
    default-language:   GHC2021
    default-extensions: LambdaCase NoImplicitPrelude OverloadedStrings
    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-monomorphism-restriction -Wno-safe -Wno-unsafe

    build-depends:
        HUnit >=1.6.2.0,
        annotated-exception >=0.2.0.5,
        base >=4.17.2.1 && <5,
        hspec >=2.11.10,
        lens >=5.2.3,
        text >=2.0.2

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures

    if impl(ghc >=9.2)
        ghc-options: -Wno-missing-kind-signatures

    if impl(ghc >=8.10)
        ghc-options:
            -Wno-missing-safe-haskell-mode -Wno-prepositive-qualified-module

    if impl(ghc >=8.8)
        ghc-options: -fwrite-ide-info
