cabal-version: 3.0
name: fluent-icu
version: 1.0.0
synopsis: ICU backend for fluent
description: ICU backend for <https://hackage.haskell.org/package/fluent fluent>.
license: EUPL-1.2
license-file: LICENCE
author: IDA
maintainer: IDA
homepage: https://digital-autonomy.institute
bug-reports: https://issues.digital-autonomy.institute
category: Language
build-type: Simple
extra-doc-files:
  CHANGELOG.md

common common
  default-language: Haskell2010
  ghc-options:
    -Weverything
    -Wno-safe
    -Wno-unsafe
    -Wno-all-missed-specialisations
    -Wno-missing-export-lists
    -Wno-missing-import-lists
    -Wno-missing-kind-signatures
    -Wno-missing-role-annotations
    -Wno-missing-safe-haskell-mode
    -Wno-orphans

  default-extensions:
    BlockArguments
    FlexibleInstances
    ImportQualifiedPost
    LambdaCase
    NamedFieldPuns
    NoImplicitPrelude
    OverloadedRecordDot
    OverloadedStrings
    QuasiQuotes
    RecordWildCards
    TypeApplications
    TypeOperators
    ViewPatterns

  build-depends:
    base >=4.11 && <5,
    fluent >=1.0 && <1.1,
    text >=2.0 && <2.2,

library
  import: common
  hs-source-dirs: src
  build-depends:
    bytestring >=0.11 && <0.13,
    scientific >=0.3 && <0.4,
    text-icu >=0.8 && <0.9,
    time >=1.12 && <1.17,

  c-sources: cbits.c
  pkgconfig-depends:
    icu-i18n,
    icu-uc,

  exposed-modules:
    Language.Fluent.ICU

test-suite test
  import: common
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Spec.hs
  other-modules:
    BuiltinSpec
    LocaleSpec
    NumberSpec
    PluralSpec
    Prelude
    TimeSpec

  build-depends:
    fluent-icu,
    hspec >=2.11 && <2.12,
    scientific >=0.3 && <0.4,
    time >=1.12 && <1.17,
