name:           gi-soup
version:        2.4.30
x-revision: 1
synopsis:       Libsoup 2.4.x bindings (compatibility layer)
description:    This package re-exports (for backward compatibility)
                the haskell-gi generated bindings in the gi-soup2 package.
homepage:       https://github.com/haskell-gi/haskell-gi
license:        LGPL-2.1
license-file:   LICENSE
author:         Iñaki García Etxebarria
maintainer:     Iñaki García Etxebarria
category:       Bindings
build-type:     Custom
cabal-version:  2.0

extra-source-files: README.md

custom-setup
 setup-depends:
   base >= 4.11 && <5,
   haskell-gi ^>= 0.26.14,
   Cabal >= 1.24 && < 4,
   gi-soup2 ^>= 2.4.30

library
    ghc-options: -Wall

    build-depends: base >= 4.11 && <5,
                   gi-soup2 ^>= 2.4.30

    default-language: Haskell2010
