cabal-version:       3.0
name:                inj
version:             2.0
synopsis:            A class for injective (one-to-one) functions
description:
  An injection is a function that never maps distinct elements of the domain
  to the same element of the codomain. For example, @(\\x -> x + 1)@ is an
  injection, but @(\\x -> min x 0)@ is not.
  .
  This package provides the @Inj@ class, whose instances can be composed to
  construct nested structures from singleton elements.
license:             BSD-3-Clause
license-file:        LICENSE
author:              Vladislav Zavialov
maintainer:          Vladislav Zavialov <vlad.z.4096@gmail.com>
category:            Control
build-type:          Simple
tested-with:         GHC ==9.2.8, GHC ==9.4.8, GHC ==9.6.7, GHC ==9.8.4,
                     GHC ==9.10.3, GHC ==9.12.4, GHC ==9.14.1
extra-doc-files:     README.md
                     CHANGELOG.md

source-repository head
  type: git
  location: https://github.com/int-index/inj.git

library
  exposed-modules:     Control.Inj
  build-depends:       base >=4.16 && <5
  hs-source-dirs:      src
  default-language:    Haskell2010
  ghc-options:         -Wall
