cabal-version:      3.0
build-type:         Simple
name:               crypto-rng-effectful
version:            1.0.1.0
license:            MIT
license-file:       LICENSE
category:           Crypto
maintainer:         andrzej@rybczak.net
author:             Andrzej Rybczak, Dominik Peteler, Hécate Moonlight

synopsis:           Adaptation of the crypto-rng library for the effectful ecosystem.

description:        Adaptation of the @<https://hackage.haskell.org/package/crypto-rng crypto-rng>@ library for the @<https://hackage.haskell.org/package/effectful effectful>@ ecosystem.

homepage:           https://github.com/haskell-effectful/crypto-rng-effectful

extra-doc-files:    CHANGELOG.md
                  , README.md

tested-with: GHC == { 8.10.7, 9.0.2, 9.2.8, 9.4.8, 9.6.7, 9.8.4, 9.10.3, 9.12.4, 9.14.1 }

bug-reports: https://github.com/haskell-effectful/crypto-rng-effectful/issues
source-repository head
  type:     git
  location: https://github.com/haskell-effectful/crypto-rng-effectful

common language
    ghc-options:        -Wall -Wcompat -Wredundant-constraints
                        -Wno-unticked-promoted-constructors
                        -Werror=prepositive-qualified-module

    default-language:   Haskell2010

    default-extensions: DataKinds
                        DerivingStrategies
                        FlexibleContexts
                        FlexibleInstances
                        GADTs
                        GeneralizedNewtypeDeriving
                        ImportQualifiedPost
                        LambdaCase
                        TypeFamilies
                        TypeOperators

library
  import:          language

  build-depends:     base            >= 4.14       && < 5
                   , bytestring      >= 0.10.8
                   , crypto-rng      >= 0.3        && < 0.4
                   , effectful-core  >= 1.0.0.0    && < 3.0.0.0
                   , random          >= 1.2        && < 1.4

  hs-source-dirs:  src

  exposed-modules: Effectful.Crypto.RNG
                   Effectful.Crypto.RNG.Unsafe

  other-modules:   Effectful.Crypto.RNG.Effect


test-suite test
  import:         language

  ghc-options:    -threaded -rtsopts -with-rtsopts=-N4

  build-depends:    base
                  , bytestring
                  , crypto-rng
                  , effectful-core
                  , crypto-rng-effectful
                  , tasty
                  , tasty-hunit

  hs-source-dirs: tests

  type:           exitcode-stdio-1.0
  main-is:        Main.hs

  other-modules:  Utils
