cabal-version: 2.4
name: hasql-auto
version: 0.1.0.1
license: MPL-2.0
copyright: 2026 Mike Ledger
maintainer: Mike Ledger <mike@quasimal.com>
author: Mike Ledger <mike@quasimal.com>
category: Web
homepage: https://gitlab.com/combobulate.systems/hasql-auto
synopsis: Automatically derived encoders and decoders for Hasql
description:
  .
  Write less boilerplate when decoding or encoding things out of or into Hasql.
  .
  This package provides a superset of functionality of
  [hasql-implicits](https://hackage.haskell.org/package/hasql-implicits) and
  [hasql-generic](https://hackage.haskell.org/package/hasql-generic), by adding
  its own utility functions, types, and instances.
  .
  "Hasql.Auto.Decoders" is substantively derived from  [hasql-implicits](https://hackage.haskell.org/package/hasql-implicits).

extra-source-files:
  LICENSE

common shared
  default-extensions:
    AllowAmbiguousTypes
    BangPatterns
    BlockArguments
    DataKinds
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    ExplicitForAll
    GADTs
    ImportQualifiedPost
    LambdaCase
    MultiWayIf
    NoStarIsType
    OverloadedRecordDot
    OverloadedStrings
    PartialTypeSignatures
    PatternSynonyms
    PolyKinds
    RequiredTypeArguments
    ScopedTypeVariables
    StrictData
    TemplateHaskell
    TemplateHaskellQuotes
    TypeFamilies
    UndecidableInstances
    ViewPatterns

  build-depends:
    aeson ^>=2.2,
    base >=4 && <5,
    bytestring,
    generics-sop,
    hasql >=1.9 && <1.10,
    iproute ^>=1.7,
    postgresql-binary >=0.14,
    scientific ^>=0.3,
    text,
    time,
    uuid,
    vector,

  default-language: GHC2021

library
  import: shared
  -- cabal-gild: discover lib
  exposed-modules:
    Hasql.Auto.Decoders
    Hasql.Auto.Encoders
    Hasql.Auto.Types

  hs-source-dirs: lib
