cabal-version:   3.0
name:            aztecs-gl-text
version:         0.1.0
license:         BSD-3-Clause
license-file:    LICENSE
maintainer:      matt@hunzinger.me
author:          Matt Hunzinger
homepage:        https://github.com/aztecs-hs/aztecs
synopsis:        OpenGL text rendering for Aztecs
description:     OpenGL text rendering for the Aztecs game engine and ECS
category:        Game Engine
build-type:      Simple
extra-doc-files: CHANGELOG.md

source-repository head
    type:     git
    location: https://github.com/aztecs-hs/aztecs-gl-text.git

library
    exposed-modules:
        Aztecs.GL.Text
        Aztecs.GL.Text.Font
        Aztecs.GL.Text.Font.Internal
        Aztecs.GL.Text.Label
        Aztecs.GL.Text.Label.Internal

    hs-source-dirs:   src
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.2 && <5,
        aztecs >=0.17,
        aztecs-gl >=0.3,
        containers >=0.6,
        freetype2 >=0.2,
        linear >=1,
        OpenGL >=3,
        vector >=0.10

test-suite aztecs-gl-text-test
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    hs-source-dirs:   test
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.2 && <5,
        aztecs-gl-text
