cabal-version: 3.0
name: marionette-effectful
version: 1.0.0
category: Web
synopsis: Effectful driver for Marionette
description:
  Adaptation of the @<https://hackage.haskell.org/package/marionette marionette>@ library for the @<https://hackage.haskell.org/package/effectful effectful>@ ecosystem.

license: EUPL-1.2
license-file: LICENCE
author: IDA
maintainer: IDA
homepage: https://digital-autonomy.institute
bug-reports: https://issues.digital-autonomy.institute
build-type: Simple
extra-doc-files:
  CHANGELOG.md

common common
  default-language: Haskell2010
  ghc-options:
    -Weverything
    -Wno-unsafe
    -Wno-missing-safe-haskell-mode
    -Wno-missing-export-lists
    -Wno-missing-import-lists
    -Wno-missing-kind-signatures
    -Wno-all-missed-specialisations

  default-extensions:
    ApplicativeDo
    BlockArguments
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveGeneric
    DerivingStrategies
    DerivingVia
    ExplicitNamespaces
    FlexibleContexts
    ImportQualifiedPost
    LambdaCase
    MultiParamTypeClasses
    NamedFieldPuns
    NoImplicitPrelude
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    RankNTypes
    RecordWildCards
    RecursiveDo
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators
    ViewPatterns

  build-depends:
    base >=4.16 && <5,
    effectful >=2.6 && <2.7,
    marionette >=1.0 && <1.1,

library
  import: common
  hs-source-dirs: src
  build-depends:
    mtl >=2.3 && <2.4,
    unliftio >=0.2 && <0.3,

  exposed-modules:
    Effectful.Marionette

test-suite marionette-effectful-test
  import: common
  type: exitcode-stdio-1.0
  ghc-options: -threaded
  hs-source-dirs: test
  main-is: Main.hs
  build-depends:
    aeson >=2.2 && <2.3,
    bytestring >=0.12 && <0.13,
    hspec-effectful >=1.0 && <1.1,
    http-types >=0.12 && <0.13,
    lucid2 >=0.0 && <0.1,
    marionette-effectful,
    text >=2.1 && <2.2,
    typed-process-effectful >=1.0 && <1.1,
    wai >=3.2 && <3.3,
    warp >=3.4 && <3.5,
