cabal-version: 3.0
name: hslua-annotations
version: 0.1.0
synopsis: A type annotation generator for HSLua
description: A type annotation generator for HSLua targetting LuaLS and EmmyLua
homepage: https://github.com/sondr3/hslua-annotations
bug-reports: https://github.com/sondr3/hslua-annotations/issues
license: (MIT OR Apache-2.0)
license-file: LICENSE LICENSE_APACHE
author: Sondre Aasemoen
maintainer: sondre@eons.io
category: Foreign
build-type: Simple
extra-doc-files:
  CHANGELOG.md
  README.md

tested-with:
  ghc ==9.10
  ghc ==9.12
  ghc ==9.14

source-repository head
  type: git
  location: https://github.com/sondr3/hslua-annotations.git

common config
  default-language: GHC2021
  default-extensions:
    DerivingStrategies
    DuplicateRecordFields
    LambdaCase
    MultiWayIf
    NamedFieldPuns
    OverloadedStrings
    TypeFamilies

  ghc-options:
    -Weverything
    -Wno-unsafe
    -Wno-implicit-prelude
    -Wno-missing-safe-haskell-mode
    -Wno-missing-kind-signatures
    -Wno-missing-import-lists
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Werror=missing-deriving-strategies
    -fhide-source-paths
    -fwrite-ide-info

  build-depends:
    base >=4.12 && <5,
    hslua-core ^>=2.3,
    hslua-packaging ^>=2.4,
    text >=2 && <3,

library
  import: config
  hs-source-dirs: lib
  exposed-modules:
    HsLua.Annotations

  other-modules:
    HsLua.Annotations.Internal
    HsLua.Annotations.Markdown
    HsLua.Annotations.Shared

test-suite hslua-annotations-golden
  import: config
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  build-depends:
    hslua-annotations,
    hslua-marshalling ^>=2.3,
    hslua-module-path ^>=1.2,
    hslua-module-version ^>=1.2,
    tasty ^>=1.5,
    tasty-golden ^>=2.3,

  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N
