cabal-version:  2.4
name:           holeyexp
version:        0.3.0.0
license:        BSD-3-Clause
license-file:   LICENSE.md
maintainer:     Harley Eades III <harley.eades@gmail.com>
author:         Harley Eades III

tested-with: 
    GHC == 9.8.4
    GHC == 9.10.*
    GHC == 9.12.*
    GHC == 9.14.1

homepage:       https://github.com/DevWKB/holey-expression
bug-reports:    https://github.com/DevWKB/holey-expression/issues
synopsis:       Add, fill, plug holes in monoids
description:    
    This is a library that allows you to add placeholders we call "holes" 
    to any monoid. Then these holes can be filled or plugged.

category:       Language
build-type:     Simple

extra-source-files:
    README.md
extra-doc-files:
    CHANGELOG.md

source-repository head
  type: git
  location: https://github.com/heades/holey-expression

common depends    
    build-depends:
       base             >= 4.7    && < 5          
      ,containers       >= 0.7    && < 0.8
      ,extra            >= 1.8.1  && < 1.9
      ,megaparsec       >= 9.7.0  && < 9.9
      ,text             >= 2.1.3  && < 2.2           

common test-depends
    build-depends:
       QuickCheck           >  2.15.0  && < 2.19
      ,hspec                >= 2.11.17 && < 2.12      
      ,quickcheck-instances >= 0.3.33  && < 0.5
    build-tool-depends: 
        hspec-discover:hspec-discover

library
  import: depends  
  exposed-modules:
      Data.HoleyExp.HExp
      Data.HoleyExp.HExpInternal
      Data.HoleyExp.Text
      Data.NatMap
  other-modules:
      Paths_holeyexp      
  autogen-modules:
      Paths_holeyexp
  hs-source-dirs:
      src  
  ghc-options: -Wall 
               -Wcompat 
               -Widentities 
               -Wincomplete-record-updates 
               -Wincomplete-uni-patterns 
               -Wmissing-export-lists 
               -Wmissing-home-modules 
               -Wpartial-fields 
               -Wredundant-constraints
               -Wno-name-shadowing 
  default-extensions:     
    ImportQualifiedPost
    OverloadedStrings
    InstanceSigs
    LambdaCase
    ViewPatterns
    PatternSynonyms
    GADTs
  default-language: Haskell2010

test-suite holey-expression-test
  import: depends, test-depends  
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules:
      Paths_holeyexp
      Data.HoleyExp.HExpInternalSpec
      Test.QuickCheck.HExp
      Test.Helpers
  autogen-modules:
      Paths_holeyexp
  hs-source-dirs:
      test
  ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wmissing-export-lists -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints -threaded -rtsopts -with-rtsopts=-N
  default-extensions: 
    ImportQualifiedPost
    OverloadedStrings
    InstanceSigs
    LambdaCase
    ViewPatterns
    GADTs
  build-depends:     
    ,holeyexp  
  default-language: Haskell2010
