cabal-version:   1.18
name:            bugsnag-types
version:         1.1.0.0
license:         MIT
maintainer:      pbrisbin@gmail.com
author:          Patrick Brisbin
homepage:        https://codeberg.org/pbrisbin/bugsnag-haskell#readme
synopsis:        Types for the Bugsnag error reporter for Haskell
description:     Please see README.md
category:        Web
build-type:      Simple
extra-doc-files:
    README.md
    CHANGELOG.md

library
    exposed-modules:
        Data.Bugsnag.Types.Application
        Data.Bugsnag.Types.BinaryArch
        Data.Bugsnag.Types.Breadcrumb
        Data.Bugsnag.Types.BreadcrumbType
        Data.Bugsnag.Types.DependentNotifier
        Data.Bugsnag.Types.Device
        Data.Bugsnag.Types.ErrorType
        Data.Bugsnag.Types.Event
        Data.Bugsnag.Types.Exception
        Data.Bugsnag.Types.FeatureFlag
        Data.Bugsnag.Types.Notifier
        Data.Bugsnag.Types.Payload
        Data.Bugsnag.Types.Prelude
        Data.Bugsnag.Types.Request
        Data.Bugsnag.Types.RuntimeVersion
        Data.Bugsnag.Types.Session
        Data.Bugsnag.Types.SessionEvent
        Data.Bugsnag.Types.Severity
        Data.Bugsnag.Types.SeverityReason
        Data.Bugsnag.Types.SeverityReasonAttributes
        Data.Bugsnag.Types.SeverityReasonType
        Data.Bugsnag.Types.Stackframe
        Data.Bugsnag.Types.Thread
        Data.Bugsnag.Types.User

    hs-source-dirs:     src
    other-modules:      Paths_bugsnag_types
    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingStrategies DerivingVia
        DuplicateRecordFields GADTs LambdaCase NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction NoPostfixOperators
        OverloadedRecordDot OverloadedStrings QuasiQuotes TypeFamilies

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-monomorphism-restriction -Wno-safe -Wno-unsafe

    build-depends:
        aeson >=2.0.3.0,
        base >=4.16.4.0 && <5,
        text >=1.2.5.0

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures

    if impl(ghc >=9.2)
        ghc-options: -Wno-missing-kind-signatures

    if impl(ghc >=8.10)
        ghc-options:
            -Wno-missing-safe-haskell-mode -Wno-prepositive-qualified-module

    if impl(ghc >=8.8)
        ghc-options: -fwrite-ide-info

test-suite spec
    type:               exitcode-stdio-1.0
    main-is:            Spec.hs
    hs-source-dirs:     test
    other-modules:
        Data.Bugsnag.Types.PayloadSpec
        Paths_bugsnag_types

    default-language:   GHC2021
    default-extensions:
        DataKinds DeriveAnyClass DerivingStrategies DerivingVia
        DuplicateRecordFields GADTs LambdaCase NoFieldSelectors
        NoImplicitPrelude NoMonomorphismRestriction NoPostfixOperators
        OverloadedRecordDot OverloadedStrings QuasiQuotes TypeFamilies

    ghc-options:
        -Weverything -Wno-all-missed-specialisations
        -Wno-missed-specialisations -Wno-missing-exported-signatures
        -Wno-missing-import-lists -Wno-missing-local-signatures
        -Wno-monomorphism-restriction -Wno-safe -Wno-unsafe -threaded
        -rtsopts -with-rtsopts=-N

    build-depends:
        aeson >=2.0.3.0,
        base >=4.16.4.0 && <5,
        bugsnag-types,
        hspec >=2.9.7

    if impl(ghc >=9.8)
        ghc-options:
            -Wno-missing-role-annotations -Wno-missing-poly-kind-signatures

    if impl(ghc >=9.2)
        ghc-options: -Wno-missing-kind-signatures

    if impl(ghc >=8.10)
        ghc-options:
            -Wno-missing-safe-haskell-mode -Wno-prepositive-qualified-module

    if impl(ghc >=8.8)
        ghc-options: -fwrite-ide-info
