cabal-version:   3.0
name:            from-text
version:         0.1
license:         BSD-3-Clause
license-file:    LICENSE
maintainer:      andrew.lelechenko@gmail.com
author:          Bodigrim
tested-with:
    ghc ==9.14.1 ghc ==9.12.2 ghc ==9.10.3 ghc ==9.8.4 ghc ==9.6.7
    ghc ==9.4.8 ghc ==9.2.8 ghc ==9.0.2 ghc ==8.10.7 ghc ==8.8.4
    ghc ==8.6.5

synopsis:        Type class to convert from Text
description:
    This package provides @class IsText a where fromText :: Text -> a@,
    aiming to simplify conversion from @Text@ to other textual data types,
    including @ByteArray@, @ByteString@ and @OsPath@.

category:        Text
build-type:      Simple
extra-doc-files:
    CHANGELOG.md
    README.md

source-repository head
    type:     git
    location: https://github.com/Bodigrim/from-text.git

library
    exposed-modules:  Data.Text.From
    hs-source-dirs:   src
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.12 && <5,
        bytestring >=0.12 && <0.13,
        filepath >=1.5 && <1.6,
        os-string >=2.0.2 && <2.1,
        text >=2.1.1 && <2.2

    if impl(ghc <9.4)
        build-depends: data-array-byte >=0.1 && <0.2

test-suite from-text-test
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    hs-source-dirs:   test
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base,
        bytestring,
        from-text,
        os-string,
        tasty,
        tasty-quickcheck,
        text
