cabal-version: 2.4
name: vector-pull
version: 0.1.0.0
license: MPL-2.0
copyright: 2024 Michael Ledger
maintainer: mike@quasimal.com
author: Michael Ledger
category: Data
synopsis: Pull-array data structure
description:
  An implementation of `Int`-indexed arrays that internally are represented by
  an index function enclosed over whatever backend (e.g. `Data.Vector`) you
  like.

source-repository head
  type: git
  location: https://gitlab.com/combobulate.systems/vector-pull

library
  hs-source-dirs: lib
  exposed-modules:
    Data.Vector.Pull

  ghc-options:
    -Wall
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-deriving-strategies
    -Wunused-foralls
    -Wno-name-shadowing
    -Wno-partial-type-signatures
    -Wno-missing-home-modules
    -Wno-ambiguous-fields
    -fprint-explicit-foralls
    -fprint-explicit-kinds
    -fwrite-ide-info

  default-language: GHC2021
  default-extensions:
    AllowAmbiguousTypes
    BangPatterns
    BlockArguments
    ConstraintKinds
    DataKinds
    DeriveAnyClass
    DeriveDataTypeable
    DeriveFoldable
    DeriveFunctor
    DeriveGeneric
    DeriveLift
    DeriveTraversable
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    EmptyCase
    EmptyDataDecls
    EmptyDataDeriving
    ExistentialQuantification
    ExplicitForAll
    FlexibleContexts
    FlexibleInstances
    FunctionalDependencies
    GADTSyntax
    GeneralisedNewtypeDeriving
    ImportQualifiedPost
    ImpredicativeTypes
    InstanceSigs
    KindSignatures
    LambdaCase
    MultiParamTypeClasses
    MultiWayIf
    NamedFieldPuns
    NoStarIsType
    NumericUnderscores
    OverloadedLabels
    OverloadedLists
    OverloadedRecordDot
    OverloadedStrings
    PackageImports
    PartialTypeSignatures
    PatternSynonyms
    PolyKinds
    PostfixOperators
    QualifiedDo
    QuasiQuotes
    RankNTypes
    ScopedTypeVariables
    StandaloneDeriving
    StandaloneKindSignatures
    StrictData
    TemplateHaskell
    TupleSections
    TypeAbstractions
    TypeApplications
    TypeFamilies
    TypeFamilyDependencies
    TypeOperators
    UndecidableInstances
    ViewPatterns

  build-depends:
    atomic-counter ^>=0.1,
    base >=4.13 && <4.22,
    exceptions ^>=0.10,
    optics-core ^>=0.4,
    streaming ^>=0.2,
    vector ^>=0.13,

test-suite vector-pull
  type: exitcode-stdio-1.0
  main-is: spec.hs
  hs-source-dirs: tests
  build-depends:
    base,
    hedgehog,
    hspec,
    hspec-hedgehog,
    vector,
    vector-pull,

  ghc-options:
    -Wall
    -Wno-partial-type-signatures

  default-language: GHC2021
  default-extensions:
    AllowAmbiguousTypes
    BangPatterns
    BlockArguments
    DataKinds
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    ExplicitNamespaces
    FlexibleContexts
    FlexibleInstances
    ImportQualifiedPost
    OverloadedLists
    OverloadedStrings
    PartialTypeSignatures
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators
    TypeSynonymInstances
    UndecidableInstances
