cabal-version: 1.12
name:           first-class-instances
version:        1.0.0.0
synopsis:       First class typeclass instances
description:    See the README file in the project repository
category:       Language
author:         Matej Nižník
maintainer:     lysxia@gmail.com
copyright:      2019 Matej Nižník
license:        BSD3
license-file:   LICENSE
build-type:     Simple
extra-source-files:
    README.md
    CHANGELOG.md

source-repository head
  type: git
  location: https://gitlab.com/thematten/first-class-instances

library
  exposed-modules:
      FCI
      FCI.Base
      FCI.TH
      FCI.Unsafe
      FCI.Internal
      FCI.Internal.TH
  hs-source-dirs:
      src
  ghc-options: -ferror-spans -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wmissing-export-lists -Widentities -Wredundant-constraints -Wpartial-fields -Wcompat
  build-depends:
      base >=4.13 && <5
    , containers >=0.6.0.1 && <0.9
    , template-haskell >=2.15 && <2.24
    , transformers >=0.6 && <0.7
  default-language: Haskell2010

test-suite test-fci
  type: exitcode-stdio-1.0
  main-is: test-fci.hs
  hs-source-dirs: test
  ghc-options: -ferror-spans -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wmissing-export-lists -Widentities -Wredundant-constraints -Wpartial-fields -Wcompat -threaded -rtsopts -with-rtsopts=-N
  -- ghc-options: -ddump-splices
  build-depends:
      base
    , first-class-instances
    , tasty
    , tasty-hunit
    , template-haskell
  default-language: Haskell2010
